import 'dart:core';

class de_DE {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': 'Ja',
      'no': 'Nein',
      'cancel': 'Abbrechen',
      'OK': 'OK',
      'reset': 'Zurücksetzen',
      'success': 'Erfolg',
      'error': 'Fehler',
      'failed': 'Fehlgeschlagen',
      'reload': 'Neu laden',
      'noMoreData': 'Keine weiteren Daten',
      'noData': 'Keine Daten',
      'operationFailed': 'Vorgang fehlgeschlagen',
      'needLoginToOperate': 'Anmeldung erforderlich',
      'hasCopiedToClipboard': 'In die Zwischenablage kopiert',
      'networkError': 'Netzwerkfehler, zum Neu laden tippen',
      'systemError': 'Systemfehler',
      'invalid': 'Ungültig',
      'internalError': 'Interner Fehler',
      'you': 'Sie',
      'retryHint': 'Bitte nach Aktualisierung erneut versuchen',
      'stop': 'Stoppen',
      'attention': 'Achtung',
      'jump': 'Springen',
      'deleteAll': 'Alle löschen',
      'connectionTimeoutHint': 'Netzwerkverbindungs-Timeout',
      'receiveDataTimeoutHint': 'Datenempfangs-Timeout',
      'archiveError': 'Fehler beim Herunterladen des Archivs',
      'edit': 'Bearbeiten',

      'home': 'Startseite',
      'gallery': 'Galerie',
      'setting': 'Einstellungen',

      /// schedule
      'dawnOfaNewDay': 'Es ist die Morgendämmerung eines neuen Tages!',
      'encounterMonster': 'Sie haben ein Monster angetroffen!',
      'encounterMonsterHint': 'Klicken Sie, um im HentaiVerse zu kämpfen.',

      /// unlock
      'localizedReason': 'Bitte authentifizieren Sie sich, um fortzufahren',
      'tap2Auth': 'Zum Authentifizieren tippen',
      'passwordErrorHint': 'Falsches Passwort, bitte erneut versuchen',

      /// start
      'TapAgainToExit': 'Erneut tippen zum Beenden',

      /// update
      'availableUpdate': 'Update verfügbar!',
      'LatestVersion': 'Neueste Version',
      'CurrentVersion': 'Aktuelle Version',
      'check': 'Prüfen',
      'dismiss': 'Schließen',

      /// login
      'login': 'Anmelden',
      'notLoggedIn': 'Anmelden',
      'logout': 'Abmelden',
      'passwordLogin': 'Passwort-Anmeldung',
      'cookieLogin': 'Cookie-Anmeldung',
      'useWebview': 'Webview verwenden',
      'skipCookieVerification': 'Überprüfung überspringen',
      'youHaveLoggedInAs': 'Hallo:   ',
      'cookieIsBlack': 'Cookie auf Sperrliste',
      'cookieFormatError': 'Cookie-Formatfehler',
      'invalidCookie': 'Anmeldung fehlgeschlagen oder ungültiges Cookie',
      'loginFail': 'Anmeldung fehlgeschlagen',
      'userName': 'Benutzername',
      'EHUser': 'EH-Benutzer',
      'password': 'Passwort',
      'needCaptcha': 'Captcha erforderlich, bitte über Cookie oder Web erneut anmelden.',
      'userNameOrPasswordMismatch': 'Benutzername oder Passwort falsch',
      'copyCookies': 'Cookies kopieren',
      'tap2Copy': 'Zum Kopieren tippen',
      'webLoginIsDisabled': 'Web-Anmeldung auf dem Desktop deaktiviert',
      'loginSuccess': 'Anmeldung erfolgreich',
      'userNameFormHint': 'Bei Sad Panda Cookie verwenden',
      'tap2Login': 'Anmelden',
      'parse': 'Parsen',
      'igneousHint': 'igneous (EX erforderlich)',
      'refreshIgneousFailed': 'Aktualisierung von Igneous fehlgeschlagen',

      /// request
      'sadPanda': 'Sad Panda (keine Daten). Siehe: https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',

      /// gallery card
      'filtered': 'Gefiltert',

      /// gallery page
      'getGallerysFailed': 'Laden der Galerien fehlgeschlagen',
      'refreshGalleryFailed': 'Aktualisierung der Galerie fehlgeschlagen',
      'tabBarSetting': 'Tab-Leisten-Einstellungen',
      'jumpPageTo': 'Zur Seite springen',
      'range': 'Bereich',
      'current': 'Aktuell',
      'galleryUrlDetected': 'Galerie-URL in Zwischenablage gefunden',
      'galleryUrlDetectedHint': 'Tippen, um zur Detailseite zu gelangen',

      /// details
      'read': 'Lesen',
      'download': 'Herunterladen',
      'favorite': 'Favorit',
      'rating': 'Bewertung',
      'torrent': 'Torrent',
      'archive': 'Archiv',
      'statistic': 'Statistik',
      'similar': 'Ähnlich',
      'downloading': 'Wird heruntergeladen',
      'resume': 'Fortsetzen',
      'pause': 'Pausieren',
      'finished': 'Fertig',
      'update': 'Aktualisieren',
      'submit': 'Absenden',
      'chooseFavorite': 'Favorit wählen',
      'asYourDefault': 'Als Standard',
      'Note': 'Notiz',
      'addNoteHint': 'Bitte zuerst einen Slot auswählen, bevor Sie eine Notiz hinzufügen',
      'uploader': 'Hochlader',
      'allComments': 'Alle Kommentare',
      'noComments': 'Keine Kommentare',
      'lastEditedOn': 'Zuletzt bearbeitet am',
      'getGalleryDetailFailed': 'Details der Galerie konnten nicht geladen werden',
      'cloudflare403': 'Sie wurden von Cloudflare bei Netzwerkanfragen eingeschränkt. Versuchen Sie, das Netzwerk zu wechseln oder eine andere Anmeldemethode zu verwenden.',
      'invisible2User': 'Diese Galerie ist für Sie nicht sichtbar',
      'invisibleHints': 'Diese Galerie wurde gelöscht oder ist nicht verfügbar.',
      'copyRightHints': 'Diese Galerie ist aufgrund eines Urheberrechtsanspruchs nicht verfügbar:',
      'refreshGalleryDetailsFailed': 'Aktualisierung der Details fehlgeschlagen',
      'failToGetThumbnails': 'Miniaturansichten konnten nicht geladen werden',
      'favoriteGallerySuccess': 'Galerie zu Favoriten hinzugefügt',
      'favoriteGalleryFailed': 'Hinzufügen zu Favoriten fehlgeschlagen',
      'removeFavoriteSuccess': 'Favorit erfolgreich entfernt',
      'removeFavoriteFailed': 'Entfernen des Favoriten fehlgeschlagen',
      'getGalleryFavoriteInfoFailed': 'Favoriteninfos konnten nicht geladen werden',
      'favoriteNoteSlotFullHint': 'Alle Notizslots belegt, bitte zuerst einige Notizen löschen',
      'ratingSuccess': 'Bewertung erfolgreich',
      'ratingFailed': 'Bewertung fehlgeschlagen',
      'voteTagFailed': 'Tag-Abstimmung fehlgeschlagen',
      'beginToDownload': 'Download beginnt',
      'resumeDownload': 'Download fortsetzen',
      'pauseDownload': 'Download pausieren',
      'addNewTagSetSuccess': 'Neues Tag-Set erfolgreich hinzugefügt',
      'addNewWatchedTagSetSuccess': 'Neues überwachtes Tag-Set hinzugefügt',
      'addNewHiddenTagSetSuccess': 'Neues ausgeblendetes Tag-Set hinzugefügt',
      'addNewTagSetSuccessHint': 'Sie können Ihre Tags unter Einstellungen->EH->Meine Tags einsehen',
      'addNewTagSetFailed': 'Hinzufügen des Tag-Sets fehlgeschlagen',
      'VisitorStatistics': 'Besucherstatistiken',
      'invisible2UserWithoutDonation': 'Statistiken dieser Galerie sind für Nicht-Spender verborgen',
      'getGalleryStatisticsFailed': 'Statistiken konnten nicht geladen werden',
      'totalVisits': 'Gesamtbesuche',
      'visits': 'Besuche',
      'imageAccesses': 'Bildzugriffe',
      'period': 'Zeitraum',
      'ranking': 'Rang',
      'score': 'Punktzahl',
      'NotOnTheList': 'Nicht in der Liste',
      'getGalleryArchiveFailed': 'Archiv konnte nicht geladen werden',
      'parseGalleryArchiveFailed': 'Analyse fehlgeschlagen. Bitte prüfen Sie, ob Ihre Archivierer-Einstellung auf e-hentai auf [Manuelle Auswahl, manueller Start (Standard)] gesetzt ist',
      'original': 'Original',
      'resample': 'Neu abtasten',
      'beginToDownloadArchive': 'Archiv-Download beginnt',
      'beginToDownloadArchiveHint': 'Fortschritt unter Herunterladen -> Archiv einsehen',
      'updateGalleryError': 'Fehler beim Aktualisieren der Galerie',
      'thisGalleryHasANewVersion': 'Diese Galerie hat eine neue Version',
      'hasUpdated': 'Aktualisiert',
      'unpackingArchiveError': 'Fehler beim Entpacken des Archivs',
      'failedToDealWith': 'Verarbeitung fehlgeschlagen',
      'hasDownloaded': 'Heruntergeladen',
      '410Hints': 'Die Download-Bytes dieses Archivs haben das Limit überschritten. Sie müssen das Archiv erneut entsperren.',
      '429Hints': 'Zu viele Download-Anfragen! Bitte reduzieren Sie die Archiv-Download-Parallelität.',
      'getUnpackedImagesFailedMsg': 'JHenTai kann die Bilder dieses Archivs nicht laden. Bitte überprüfen Sie Ihre lokalen Dateien.',
      'getGalleryTorrentsFailed': 'Torrents konnten nicht geladen werden',
      'chooseArchive': 'Archiv auswählen',
      'tagSetExceedLimit': 'Kein weiteres Tag hinzufügbar, Limit erreicht',
      'useTranslation': 'Übersetzung verwenden',
      'addTagSuccess': 'Tag erfolgreich hinzugefügt',
      'addTagFailed': 'Tag-Hinzufügen fehlgeschlagen',
      'parentGallery': 'Übergeordnete Galerie',
      'blockUploaderLocally': 'Benutzer lokal sperren',
      'block': 'Sperren',

      /// detail dialog
      'galleryUrl': 'Galerie-URL',
      'title': 'Titel',
      'japaneseTitle': 'Japanischer Titel',
      'category': 'Kategorie',
      'publishTime': 'Veröffentlichungszeit',
      'pageCount': 'Seitenanzahl',
      'favoriteCount': 'Favoritenanzahl',
      'ratingCount': 'Bewertungsanzahl',

      /// comments
      'newComment': 'Neuer Kommentar',
      'updateComment': 'Kommentar aktualisieren',
      'commentTooShort': 'Kommentar zu kurz',
      'sendCommentFailed': 'Senden des Kommentars fehlgeschlagen',
      'voteCommentFailed': 'Abstimmung für Kommentar fehlgeschlagen',
      'voteCommentFailedHint': 'Versuchen Sie zuerst, die Detailseite nach unten zu ziehen und zu aktualisieren',
      'unknownUser': 'Unbekannter Benutzer',
      'atLeast3Characters': 'Mindestens 3 Zeichen erforderlich',
      'noJHenTaiHints': 'Bitte JHenTai nicht erwähnen',
      'blockUser': 'Benutzer sperren',

      /// EHImage
      'reloadImage': 'Bild neu laden',

      /// read page
      'parsingPage': 'Seite wird geparst',
      'parsingURL': 'URL wird geparst',
      'parsePageFailed': 'Parsen der Seite fehlgeschlagen, zum Wiederholen tippen',
      'parseURLFailed': 'Parsen der URL fehlgeschlagen, zum Wiederholen tippen',
      'loading': 'Laden',
      'paused': 'Pausiert',
      'exceedImageLimits': 'Bildlimit überschritten',
      'ehServerError': 'Ein EH-Serverfehler ist aufgetreten. Bitte später erneut versuchen.',
      'unsupportedImagePageStyle': 'JHenTai unterstützt den Multi-Page-Viewer (MPV) nicht. Bitte wechseln Sie auf e-hentai.org zum Standard-Stil.',
      'toNext': 'Weiter',
      'toPrev': 'Zurück',
      'back': 'Zurück',
      'toggleMenu': 'Menü umschalten',
      'share': 'Teilen',
      'save': 'Als Bild speichern',

      /// setting page
      'account': 'Konto',
      'EH': 'EH',
      'style': 'Stil',
      'preference': 'Einstellungen',
      'network': 'Netzwerk',
      'performance': 'Leistung',
      'mouseWheel': 'Mausrad',
      'advanced': 'Erweitert',
      'cloud': 'Cloud',
      'security': 'Sicherheit',
      'about': 'Über',
      'accountSetting': 'Kontoeinstellungen',
      'styleSetting': 'Stileinstellungen',
      'advancedSetting': 'Erweiterte Einstellungen',
      'securitySetting': 'Sicherheitseinstellungen',
      'ehSetting': 'EH-Website-Einstellungen',
      'readSetting': 'Leseeinstellungen',
      'preferenceSetting': 'Voreinstellungen',
      'downloadSetting': 'Download-Einstellungen',
      'networkSetting': 'Netzwerkeinstellungen',
      'performanceSetting': 'Leistungseinstellungen',
      'mouseWheelSetting': 'Mausrad-Einstellungen',

      /// eh setting
      'site': 'Website',
      'redirect2Eh': 'Falls verfügbar zu EH weiterleiten',
      'redirect2EhHint': 'Versuchen Sie zuerst, die Galerie-Detailseite der EH-Website zu laden für bessere Netzwerkleistung',
      'redirectAllGallery': 'Alle Galerien zu EH weiterleiten',
      'imDonorHint': 'Wenn Sie Spender sind, aktivieren Sie dies, um Galerien auf der EX-Website zu öffnen',
      'profileSetting': 'Profileinstellungen',
      'chooseProfileHint': 'Wählen Sie das in JHenTai verwendete Profil',
      'siteSetting': 'Website-Einstellungen',
      'siteSettingHint': 'Website-Einstellungen auf e-hentai bearbeiten',
      'showCookie': 'Cookie',
      'redirect2EH': 'Falls verfügbar zur EH-Website weiterleiten',
      'redirect2Hints': 'Versucht zuerst, die EH-Website zu parsen',
      'pleaseLogInToOperate': 'Bitte anmelden, um zu arbeiten',
      'imageLimits': 'Bildkontingent',
      'resetCost': 'Lang drücken zum Zurücksetzen, Kosten',
      'assets': 'Vermögenswerte',
      'isNotDonator': 'Nicht-Spender können das Kontingent nicht einsehen',
      'fetchImageQuotaFailed': 'Bildkontingent konnte nicht abgerufen werden',

      /// tags
      'myTags': 'Meine Tags',
      'myTagsHint': 'Überwachte/ausgeblendete Tags online verwalten',
      'localTags': 'Lokale Tags',
      'localTagsHint': 'Zusätzliche Filter-Tags',
      'localTagsHint2': 'Galerien mit diesen Tags werden ausgeblendet',
      'addLocalTags': 'Tags hinzufügen',
      'hidden': 'Ausgeblendet',
      'nope': 'Nein',
      'getTagSetFailed': 'Tag-Set konnte nicht abgerufen werden',
      'updateTagSetFailed': 'Tag-Set-Aktualisierung fehlgeschlagen',
      'updateTagFailed': 'Tag-Aktualisierung fehlgeschlagen',
      'deleteTagSuccess': 'Tag erfolgreich gelöscht',
      'deleteTagFailed': 'Tag-Löschen fehlgeschlagen',
      'addLocalTagHint': 'Suchen, um ein neues Tag hinzuzufügen',

      /// Profile
      'selectedProfile': 'Ausgewähltes Profil',
      'resetIfSwitchSite': 'Wird beim Website-Wechsel zurückgesetzt',

      /// host mapping
      'addHostMapping': 'Host-Zuordnung hinzufügen',

      /// Layout
      'layoutMode': 'Layout-Modus',
      'mobileLayoutV2Name': 'Mobil',
      'mobileLayoutV2Desc': 'Einspaltig',
      'mobileLayoutName': 'Mobil (Alt)',
      'mobileLayoutDesc': 'Wird nicht mehr gewartet',
      'tabletLayoutV2Name': 'Tablet',
      'tabletLayoutV2Desc': 'Zweispaltig',
      'tabletLayoutName': 'Tablet (Alt)',
      'tabletLayoutDesc': 'Wird nicht mehr gewartet',
      'desktopLayoutName': 'Desktop',
      'desktopLayoutDesc': 'Zweispaltig mit linker Tab-Leiste, Tastaturunterstützung',

      /// style
      'enableTagZHTranslation': 'Tag-Namen ins Chinesische übersetzen',
      'version': 'Version',
      'downloadTagTranslationHint': 'Daten werden heruntergeladen... Heruntergeladen:',
      'zhTagSearchOrderOptimization': 'Sortirregel für chinesische Tag-Autovervollständigung',
      'zhTagSearchOrderOptimizationHint': 'Standardmäßig intelligente Sortierung, bei Aktivierung nach Häufigkeit',
      'themeMode': 'Themen-Modus',
      'dark': 'Dunkel',
      'light': 'Hell',
      'followSystem': 'System folgen',
      'themeColor': 'Themenfarbe',
      'listStyle': 'Galerie-Listenstil (Global)',
      'flat': 'Flach',
      'flatWithoutTags': 'Flach (ohne Tags)',
      'listWithoutTags': 'Karte (ohne Tags)',
      'listWithTags': 'Karte',
      'waterfallFlowSmall': 'Wasserfall (Klein)',
      'waterfallFlowMedium': 'Wasserfall (Mittel)',
      'waterfallFlowBig': 'Wasserfall (Groß)',
      'crossAxisCountInWaterFallFlow': 'Wasserfallspalten',
      'pageListStyle': 'Listenstil (Seite)',
      'crossAxisCountInGridDownloadPageForGroup': 'Download-Rasterspalten (Gruppe)',
      'crossAxisCountInGridDownloadPageForGallery': 'Download-Rasterspalten (Galerie)',
      'crossAxisCountInDetailPage': 'Miniaturansichts-Spalten (Detail)',
      'global': 'Global',
      'auto': 'Automatisch',
      'moveCover2RightSide': 'Cover nach rechts verschieben',
      'coverStyle': 'Cover-Stil',
      'cover': 'Cover',
      'adaptive': 'Adaptiv',
      'simpleDashboardMode': 'Vereinfachte Startseite',
      'simpleDashboardModeHint': 'Rangliste und Beliebt ausblenden',
      'hideBottomBar': 'Untere Leiste ausblenden',
      'hideScroll2TopButton': 'Scroll-nach-oben-Schaltfläche ausblenden',
      'whenScrollUp': 'Beim Hochscrollen',
      'whenScrollDown': 'Beim Runterscrollen',
      'preloadGalleryCover': 'Galeriecover vorladen',
      'preloadGalleryCoverHint': 'Cover von noch nicht angezeigten Galerien vorladen',
      'enableSwipeBackGesture': 'Wischgeste zum Zurückgehen aktivieren',
      'enableLeftMenuDrawerGesture': 'Linkes Menü-Drawer-Geste aktivieren',
      'enableQuickSearchDrawerGesture': 'Schnellsuche-Drawer-Geste aktivieren',
      'drawerGestureEdgeWidth': 'Drawer-Gesten-Randbreite',
      'alwaysShowScroll2TopButton': 'Scroll-nach-oben-Schaltfläche immer anzeigen',
      'enableDefaultFavorite': 'Standard-Favoriten aktivieren',
      'enableDefaultFavoriteHint': 'Lang drücken für erneute Auswahl',
      'enableDefaultTagSet': 'Standard-Tag-Set aktivieren',
      'enableDefaultTagSetHint': 'Lang drücken für erneute Auswahl',
      'disableDefaultTagSetHint': 'Manuell auswählen',
      'launchInFullScreen': 'Im Vollbildmodus starten',
      'launchInFullScreenHint': 'Manuell mit F11 umschalten',
      'disableDefaultFavoriteHint': 'Manuell auswählen',
      'searchBehaviour': 'Suchverhalten',
      'inheritAll': 'Alles übernehmen',
      'inheritAllHint': 'Letzte Suchoptionen für die nächste Suche verwenden',
      'inheritPartially': 'Teilweise übernehmen',
      'inheritPartiallyHint': 'Letzte Suchoptionen verwenden (außer Sprache und Kategorie)',
      'none': 'Kein',
      'noneHint': 'Standard-Suchoptionen für nächste Suche verwenden',
      'showAllGalleryTitles': 'Alle Galerietitel anzeigen',
      'showAllGalleryTitlesHint': 'Original- und japanische Titel anzeigen, falls verfügbar',
      'showGalleryTagVoteStatus': 'Tag-Abstimmungsstatus der Galerie anzeigen',
      'showGalleryTagVoteStatusHint': 'Enthält Vertrauen, Skepsis und Ungenauigkeit',
      'showComments': 'Kommentare anzeigen',
      'showAllComments': 'Alle Kommentare anzeigen',
      'showAllCommentsHint': 'Standardmäßig werden nur die 45 am besten bewerteten und die 5 neuesten Kommentare angezeigt',
      'addTag': 'Tag hinzufügen',
      'addTagHint': 'Neue Tags eingeben, durch Komma getrennt',

      /// theme color
      'themeColorSettingHint': 'Verschiedene Farben für helles und dunkles Thema festlegen',
      'preview': 'Vorschau',
      'preset': 'Voreinstellung',
      'custom': 'Benutzerdefiniert',

      /// performance
      'maxGalleryNum4Animation': 'Max. Galerienanzahl für Listen-Animation',
      'maxGalleryNum4AnimationHint': 'Animation für Gruppen mit mehr Galerien als diesem Wert deaktivieren (Listenstil)',

      /// mouse wheel
      'wheelScrollSpeed': 'Mausrad-Scrollgeschwindigkeit',
      'ineffectiveInGalleryPage': 'Derzeit auf der Galerie-Seite nicht wirksam.',

      /// advanced
      'enableDomainFronting': 'Domain-Fronting aktivieren',
      'bypassSNIBlocking': 'SNI-Blockierung umgehen',
      'hostMapping': 'Host-Zuordnung',
      'hostMappingHint': 'Für Domain-Fronting verwendet',
      'proxyAddress': 'Proxy-Adresse',
      'proxyAddressHint': 'Korrekt einstellen, wenn ein Proxy-Server verwendet wird',
      'saveSuccess': 'Speichern erfolgreich',
      'saveFailed': 'Speichern fehlgeschlagen',
      'updateSuccess': 'Aktualisierung erfolgreich',
      'connectTimeout': 'Verbindungs-Timeout',
      'receiveTimeout': 'Empfangs-Timeout',
      'pageCacheMaxAge': 'Maximales Seitenalter im Cache',
      'pageCacheMaxAgeHint': 'Seite aktualisieren, um Cache zu erneuern',
      'cacheImageExpireDuration': 'Ablaufdauer des Bild-Caches',
      'cacheImageExpireDurationHint': 'Bild-Cache nach App-Start automatisch löschen',
      'oneMinute': '1 Minute',
      'tenMinute': '10 Minuten',
      'oneHour': '1 Stunde',
      'oneDay': '1 Tag',
      'threeDay': '3 Tage',
      'enableLogging': 'Protokollierung aktivieren',
      'enableVerboseLogging': 'Ausführliche Protokollierung aktivieren',
      'openLog': 'Protokoll öffnen',
      'clearLogs': 'Protokolle löschen',
      'clearImagesCache': 'Bild-Cache löschen',
      'longPress2Clear': 'Lang drücken zum Löschen',
      'checkUpdateAfterLaunchingApp': 'Nach dem Start auf Updates prüfen',
      'checkClipboard': 'Galerie-URL in Zwischenablage prüfen',
      'clearPageCache': 'Seiten-Cache löschen',
      'clearSuccess': 'Löschen erfolgreich',
      'superResolution': 'Super-Auflösung',
      'stopSuperResolution': 'Super-Auflösung stoppen',
      'deleteSuperResolvedImage': 'Super-aufgelöstes Bild löschen',
      'superResolveOriginalImageHint': 'Die Verarbeitung des Originalbilds benötigt mehr Zeit, Speicherplatz und Rechenleistung. Fortfahren?',
      'verityAppLinks4Android12': 'App-Links verifizieren (Android 12+)',
      'verityAppLinks4Android12Hint': 'Für Android 12+ müssen Sie den Link manuell zu verifizierten Links hinzufügen, um JHenTai aus Drittanbieter-Apps zu öffnen',
      'noImageMode': 'Ohne-Bild-Modus',
      'exportData': 'Daten exportieren',
      'exportDataHint': 'Einstellungen, Blockierregeln und Verlauf exportieren',
      'selectExportItems': 'Zu exportierende Elemente auswählen',
      'importData': 'Daten importieren',
      'importDataHint': 'Die App wird nach dem Import automatisch beendet, um die neueste Konfiguration anzuwenden',

      /// host mapping page
      'hostDataSource': 'Standardmäßig nicht ändern.\nDatenquelle: https://dns.google/',

      /// proxy
      'proxySetting': 'Proxy-Einstellungen',
      'proxyType': 'Proxy-Typ',
      'systemProxy': 'System',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRECT',
      'address': 'Adresse',

      /// security
      'enablePasswordAuth': 'Passwort-Authentifizierung aktivieren',
      'enableBiometricAuth': 'Biometrische Authentifizierung aktivieren',
      'enableAuthOnResume': 'Authentifizierung beim Fortsetzen aktivieren',
      'enableAuthOnResumeHints': '3 Sekunden Verzögerung',
      'enableBlurBackgroundApp': 'Seite beim Wechsel in den Hintergrund unscharf machen',
      'hideImagesInAlbum': 'Bilder im Album ausblenden',
      'hideImagesInAlbumHints': 'Wenn Sie den Standard-Download-Pfad geändert haben, müssen Sie .nomedia manuell erstellen',

      /// read setting
      'enableImmersiveMode': 'Immersiven Modus aktivieren',
      'keepScreenAwakeWhenReading': 'Bildschirm beim Lesen wach halten',
      'enableCustomReadBrightness': 'Benutzerdefinierte Helligkeit beim Lesen aktivieren',
      'spaceBetweenImages': 'Abstand zwischen Bildern',
      'enableImmersiveHint': 'Systemleiste ausblenden',
      'enableImmersiveHint4Windows': 'Titelleiste ausblenden',
      'deviceOrientation': 'Gerätausrichtung',
      'landscape': 'Querformat',
      'portrait': 'Hochformat',
      'readDirection': 'Leserichtung',
      'notchOptimization': 'Notch-Optimierung',
      'notchOptimizationHint': 'Abstand vor dem ersten Bild hinzufügen, um Notch und Statusleiste zu vermeiden',
      'imageRegionWidthRatio': 'Breiten-Verhältnis des Bildbereichs',
      'gestureRegionWidthRatio': 'Breiten-Verhältnis des Gestenbereichs',
      'useThirdPartyViewer': 'Benutzerdefinierten Viewer verwenden',
      'thirdPartyViewerPath': 'Pfad des Viewers (ausführbare Datei)',
      'showThumbnails': 'Miniaturansichten anzeigen',
      'showScrollBar': 'Scrollleiste anzeigen',
      'showStatusInfo': 'Status unten anzeigen',
      'autoModeInterval': 'Automatisches Seitenintervall',
      'autoModeStyle': 'Automatik-Modus-Stil',
      'scroll': 'Scrollen',
      'turnPage': 'Seite umblättern',
      'top2bottomList': 'Von oben nach unten (Fortlaufend)',
      'left2rightSinglePage': 'Von links nach rechts (Einzelseite)',
      'left2rightSinglePageFitWidth': 'Von links nach rechts (Breite anpassen)',
      'right2leftSinglePage': 'Von rechts nach links (Einzelseite)',
      'right2leftSinglePageFitWidth': 'Von rechts nach links (Breite anpassen)',
      'left2rightDoubleColumn': 'Von links nach rechts (Doppelspalte)',
      'right2leftDoubleColumn': 'Von rechts nach links (Doppelspalte)',
      'left2rightList': 'Von links nach rechts (Fortlaufend)',
      'right2leftList': 'Von rechts nach links (Fortlaufend)',
      'enablePageTurnByVolumeKeys': 'Lautstärketasten zum Blättern verwenden',
      'enablePageTurnAnime': 'Seitenblätter-Animation aktivieren',
      'enableDoubleTapToScaleUp': 'Doppel-Tap zum Vergrößern aktivieren',
      'enableTapDragToScaleUp': 'Tap-Ziehen zum Vergrößern aktivieren',
      'enableBottomMenu': 'Unteres Menü aktivieren',
      'reverseTurnPageDirection': 'Seitenblätter-Richtung umkehren',
      'disableGestureWhenScrolling': 'Geste beim Scrollen deaktivieren',
      'disablePageTurningOnTap': 'Seitenblättern bei Tap deaktivieren',
      'turnPageMode': 'Seitenblätter-Modus',
      'turnPageModeHint': 'Zum nächsten Bildschirm oder nächsten Bild',
      'enableImageMaxKilobytes': 'Bildkomprimierung aktivieren',
      'imageMaxKilobytes': 'Maximale Bildgröße',
      'imageMaxKilobytesHint': 'Bilder die größer als diese Größe sind, werden komprimiert',
      'image': 'Bild',
      'screen': 'Bildschirm',
      'preloadDistanceInOnlineMode': 'Vorladeabstand (Online)',
      'preloadDistanceInLocalMode': 'Vorladeabstand (Lokal)',
      'ScreenHeight': 'Bildschirm',
      'preloadPageCount': 'Vorladeseiten (Online)',
      'preloadPageCountInLocalMode': 'Vorladeseiten (Lokal)',
      'continuousScroll': 'Kontinuierliches Scrollen',
      'continuousScrollHint': 'Mehrere Bilder verbinden',
      'doubleColumn': 'Doppelspalte',
      'displayFirstPageAlone': 'Erste Seite allein anzeigen',
      'displayFirstPageAloneGlobally': 'Erste Seite allein anzeigen (Global)',
      'toggleFullScreen': 'Vollbild umschalten',
      'enableAutoScaleUp': 'Automatisches Skalieren langer Bilder aktivieren',
      'enableAutoScaleUpHints': 'Bildbreite an Bildschirmbreite anpassen',

      /// preference
      'showR18GImageDirectly': 'R18G-Bilder direkt anzeigen',
      'defaultTab': 'Standard-Tab',
      'showUtcTime': 'UTC-Zeit für Galerie anzeigen',
      'showDawnInfo': 'Morgendämmerungs-Ereignis anzeigen',
      'showEncounterMonster': 'HentaiVerse-Monster-Begegnungs-Ereignis anzeigen',

      /// log
      'logList': 'Protokollliste',

      /// super resolution
      'downloadSuperResolutionModelHint': 'Modell von Github herunterladen',
      'modelDirectoryPath': 'Modellverzeichnispfad',
      'upSamplingScale': 'Hochskalierungsfaktor',
      'modelType': 'Modell wählen',
      'x4plusHint': 'Benötigt mehr Speicher, aber im Allgemeinen schneller',
      'x4plusAnimeHint': 'Benötigt weniger Speicher, aber im Allgemeinen langsamer',
      'enable4OnlineReading': 'Beim Online-Lesen automatisch verarbeiten',

      /// download page
      'local': 'Lokal',
      'reDownload': 'Erneut herunterladen',
      'delete': 'Löschen',
      'deleteTask': 'Nur Aufgabe löschen',
      'deleteTaskAndImages': 'Aufgabe und Bilder löschen',
      'unlocking': 'Wird entsperrt',
      'unlocked': 'Entsperrt',
      'parsingDownloadPageUrl': 'Analyse I',
      'parsedDownloadPageUrl': 'Analyse I',
      'parsingDownloadUrl': 'Analyse II',
      'parsedDownloadUrl': 'Analyse II',
      'waitingIsolate': 'Wartend',
      'downloaded': 'Heruntergeladen',
      'downloadFailed': 'Download fehlgeschlagen',
      'unpacking': 'Wird entpackt',
      'completed': 'Abgeschlossen',
      'needReUnlock': 'Erneutes Entsperren erforderlich',
      'reUnlock': 'Erneut entsperren',
      'reUnlockHint': 'Achtung! Sie müssen dieses Archiv neu kaufen, um es erneut zu entsperren.',
      'downloadHelpInfo': 'Wenn Sie nicht herunterladen können oder Fehler wie fehlende Tabellen auftreten, deinstallieren und reinstallieren Sie die App.',
      'localGalleryHelpInfo': 'Galerien laden, die nicht von JHenTai heruntergeladen wurden. Konfiguration unter Download-Einstellungen -> Zusätzlicher Galerie-Scan-Pfad hinzufügen und aktualisieren.',
      'localGalleryHelpInfo4iOSAndMacOS': 'Galerien laden, die nicht von JHenTai heruntergeladen wurden. Galerien in den Standard-Download-Pfad legen und aktualisieren.',
      'deleteLocalGalleryHint': 'Lokale Dateien löschen',
      'priority': 'Priorität',
      'highest': 'Höchste',
      'default': 'Standard',
      'newGalleryCount': 'Neue Galerien',
      'changePriority': 'Priorität ändern',
      'changeGroup': 'Gruppe ändern',
      'chooseGroup': 'Gruppe wählen',
      'renameGroup': 'Gruppe umbenennen',
      'deleteGroup': 'Gruppe löschen',
      'existingGroup': 'Vorhandene Gruppe',
      'groupName': 'Gruppenname',
      'drag2sort': 'Ziehen zum Sortieren',
      'switch2GridMode': 'Zur Rasteransicht wechseln',
      'switch2ListMode': 'Zur Listenansicht wechseln',
      'multiSelect': 'Mehrfachauswahl',
      'multiSelectHint': 'Zum Auswählen tippen',
      'resumeAllTasks': 'Alle Aufgaben fortsetzen',
      'pauseAllTasks': 'Alle Aufgaben pausieren',
      'requireDownloadComplete': 'Vollständigen Download erforderlich',
      'operationHasCompleted': 'Der Vorgang wurde abgeschlossen',
      'operationInProgress': 'Der Vorgang läuft',
      'startProcess': 'Prozess starten',
      'multiReDownloadHint': 'Sie werden alle ausgewählten Galerien erneut herunterladen.',
      'multiChangeGroupHint': 'Sie werden die Gruppe aller ausgewählten Galerien ändern.',
      'multiDeleteHint': 'Sie werden alle ausgewählten Galerien löschen.',
      'blankImageHint': 'Download des Bilds hat ein leeres Ergebnis zurückgegeben, erneutes Parsen wird versucht.',
      'peakHoursHint': 'Das Herunterladen von Originaldateien in Stoßzeiten erfordert GP, aber Sie haben nicht genug, der Download wurde pausiert.',
      'oldGalleryHint': 'Das Herunterladen von Originaldateien dieser Galerie erfordert GP, aber Sie haben nicht genug.',
      'exceedLimitHint': 'Sie haben das Bildlimit erreicht und haben nicht genug GP, um ein Download-Kontingent zu kaufen.',
      'deleteUpdatingDependentHint': 'Eine andere Galerie ist von dieser Galerie abhängig. Es wird empfohlen, sie nach Abschluss des Updates zu löschen.',
      'migrateToDownload': 'Zu 「Herunterladen」 migrieren',
      'refresh': 'Aktualisieren',

      /// search
      'simpleSearch': 'Einfach',
      'regexSearch': 'Regex',

      /// search dialog
      'searchConfig': 'Suchkonfiguration',
      'addTabBar': 'Tab-Leiste hinzufügen',
      'updateTabBar': 'Tab-Leiste aktualisieren',
      'addQuickSearch': 'Hinzufügen',
      'updateQuickSearch': 'Aktualisieren',
      'filter': 'Filter',
      'tabBarName': 'Tab-Leisten-Name',
      'quickSearchName': 'Name',
      'pleaseInputValidName': 'Bitte gültigen Namen eingeben',
      'sameNameExists': 'Gleicher Name existiert bereits',
      'sameConfigExists': 'Gleiche Konfiguration existiert bereits',
      'searchType': 'Suchtyp',
      'popular': 'Beliebt',
      'ranklist': 'Rangliste',
      'ranklistBoard': 'Ranglistentafel',
      'watched': 'Beobachtet',
      'history': 'Verlauf',
      'keyword': 'Schlüsselwort',
      'orderBy': 'Sortieren nach',
      'favoritedTime': 'Zeit der Favorisierung',
      'publishedTime': 'Veröffentlichungszeit',
      'backspace2DeleteTag': 'Rücktaste zum Tag löschen',
      'searchGalleryName': 'Nach Name suchen',
      'searchGalleryTags': 'Nach Tags suchen',
      'searchGalleryDescription': 'Nach Beschreibung suchen',
      'onlySearchExpungedGalleries': 'Nur gelöschte Galerien suchen',
      'onlyShowGalleriesWithTorrents': 'Nur Galerien mit Torrents anzeigen',
      'searchLowPowerTags': 'Schwach bewertete Tags suchen',
      'searchDownVotedTags': 'Negativ bewertete Tags suchen',
      'pageAtLeast': '页数至少', // Not provided in prompt, but keeping consistency. Wait, prompt has pageAtLeast=Mindestseiten
      'pageAtLeast': 'Mindestseiten',
      'pageAtMost': 'Maximalseiten',
      'pagesBetween': 'Seitenbereich',
      'pageRangeSelectHint': 'min <= 1000, max >= 10\nmin/max <= 0.8, max-min >= 20',
      'to': 'bis',
      'minimumRating': 'Mindestbewertung',
      'disableFilterForLanguage': 'Sprachfilter deaktivieren',
      'disableFilterForUploader': 'Hochlader-Filter deaktivieren',
      'disableFilterForTags': 'Tag-Filter deaktivieren',
      'searchName': 'Nach Name suchen',
      'searchTags': 'Nach Tags suchen',
      'searchNote': 'Nach Notiz suchen',
      'allTime': 'Alle Zeiten',
      'year': 'Jahr',
      'month': 'Monat',
      'day': 'Tag',
      'favoriteHint': 'Qualifikatoren: Tag/Titel/Kommentar/Favoritennotiz',

      /// popular
      'getPopularListFailed': 'Beliebte Liste konnte nicht geladen werden',

      /// ranklist
      'getRanklistFailed': 'Rangliste konnte nicht geladen werden',
      'getSomeOfGallerysFailed': 'Einige Galerien konnten nicht geladen werden',

      /// history
      'getHistoryGallerysFailed': 'Einige Verlaufsgalerien konnten nicht geladen werden',

      /// search page
      'search': 'Suchen',
      'searchFailed': 'Suche fehlgeschlagen',
      'fileSearchFailed': 'Dateisuche fehlgeschlagen',
      'tab': 'Tab',
      'openGallery': 'Galerie öffnen',
      'tapChip2Delete': 'Chip antippen zum Löschen\nSchaltfläche lang drücken zum Alle löschen',
      'accurateCountTemplate': '%s Ergebnisse',
      'hundredsOfCountTemplate': 'Hunderte von Ergebnissen',
      'thousandsOfCountTemplate': 'Tausende von Ergebnissen',

      /// about
      'author': 'Autor',
      'Q&A': 'F&A',
      'telegramHint': 'Sie können Fragen zuerst auf github stellen',

      /// download setting
      'downloadPath': 'Download-Pfad',
      'changeDownloadPathHint': 'Lang drücken zum Ändern (keine SD-Karte oder Systempfade). Kopiert heruntergeladene Galerien automatisch, behält alte Dateien. Bei Fehler zurücksetzen.',
      'resetDownloadPath': 'Download-Pfad zurücksetzen',
      'extraGalleryScanPath': 'Zusätzlicher Galerie-Scan-Pfad',
      'extraGalleryScanPathHint': 'Zum Scannen und Laden lokaler Galerien',
      'singleImageSavePath': 'Einzelbild-Speicherpfad',
      'downloadOriginalImage': 'Originalbild',
      'downloadOriginalImageByDefault': 'Standardmäßig Originalbild auswählen',
      'originalImage': 'Original',
      'resampleImage': 'Neu abtasten',
      'defaultGalleryGroup': 'Standard-Galeriegruppe',
      'defaultArchiveGroup': 'Standard-Archivgruppe',
      'never': 'Nie',
      'manual': 'Manuell',
      'always': 'Immer',
      'longPress2Reset': 'Lang drücken zum Zurücksetzen',
      'needPermissionToChangeDownloadPath': 'Berechtigung erforderlich zum Ändern des Pfads',
      'invalidPath': 'Ungültiger Pfad. Bitte SD-Karte, System- oder Root-Pfade vermeiden.',
      'downloadTaskConcurrency': 'Download-Parallelität',
      'needRestart': 'Neustart erforderlich',
      'speedLimit': 'Geschwindigkeitsbegrenzung',
      'speedLimitHint': 'Nicht zu schnell',
      'per': 'Pro',
      'images': 'Bilder',
      'downloadTimeout': 'Download-Timeout',
      'downloadAllGallerysOfSamePriority': 'Alle Galerien gleicher Priorität herunterladen',
      'downloadAllGallerysOfSamePriorityHint': 'Standardmäßig nur 1 Galerie aus der Gruppe mit höchster Priorität gleichzeitig',
      'alwaysUseDefaultGroup': 'Immer Standard-Gruppe verwenden',
      'enableStoreMetadataForRestore': 'Metadaten für Wiederherstellung speichern aktivieren',
      'enableStoreMetadataForRestoreHint': 'Deaktivieren verhindert die Wiederherstellung von Download-Aufgaben',
      'archiveDownloadIsolateCount': 'Archiv-Download-Thread-Anzahl',
      'archiveDownloadIsolateCountHint': 'Die Summe der Threads aller Aufgaben muss unter 10 liegen, sonst schlägt der Download fehl',
      'manageArchiveDownloadConcurrency': 'Archiv-Download-Parallelität verwalten',
      'manageArchiveDownloadConcurrencyHint': 'Archiv wartet, bis genug Threads zum Herunterladen vorhanden sind',
      'deleteArchiveFileAfterDownload': 'Archiv-.zip-Datei nach dem Download löschen',
      'restoreDownloadTasks': 'Download-Aufgaben wiederherstellen',
      'restoreDownloadTasksHint': 'Aufgaben aus Metadaten wiederherstellen',
      'restoreDownloadTasksSuccess': 'Download-Aufgaben erfolgreich wiederhergestellt',
      'restoredCount': 'Wiederhergestellte Aufgaben',
      'restoredGalleryCount': 'Wiederhergestellte Galerien',
      'restoredArchiveCount': 'Wiederhergestellte Archive',
      'restoreTasksAutomatically': 'Aufgaben automatisch wiederherstellen',
      'restoreTasksAutomaticallyHint': 'Aufgaben beim App-Start automatisch wiederherstellen',
      'brokenDownloadPathHint': 'Ihr Download-Pfad scheint beschädigt zu sein, die Download-Funktion könnte nicht funktionieren',
      'brokenExtraScanPathHint': 'Ihr Standard-Lokale-Galerie-Pfad scheint beschädigt zu sein, lokale Galerien werden möglicherweise nicht erkannt',
      'useJH2UpdateGallery': 'JH-Server zum Beschleunigen von Galerie-Updates verwenden',

      /// archive bot
      'archiveBotSettings': 'Archive-Bot-Einstellungen',
      'archiveBotSettingsHint': 'Archive-Bot verwenden, um Archiv-Links kostenlos zu erhalten',
      'apiSetting': 'API-Einstellungen',
      'apiAddress': 'Adresse',
      'apiKey': 'Schlüssel',
      'apiKeyHint': 'Geben Sie den Schlüssel ein, den Sie vom Telegram-Bot erhalten haben',
      'dailyCheckin': 'Tägliches Einloggen',
      'currentBalance': 'Aktuelles GP-Guthaben',
      'checkBalanceFailed': 'GP-Guthaben konnte nicht abgerufen werden',
      'checkInFailed': 'Einloggen fehlgeschlagen',
      'checkInSuccess': 'Einloggen erfolgreich',
      'checkInSuccessHint': 'Erhaltene GP: %s, aktuell gesamt GP: %s.',
      'pauseDownloadByInvalidArchiveBotKey': 'Archive-Bot-Einstellungen ungültig, Download pausiert',
      'chooseArchiveParseSource': 'Parse-Quelle ändern',
      'official': 'Offiziell',
      'archiveBot': 'Archive Bot',
      'changeParseSource2Official': 'Parse-Quelle auf offiziell ändern',
      'changeParseSource2Bot': 'Parse-Quelle auf Archive Bot ändern',
      'invalidParam': 'Ungültiger Parameter',
      'invalidApiKey': 'Ungültiger API-Schlüssel',
      'banned': 'Sie wurden gebannt',
      'fetchGalleryInfoFailed': 'Galerieinfos konnten nicht abgerufen werden',
      'insufficientGP': 'Unzureichende GP',
      'parseFailed': 'Parsen fehlgeschlagen',
      'checkedIn': 'Heute bereits eingeloggt',
      'serverError': 'Interner Archive-Bot-Fehler',
      'useProxyServer': 'JHenTai-Proxy-Server verwenden',
      'useProxyServerHint': 'Anfragen über JHenTai-Server weiterleiten',

      /// password
      'setPasswordHint': 'Bitte Passwort eingeben',
      'confirmPasswordHint': 'Bitte Passwort erneut eingeben',
      'passwordNotMatchHint': 'Passwörter stimmen nicht überein, bitte erneut versuchen',

      /// cloud
      'serverCondition': 'Server-Zustand',
      'configSync': 'Konfigurationssynchronisierung',
      'configSyncHint': 'Konfigurationsdaten in der Cloud speichern (bis zu 50 Einträge)',
      'upload2cloud': 'In die Cloud hochladen',
      'upload2cloudHint': 'Aktuelle lokale Konfiguration hochladen',
      'tap2upload': 'Zum Hochladen tippen',
      'copyIdentificationCodeSuccess': 'Hochladen erfolgreich. Identifikationscode kopiert',
      'copyShareCode': 'Freigabecode kopieren',
      'import': 'Importieren',
      'save2Local': 'Lokal speichern',
      'readIndexRecord': 'Lesefortschritt',
      'quickSearch': 'Schnellsuche-Konfiguration',
      'blockRules': 'Blockierregeln',
      'searchHistory': 'Suchverlauf',
      'galleryHistory': 'Galerie-Verlauf',

      /// block rules
      'configureBlockRuleFailed': 'Konfiguration der Blockierregel fehlgeschlagen',
      'removeBlockRuleFailed': 'Löschen der Blockierregel fehlgeschlagen',
      'inputNumberHint': 'Bitte eine korrekte Zahl eingeben',
      'inputRegexHint': 'Bitte einen korrekten regulären Ausdruck eingeben',
      'useBuiltInBlockedUsers': 'Integrierte Benutzersperrliste aktivieren',
      'useBuiltInBlockedUsersHint': 'Galerie-Kommentare von Benutzern auf der Sperrliste herausfiltern',
      'blockingRules': 'Blockierregeln',
      'blockingRulesHint': 'Zusätzliche Blockierregeln für Galerien und Kommentare',
      'blockingTarget': 'Blockierziel',
      'blockingAttribute': 'Blockier-Attribut',
      'blockingPattern': 'Blockiermuster',
      'blockingExpression': 'Blockier-Ausdruck',
      'contain': 'Enthält',
      'notContain': 'Enthält nicht',
      'regex': 'Regex',
      'comment': 'Kommentar',
      'tag': 'Tag',
      'userId': 'Benutzer-ID',
      'content': 'Inhalt',
      'incompleteInformation': 'Unvollständige Informationen',
      'noBlockingRuleHint': 'Mindestens 1 Regel hinzufügen',
      'notSameBlockingRuleTargetHint': 'Alle Unterregeln müssen dasselbe Blockierziel haben',
      'blockingRuleHelp': '''
Blockierziel: Galerien auf der Listenseite oder Kommentare auf der Detailseite filtern. Alle Unterregeln unter derselben Regel müssen dasselbe Blockierziel haben.
Blockier-Attribut: Geben Sie das Attribut des Ziels an, auf dem die Regel basiert.
Blockiermuster: Verwenden Sie reguläre Ausdrücke für komplexe Szenarien.
Blockier-Ausdruck: Einfache Zeichenfolgen oder reguläre Ausdrücke.

Hinweis1: Verschiedene Regeln haben eine ODER-(||)-Beziehung, während alle Unterregeln unter derselben Regel eine UND-(&&)-Beziehung haben.
Hinweis2: Beim Blockieren von Tags überprüft die Regel jedes Tag in der Galerie; der Ausdruck sollte für ein einzelnes Tag geschrieben werden.
Hinweis3: Beim Blockieren von Tags müssen Sie das vollständige Tag mit Namespace angeben, wenn Sie die '='-Regel verwenden.
Hinweis4: Sie müssen ein Galerie-Layout verwenden, das alle Tags auf E-Hentai anzeigen kann, wie „Erweitert", sonst werden einige Galerien möglicherweise nicht korrekt gefiltert.

Beispiel 1: Galerien mit dem Tag „yaoi" aber ohne „tomgirl" blockieren————Galerie-Tag Enthält male:yaoi && Galerie-Tag Enthält nicht male:tomgirl
Beispiel 2: Kommentare mit einem Score <= 10 blockieren————Kommentar-Score <= 10
''',

      /// quick search
      'quickSearch': 'Schnellsuche',

      /// dashboard
      'seeAll': 'Alle',
      'newest': 'Neueste',

      /// torrent
      'outdated': 'Veraltet',

      /// tag dialog
      'warningImageHint': 'R18G-Bild, zum Anzeigen tippen',

      /// tagSet
      'chooseTagSet': 'Tag-Set wählen',

      /// tag namespace
      'language': 'Sprache',
      'artist': 'Künstler',
      'character': 'Charakter',
      'female': 'Weiblich',
      'male': 'Männlich',
      'parody': 'Parodie',
      'group': 'Gruppe',
      'mixed': 'Gemischt',
      'Coser': 'Coser',
      'cosplayer': 'Cosplayer',
      'reclass': 'Umklassifizieren',
      'temp': 'Temporär',
      'other': 'Sonstiges',
    };
  }
}
