import 'dart:core';

class es_ES {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': 'Sí',
      'no': 'No',
      'cancel': 'Cancelar',
      'OK': 'OK',
      'reset': 'Restablecer',
      'success': 'Éxito',
      'error': 'Error',
      'failed': 'Fallido',
      'reload': 'Recargar',
      'noMoreData': 'No hay más datos',
      'noData': 'Sin datos',
      'operationFailed': 'Operación fallida',
      'needLoginToOperate': 'Se requiere iniciar sesión',
      'hasCopiedToClipboard': 'Copiado al portapapeles',
      'networkError': 'Error de red, toca para recargar',
      'systemError': 'Error del sistema',
      'invalid': 'Inválido',
      'internalError': 'Error interno',
      'you': 'Usted',
      'retryHint': 'Por favor, reintenta después de actualizar',
      'stop': 'Detener',
      'attention': 'Atención',
      'jump': 'Ir a',
      'deleteAll': 'Eliminar todo',
      'connectionTimeoutHint': 'Tiempo de espera de conexión de red',
      'receiveDataTimeoutHint': 'Tiempo de espera al recibir datos',
      'archiveError': 'Error al descargar el archivo',
      'edit': 'Editar',

      'home': 'Inicio',
      'gallery': 'Galería',
      'setting': 'Ajustes',

      /// schedule
      'dawnOfaNewDay': '¡Es el amanecer de un nuevo día!',
      'encounterMonster': '¡Has encontrado un monstruo!',
      'encounterMonsterHint': 'Haz clic para luchar en HentaiVerse.',

      /// unlock page
      'localizedReason': 'Por favor, autentícate para continuar',
      'tap2Auth': 'Toca para autenticarte',
      'passwordErrorHint': 'Contraseña incorrecta, inténtalo de nuevo',

      /// start page
      'TapAgainToExit': 'Toca de nuevo para salir',

      /// update dialog
      'availableUpdate': '¡Actualización disponible!',
      'LatestVersion': 'Última versión',
      'CurrentVersion': 'Versión actual',
      'check': 'Verificar',
      'dismiss': 'Descartar',

      /// login page
      'login': 'Iniciar sesión',
      'notLoggedIn': 'Iniciar sesión',
      'logout': 'Cerrar sesión',
      'passwordLogin': 'Inicio con contraseña',
      'cookieLogin': 'Inicio con cookie',
      'useWebview': 'Usar Webview',
      'skipCookieVerification': 'Omitir verificación',
      'youHaveLoggedInAs': 'Hola:   ',
      'cookieIsBlack': 'Cookie en lista negra',
      'cookieFormatError': 'Error de formato de cookie',
      'invalidCookie': 'Error de inicio o cookie inválida',
      'loginFail': 'Error de inicio de sesión',
      'userName': 'Nombre de usuario',
      'EHUser': 'Usuario EH',
      'password': 'Contraseña',
      'needCaptcha': 'Se requiere captcha, inicia sesión vía cookie o web.',
      'userNameOrPasswordMismatch': 'Nombre de usuario o contraseña incorrectos',
      'copyCookies': 'Copiar cookies',
      'tap2Copy': 'Toca para copiar',
      'webLoginIsDisabled': 'El inicio web está desactivado en escritorio',
      'loginSuccess': 'Inicio de sesión exitoso',
      'userNameFormHint': 'Usa cookie en caso de Sad Panda',
      'tap2Login': 'Iniciar sesión',
      'parse': 'Analizar',
      'igneousHint': 'igneous (EX requerido)',
      'refreshIgneousFailed': 'Error al actualizar Igneous',

      /// request
      'sadPanda': 'Sad Panda (sin datos). Ver: https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',

      /// gallery card
      'filtered': 'Filtrado',

      /// gallery page
      'getGallerysFailed': 'Error al obtener galerías',
      'refreshGalleryFailed': 'Error al actualizar la galería',
      'tabBarSetting': 'Configuración de barra de pestañas',
      'jumpPageTo': 'Ir a la página',
      'range': 'Rango',
      'current': 'Actual',
      'galleryUrlDetected': 'URL de galería detectada en el portapapeles',
      'galleryUrlDetectedHint': 'Toca para ir a la página de detalles',

      /// details page
      'read': 'Leer',
      'download': 'Descargar',
      'favorite': 'Favorito',
      'rating': 'Calificación',
      'torrent': 'Torrent',
      'archive': 'Archivo',
      'statistic': 'Estadísticas',
      'similar': 'Similar',
      'downloading': 'Descargando',
      'resume': 'Reanudar',
      'pause': 'Pausar',
      'finished': 'Terminado',
      'update': 'Actualizar',
      'submit': 'Enviar',
      'chooseFavorite': 'Elegir favorito',
      'asYourDefault': 'Como predeterminado',
      'Note': 'Nota',
      'addNoteHint': 'Por favor elige un espacio antes de añadir una nota',
      'uploader': 'Subidor',
      'allComments': 'Todos los comentarios',
      'noComments': 'Sin comentarios',
      'lastEditedOn': 'Última edición el',
      'getGalleryDetailFailed': 'Error al obtener los detalles de la galería',
      'cloudflare403': 'Cloudflare ha restringido tus solicitudes de red. Intenta cambiar de red o usa otro método de inicio de sesión.',
      'invisible2User': 'Esta galería es invisible para ti',
      'invisibleHints': 'Esta galería ha sido eliminada o no está disponible.',
      'copyRightHints': 'Esta galería no está disponible debido a una reclamación de derechos de autor:',
      'refreshGalleryDetailsFailed': 'Error al actualizar los detalles',
      'failToGetThumbnails': 'Error al obtener miniaturas',
      'favoriteGallerySuccess': 'Galería añadida a favoritos',
      'favoriteGalleryFailed': 'Error al añadir a favoritos',
      'removeFavoriteSuccess': 'Favorito eliminado con éxito',
      'removeFavoriteFailed': 'Error al eliminar el favorito',
      'getGalleryFavoriteInfoFailed': 'Error al obtener la información de favoritos',
      'favoriteNoteSlotFullHint': 'El espacio de notas de favoritos está lleno, elimina algunas primero',
      'ratingSuccess': 'Calificación enviada',
      'ratingFailed': 'Error al calificar',
      'voteTagFailed': 'Error al votar la etiqueta',
      'beginToDownload': 'Descarga iniciada',
      'resumeDownload': 'Reanudar descarga',
      'pauseDownload': 'Pausar descarga',
      'addNewTagSetSuccess': 'Nuevo conjunto de etiquetas añadido',
      'addNewWatchedTagSetSuccess': 'Nuevo conjunto de etiquetas vigiladas añadido',
      'addNewHiddenTagSetSuccess': 'Nuevo conjunto de etiquetas ocultas añadido',
      'addNewTagSetSuccessHint': 'Puedes ver tus etiquetas en Ajustes->EH->Mis etiquetas',
      'addNewTagSetFailed': 'Error al añadir el conjunto de etiquetas',
      'VisitorStatistics': 'Estadísticas de visitantes',
      'invisible2UserWithoutDonation': 'Las estadísticas de esta galería están ocultas para no donantes',
      'getGalleryStatisticsFailed': 'Error al obtener estadísticas',
      'totalVisits': 'Visitas totales',
      'visits': 'Visitas',
      'imageAccesses': 'Accesos a imágenes',
      'period': 'Período',
      'ranking': 'Clasificación',
      'score': 'Puntuación',
      'NotOnTheList': 'Fuera de la lista',
      'getGalleryArchiveFailed': 'Error al obtener el archivo',
      'parseGalleryArchiveFailed': 'Error de análisis. Comprueba que la configuración del archivador en e-hentai sea [Selección manual, inicio manual (predeterminado)]',
      'original': 'Original',
      'resample': 'Remuestrear',
      'beginToDownloadArchive': 'Descarga de archivo iniciada',
      'beginToDownloadArchiveHint': 'Puedes ver el progreso en Descargar -> Archivo',
      'updateGalleryError': 'Error al actualizar la galería',
      'thisGalleryHasANewVersion': 'Esta galería tiene una nueva versión',
      'hasUpdated': 'Actualizado',
      'unpackingArchiveError': 'Error al descomprimir el archivo',
      'failedToDealWith': 'Error al procesar',
      'hasDownloaded': 'Descargado',
      '410Hints': 'Los bytes de descarga de este archivo han superado el límite. Necesitas desbloquear el archivo de nuevo.',
      '429Hints': '¡Demasiadas solicitudes de descarga! Reduce la concurrencia de descarga de archivos.',
      'getUnpackedImagesFailedMsg': 'JHenTai no puede cargar las imágenes de este archivo. Comprueba tus archivos locales.',
      'getGalleryTorrentsFailed': 'Error al obtener torrents',
      'chooseArchive': 'Elegir archivo',
      'tagSetExceedLimit': 'No se pueden añadir más etiquetas, límite alcanzado',
      'useTranslation': 'Usar traducción',
      'addTagSuccess': 'Etiqueta añadida con éxito',
      'addTagFailed': 'Error al añadir la etiqueta',
      'parentGallery': 'Galería principal',
      'blockUploaderLocally': 'Bloquear usuario localmente',
      'block': 'Bloquear',

      /// detail dialog
      'galleryUrl': 'URL de la galería',
      'title': 'Título',
      'japaneseTitle': 'Título japonés',
      'category': 'Categoría',
      'publishTime': 'Hora de publicación',
      'pageCount': 'Número de páginas',
      'favoriteCount': 'Número de favoritos',
      'ratingCount': 'Número de calificaciones',

      /// comment page
      'newComment': 'Nuevo comentario',
      'updateComment': 'Actualizar comentario',
      'commentTooShort': 'Comentario demasiado corto',
      'sendCommentFailed': 'Error al enviar el comentario',
      'voteCommentFailed': 'Error al votar el comentario',
      'voteCommentFailedHint': 'Intenta primero tirar hacia abajo para actualizar la página de detalles',
      'unknownUser': 'Usuario desconocido',
      'atLeast3Characters': 'Se requieren al menos 3 caracteres',
      'noJHenTaiHints': 'Por favor, no menciones JHenTai',
      'blockUser': 'Bloquear usuario',

      /// EHImage
      'reloadImage': 'Recargar imagen',

      /// read page
      'parsingPage': 'Analizando página',
      'parsingURL': 'Analizando URL',
      'parsePageFailed': 'Error al analizar la página, toca para reintentar',
      'parseURLFailed': 'Error al analizar la URL, toca para reintentar',
      'loading': 'Cargando',
      'paused': 'En pausa',
      'exceedImageLimits': 'Límite de imágenes superado',
      'ehServerError': 'Se ha producido un error del servidor EH. Inténtalo más tarde.',
      'unsupportedImagePageStyle': 'JHenTai no es compatible con el visor multipágina (MPV). Cambia al estilo predeterminado en e-hentai.org.',
      'toNext': 'Siguiente',
      'toPrev': 'Anterior',
      'back': 'Volver',
      'toggleMenu': 'Alternar menú',
      'share': 'Compartir',
      'save': 'Guardar imagen',

      /// setting page
      'account': 'Cuenta',
      'EH': 'EH',
      'style': 'Estilo',
      'preference': 'Preferencias',
      'network': 'Red',
      'performance': 'Rendimiento',
      'mouseWheel': 'Rueda del ratón',
      'advanced': 'Avanzado',
      'cloud': 'Nube',
      'security': 'Seguridad',
      'about': 'Acerca de',
      'accountSetting': 'Ajustes de cuenta',
      'styleSetting': 'Ajustes de estilo',
      'advancedSetting': 'Ajustes avanzados',
      'securitySetting': 'Ajustes de seguridad',
      'ehSetting': 'Ajustes del sitio EH',
      'readSetting': 'Ajustes de lectura',
      'preferenceSetting': 'Ajustes de preferencias',
      'downloadSetting': 'Ajustes de descarga',
      'networkSetting': 'Ajustes de red',
      'performanceSetting': 'Ajustes de rendimiento',
      'mouseWheelSetting': 'Ajustes de rueda del ratón',

      /// eh setting page
      'site': 'Sitio',
      'redirect2Eh': 'Redirigir a EH si está disponible',
      'redirect2EhHint': 'Intenta cargar primero la página de detalles del sitio EH para mejor rendimiento de red',
      'redirectAllGallery': 'Redirigir todas las galerías a EH',
      'imDonorHint': 'Si eres donante, activa esto para acceder a galerías en el sitio EX',
      'profileSetting': 'Ajustes de perfil',
      'chooseProfileHint': 'Elige el perfil utilizado en JHenTai',
      'siteSetting': 'Ajustes del sitio',
      'siteSettingHint': 'Editar ajustes del sitio en e-hentai',
      'showCookie': 'Cookie',
      'redirect2EH': 'Redirigir al sitio EH si está disponible',
      'redirect2Hints': 'Intentará analizar primero el sitio EH',
      'pleaseLogInToOperate': 'Por favor, inicia sesión para operar',
      'imageLimits': 'Cuota de imágenes',
      'resetCost': 'Mantén pulsado para restablecer, coste',
      'assets': 'Activos',
      'isNotDonator': 'Los no donantes no pueden ver la cuota',
      'fetchImageQuotaFailed': 'Error al obtener la cuota de imágenes',

      /// tag setting page
      'myTags': 'Mis etiquetas',
      'myTagsHint': 'Gestionar etiquetas vigiladas/ocultas en línea',
      'localTags': 'Etiquetas locales',
      'localTagsHint': 'Etiquetas de filtro adicionales',
      'localTagsHint2': 'Las galerías con estas etiquetas se ocultarán',
      'addLocalTags': 'Añadir etiquetas',
      'hidden': 'Oculto',
      'nope': 'No',
      'getTagSetFailed': 'Error al obtener el conjunto de etiquetas',
      'updateTagSetFailed': 'Error al actualizar el conjunto de etiquetas',
      'updateTagFailed': 'Error al actualizar la etiqueta',
      'deleteTagSuccess': 'Etiqueta eliminada con éxito',
      'deleteTagFailed': 'Error al eliminar la etiqueta',
      'addLocalTagHint': 'Busca para añadir una nueva etiqueta',

      /// Profile Setting page
      'selectedProfile': 'Perfil seleccionado',
      'resetIfSwitchSite': 'Se restablecerá al cambiar de sitio',

      /// host mapping dialog
      'addHostMapping': 'Añadir mapeo de host',

      /// Layout
      'layoutMode': 'Modo de diseño',
      'mobileLayoutV2Name': 'Móvil',
      'mobileLayoutV2Desc': 'Una columna',
      'mobileLayoutName': 'Móvil (antiguo)',
      'mobileLayoutDesc': 'Ya no se mantiene',
      'tabletLayoutV2Name': 'Tableta',
      'tabletLayoutV2Desc': 'Dos columnas',
      'tabletLayoutName': 'Tableta (antiguo)',
      'tabletLayoutDesc': 'Ya no se mantiene',
      'desktopLayoutName': 'Escritorio',
      'desktopLayoutDesc': 'Dos columnas con barra de pestañas izquierda, soporte de teclado',

      /// style setting page
      'enableTagZHTranslation': 'Traducir nombres de etiquetas al chino',
      'version': 'Versión',
      'downloadTagTranslationHint': 'Descargando datos... Descargado:',
      'zhTagSearchOrderOptimization': 'Regla de orden de autocompletado de etiquetas chinas',
      'zhTagSearchOrderOptimizationHint': 'Ordenación inteligente por defecto, ordenar por frecuencia si está activado',
      'themeMode': 'Modo de tema',
      'dark': 'Oscuro',
      'light': 'Claro',
      'followSystem': 'Seguir el sistema',
      'themeColor': 'Color del tema',
      'listStyle': 'Estilo de lista de galerías (Global)',
      'flat': 'Plano',
      'flatWithoutTags': 'Plano (sin etiquetas)',
      'listWithoutTags': 'Tarjeta (sin etiquetas)',
      'listWithTags': 'Tarjeta',
      'waterfallFlowSmall': 'Cascada (Pequeña)',
      'waterfallFlowMedium': 'Cascada (Mediana)',
      'waterfallFlowBig': 'Cascada (Grande)',
      'crossAxisCountInWaterFallFlow': 'Columnas de cascada',
      'pageListStyle': 'Estilo de lista (Página)',
      'crossAxisCountInGridDownloadPageForGroup': 'Columnas de cuadrícula de descarga (Grupo)',
      'crossAxisCountInGridDownloadPageForGallery': 'Columnas de cuadrícula de descarga (Galería)',
      'crossAxisCountInDetailPage': 'Columnas de miniaturas (Detalle)',
      'global': 'Global',
      'auto': 'Automático',
      'moveCover2RightSide': 'Mover portada a la derecha',
      'coverStyle': 'Estilo de portada',
      'cover': 'Portada',
      'adaptive': 'Adaptativo',
      'simpleDashboardMode': 'Página de inicio simplificada',
      'simpleDashboardModeHint': 'Ocultar lista de clasificación y populares',
      'hideBottomBar': 'Ocultar barra inferior',
      'hideScroll2TopButton': 'Ocultar botón de scroll arriba',
      'whenScrollUp': 'Al desplazarse hacia arriba',
      'whenScrollDown': 'Al desplazarse hacia abajo',
      'preloadGalleryCover': 'Precargar portadas de galerías',
      'preloadGalleryCoverHint': 'Precargar portadas de galerías aún no mostradas',
      'enableSwipeBackGesture': 'Activar gesto de deslizar para volver',
      'enableLeftMenuDrawerGesture': 'Activar gesto del cajón de menú izquierdo',
      'enableQuickSearchDrawerGesture': 'Activar gesto del cajón de búsqueda rápida',
      'drawerGestureEdgeWidth': 'Ancho del borde del gesto del cajón',
      'alwaysShowScroll2TopButton': 'Mostrar siempre el botón de scroll arriba',
      'enableDefaultFavorite': 'Activar favorito predeterminado',
      'enableDefaultFavoriteHint': 'Mantén pulsado para volver a seleccionar',
      'enableDefaultTagSet': 'Activar conjunto de etiquetas predeterminado',
      'enableDefaultTagSetHint': 'Mantén pulsado para volver a seleccionar',
      'disableDefaultTagSetHint': 'Seleccionar manualmente',
      'launchInFullScreen': 'Iniciar en pantalla completa',
      'launchInFullScreenHint': 'Cambiar manualmente con F11',
      'disableDefaultFavoriteHint': 'Seleccionar manualmente',
      'searchBehaviour': 'Comportamiento de búsqueda',
      'inheritAll': 'Heredar todo',
      'inheritAllHint': 'Usar las últimas opciones de búsqueda para la próxima búsqueda',
      'inheritPartially': 'Heredar parcialmente',
      'inheritPartiallyHint': 'Usar las últimas opciones (excepto idioma y categoría)',
      'none': 'Ninguno',
      'noneHint': 'Usar opciones de búsqueda predeterminadas',
      'showAllGalleryTitles': 'Mostrar todos los títulos de galerías',
      'showAllGalleryTitlesHint': 'Mostrar títulos originales y japoneses si están disponibles',
      'showGalleryTagVoteStatus': 'Mostrar estado de votación de etiquetas',
      'showGalleryTagVoteStatusHint': 'Incluye confianza, escepticismo e incorrecto',
      'showComments': 'Mostrar comentarios',
      'showAllComments': 'Mostrar todos los comentarios',
      'showAllCommentsHint': 'Por defecto solo se muestran los 45 comentarios más votados y los 5 más recientes',
      'addTag': 'Añadir etiqueta',
      'addTagHint': 'Introduce nuevas etiquetas separadas por coma',

      /// theme color setting page
      'themeColorSettingHint': 'Asignar colores diferentes para tema claro y oscuro',
      'preview': 'Vista previa',
      'preset': 'Predefinido',
      'custom': 'Personalizado',

      /// performance setting page
      'maxGalleryNum4Animation': 'Nº máx. de galerías para animación de lista',
      'maxGalleryNum4AnimationHint': 'Desactivar animación para grupos con más galerías que este valor (estilo lista)',

      /// mouse wheel setting page
      'wheelScrollSpeed': 'Velocidad de desplazamiento de la rueda',
      'ineffectiveInGalleryPage': 'Actualmente no efectivo en la página de galerías.',

      /// advanced setting page
      'enableDomainFronting': 'Activar fronting de dominio',
      'bypassSNIBlocking': 'Omitir bloqueo SNI',
      'hostMapping': 'Mapeo de host',
      'hostMappingHint': 'Usado para el fronting de dominio',
      'proxyAddress': 'Dirección del proxy',
      'proxyAddressHint': 'Configura correctamente si usas un servidor proxy',
      'saveSuccess': 'Guardado con éxito',
      'saveFailed': 'Error al guardar',
      'updateSuccess': 'Actualización exitosa',
      'connectTimeout': 'Tiempo de espera de conexión',
      'receiveTimeout': 'Tiempo de espera de recepción',
      'pageCacheMaxAge': 'Edad máxima de caché de página',
      'pageCacheMaxAgeHint': 'Puedes actualizar la página para renovar la caché',
      'cacheImageExpireDuration': 'Duración de expiración de caché de imágenes',
      'cacheImageExpireDurationHint': 'Eliminar automáticamente la caché de imágenes al iniciar la app',
      'oneMinute': '1 minuto',
      'tenMinute': '10 minutos',
      'oneHour': '1 hora',
      'oneDay': '1 día',
      'threeDay': '3 días',
      'enableLogging': 'Activar registro',
      'enableVerboseLogging': 'Activar registro detallado',
      'openLog': 'Abrir registros',
      'clearLogs': 'Borrar registros',
      'clearImagesCache': 'Borrar caché de imágenes',
      'longPress2Clear': 'Mantén pulsado para borrar',
      'checkUpdateAfterLaunchingApp': 'Comprobar actualizaciones al iniciar',
      'checkClipboard': 'Comprobar URL de galería en el portapapeles',
      'clearPageCache': 'Borrar caché de páginas',
      'clearSuccess': 'Borrado exitoso',
      'superResolution': 'Superresolución de imagen',
      'stopSuperResolution': 'Detener superresolución',
      'deleteSuperResolvedImage': 'Eliminar imagen con superresolución',
      'superResolveOriginalImageHint': 'Procesar la imagen original requiere más tiempo, espacio y rendimiento. ¿Continuar?',
      'verityAppLinks4Android12': 'Verificar enlaces de app (Android 12+)',
      'verityAppLinks4Android12Hint': 'Para Android 12+, necesitas añadir manualmente el enlace a los enlaces verificados para abrir JHenTai desde apps de terceros',
      'noImageMode': 'Modo sin imagen',
      'exportData': 'Exportar datos',
      'exportDataHint': 'Exportar ajustes, reglas de bloqueo e historial',
      'selectExportItems': 'Seleccionar elementos a exportar',
      'importData': 'Importar datos',
      'importDataHint': 'La app se cerrará automáticamente tras la importación para aplicar la configuración',

      /// host mapping page
      'hostDataSource': 'No modificar por defecto.\nFuente de datos: https://dns.google/',

      /// proxy page
      'proxySetting': 'Ajustes de proxy',
      'proxyType': 'Tipo de proxy',
      'systemProxy': 'Sistema',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRECT',
      'address': 'Dirección',

      /// security setting page
      'enablePasswordAuth': 'Activar autenticación por contraseña',
      'enableBiometricAuth': 'Activar autenticación biométrica',
      'enableAuthOnResume': 'Activar autenticación al reanudar',
      'enableAuthOnResumeHints': 'Retraso de 3 segundos',
      'enableBlurBackgroundApp': 'Difuminar la página al cambiar al segundo plano',
      'hideImagesInAlbum': 'Ocultar imágenes en el álbum',
      'hideImagesInAlbumHints': 'Si has cambiado la ruta de descarga predeterminada, crea .nomedia manualmente',

      /// read setting page
      'enableImmersiveMode': 'Activar modo inmersivo',
      'keepScreenAwakeWhenReading': 'Mantener pantalla activa al leer',
      'enableCustomReadBrightness': 'Activar brillo personalizado al leer',
      'spaceBetweenImages': 'Espacio entre imágenes',
      'enableImmersiveHint': 'Ocultar barra del sistema',
      'enableImmersiveHint4Windows': 'Ocultar barra de título',
      'deviceOrientation': 'Orientación del dispositivo',
      'landscape': 'Horizontal',
      'portrait': 'Vertical',
      'readDirection': 'Dirección de lectura',
      'notchOptimization': 'Optimización de muesca',
      'notchOptimizationHint': 'Añadir relleno antes de la primera imagen para evitar la muesca y la barra de estado',
      'imageRegionWidthRatio': 'Ratio de ancho de la región de imagen',
      'gestureRegionWidthRatio': 'Ratio de ancho de la región de gesto',
      'useThirdPartyViewer': 'Usar visor personalizado',
      'thirdPartyViewerPath': 'Ruta del visor (ejecutable)',
      'showThumbnails': 'Mostrar miniaturas',
      'showScrollBar': 'Mostrar barra de desplazamiento',
      'showStatusInfo': 'Mostrar estado en la parte inferior',
      'autoModeInterval': 'Intervalo de cambio automático de página',
      'autoModeStyle': 'Estilo de modo automático',
      'scroll': 'Desplazamiento',
      'turnPage': 'Cambiar página',
      'top2bottomList': 'De arriba a abajo (Continuo)',
      'left2rightSinglePage': 'De izquierda a derecha (Página única)',
      'left2rightSinglePageFitWidth': 'De izquierda a derecha (Ajustar ancho)',
      'right2leftSinglePage': 'De derecha a izquierda (Página única)',
      'right2leftSinglePageFitWidth': 'De derecha a izquierda (Ajustar ancho)',
      'left2rightDoubleColumn': 'De izquierda a derecha (Doble columna)',
      'right2leftDoubleColumn': 'De derecha a izquierda (Doble columna)',
      'left2rightList': 'De izquierda a derecha (Continuo)',
      'right2leftList': 'De derecha a izquierda (Continuo)',
      'enablePageTurnByVolumeKeys': 'Usar teclas de volumen para cambiar página',
      'enablePageTurnAnime': 'Activar animación de cambio de página',
      'enableDoubleTapToScaleUp': 'Activar doble toque para ampliar',
      'enableTapDragToScaleUp': 'Activar toque y arrastrar para ampliar',
      'enableBottomMenu': 'Activar menú inferior',
      'reverseTurnPageDirection': 'Invertir dirección de cambio de página',
      'disableGestureWhenScrolling': 'Desactivar gesto al desplazarse',
      'disablePageTurningOnTap': 'Desactivar cambio de página al tocar',
      'turnPageMode': 'Modo de cambio de página',
      'turnPageModeHint': 'Hacia la siguiente pantalla o la siguiente imagen',
      'enableImageMaxKilobytes': 'Activar compresión de imagen',
      'imageMaxKilobytes': 'Tamaño máximo de imagen',
      'imageMaxKilobytesHint': 'Las imágenes mayores a este tamaño serán comprimidas',
      'image': 'Imagen',
      'screen': 'Pantalla',
      'preloadDistanceInOnlineMode': 'Distancia de precarga (En línea)',
      'preloadDistanceInLocalMode': 'Distancia de precarga (Local)',
      'ScreenHeight': 'Pantalla',
      'preloadPageCount': 'Páginas de precarga (En línea)',
      'preloadPageCountInLocalMode': 'Páginas de precarga (Local)',
      'continuousScroll': 'Desplazamiento continuo',
      'continuousScrollHint': 'Conectar múltiples imágenes juntas',
      'doubleColumn': 'Doble columna',
      'displayFirstPageAlone': 'Mostrar primera página sola',
      'displayFirstPageAloneGlobally': 'Mostrar primera página sola (Global)',
      'toggleFullScreen': 'Alternar pantalla completa',
      'enableAutoScaleUp': 'Activar escalado automático de imágenes largas',
      'enableAutoScaleUpHints': 'Ajustar el ancho de la imagen al ancho de la pantalla',

      /// preference setting page
      'showR18GImageDirectly': 'Mostrar imagen R18G directamente',
      'defaultTab': 'Pestaña predeterminada',
      'showUtcTime': 'Mostrar hora UTC para la galería',
      'showDawnInfo': 'Mostrar evento de nuevo amanecer',
      'showEncounterMonster': 'Mostrar evento de encuentro con monstruo de HentaiVerse',

      /// log page
      'logList': 'Lista de registros',

      /// super resolution setting page
      'downloadSuperResolutionModelHint': 'Descargar modelo desde Github',
      'modelDirectoryPath': 'Ruta del directorio del modelo',
      'upSamplingScale': 'Escala de sobremuestreo',
      'modelType': 'Elegir modelo',
      'x4plusHint': 'Ocupa más espacio, pero generalmente más rápido',
      'x4plusAnimeHint': 'Ocupa menos espacio, pero generalmente más lento',
      'enable4OnlineReading': 'Procesar automáticamente durante la lectura en línea',

      /// download page
      'local': 'Local',
      'delete': 'Eliminar',
      'deleteTask': 'Eliminar solo tarea',
      'deleteTaskAndImages': 'Eliminar tarea e imágenes',
      'reDownload': 'Volver a descargar',
      'unlocking': 'Desbloqueando',
      'unlocked': 'Desbloqueado',
      'parsingDownloadPageUrl': 'Análisis I',
      'parsedDownloadPageUrl': 'Análisis I',
      'parsingDownloadUrl': 'Análisis II',
      'parsedDownloadUrl': 'Análisis II',
      'waitingIsolate': 'Esperando',
      'downloaded': 'Descargado',
      'downloadFailed': 'Descarga fallida',
      'unpacking': 'Descomprimiendo',
      'completed': 'Completado',
      'needReUnlock': 'Se requiere volver a desbloquear',
      'reUnlock': 'Volver a desbloquear',
      'reUnlockHint': '¡Atención! Necesitas recomprar este archivo para volver a desbloquearlo.',
      'downloadHelpInfo': 'Si no puedes descargar o tienes errores como tabla no existente, desinstala y reinstala la aplicación actual.',
      'localGalleryHelpInfo': 'Carga galerías no descargadas por JHenTai. Añade configuración en Ajustes de descarga -> Ruta de escaneo adicional y actualiza.',
      'localGalleryHelpInfo4iOSAndMacOS': 'Carga galerías no descargadas por JHenTai. Coloca tus galerías en la ruta de descarga predeterminada y actualiza.',
      'deleteLocalGalleryHint': 'Eliminar tus archivos locales',
      'priority': 'Prioridad',
      'highest': 'Máxima',
      'default': 'Predeterminado',
      'newGalleryCount': 'Nuevas galerías',
      'changePriority': 'Cambiar prioridad',
      'changeGroup': 'Cambiar grupo',
      'chooseGroup': 'Elegir grupo',
      'renameGroup': 'Renombrar grupo',
      'deleteGroup': 'Eliminar grupo',
      'existingGroup': 'Grupo existente',
      'groupName': 'Nombre del grupo',
      'drag2sort': 'Arrastra para ordenar',
      'switch2GridMode': 'Cambiar a modo cuadrícula',
      'switch2ListMode': 'Cambiar a modo lista',
      'multiSelect': 'Selección múltiple',
      'multiSelectHint': 'Toca para seleccionar',
      'resumeAllTasks': 'Reanudar todas las tareas',
      'pauseAllTasks': 'Pausar todas las tareas',
      'requireDownloadComplete': 'Requiere descarga completa',
      'operationHasCompleted': 'La operación ha sido completada',
      'operationInProgress': 'La operación está en curso',
      'startProcess': 'Iniciar proceso',
      'multiReDownloadHint': 'Volverás a descargar todas las galerías seleccionadas.',
      'multiChangeGroupHint': 'Cambiarás el grupo de todas las galerías seleccionadas.',
      'multiDeleteHint': 'Eliminarás todas las galerías seleccionadas.',
      'blankImageHint': 'La descarga de la imagen devolvió un resultado vacío, intentando reanálisis.',
      'peakHoursHint': 'Descargar archivos originales en horas punta requiere GP, y no tienes suficiente, la descarga ha sido pausada.',
      'oldGalleryHint': 'Descargar archivos originales de esta galería requiere GP, y no tienes suficiente.',
      'exceedLimitHint': 'Has alcanzado el límite de imágenes y no tienes suficiente GP para comprar una cuota de descarga.',
      'deleteUpdatingDependentHint': 'Otra galería depende de esta galería. Se recomienda eliminarla después de que finalice la actualización.',
      'migrateToDownload': 'Migrar a 「Descargar」',
      'refresh': 'Actualizar',

      /// download search page
      'simpleSearch': 'Simple',
      'regexSearch': 'Regex',

      /// search dialog
      'searchConfig': 'Configuración de búsqueda',
      'addTabBar': 'Añadir barra de pestañas',
      'updateTabBar': 'Actualizar barra de pestañas',
      'addQuickSearch': 'Añadir',
      'updateQuickSearch': 'Actualizar',
      'filter': 'Filtro',
      'tabBarName': 'Nombre de barra de pestañas',
      'quickSearchName': 'Nombre',
      'pleaseInputValidName': 'Por favor, introduce un nombre válido',
      'sameNameExists': 'Ya existe este nombre',
      'sameConfigExists': 'Ya existe esta configuración',
      'searchType': 'Tipo de búsqueda',
      'popular': 'Popular',
      'ranklist': 'Clasificación',
      'ranklistBoard': 'Tablero de clasificación',
      'watched': 'Vigilado',
      'history': 'Historial',
      'keyword': 'Palabra clave',
      'orderBy': 'Ordenar por',
      'favoritedTime': 'Hora de añadir a favoritos',
      'publishedTime': 'Hora de publicación',
      'backspace2DeleteTag': 'Retroceso para eliminar etiqueta',
      'searchGalleryName': 'Buscar por nombre',
      'searchGalleryTags': 'Buscar por etiquetas',
      'searchGalleryDescription': 'Buscar por descripción',
      'onlySearchExpungedGalleries': 'Buscar solo galerías eliminadas',
      'onlyShowGalleriesWithTorrents': 'Mostrar solo galerías con torrents',
      'searchLowPowerTags': 'Buscar etiquetas de baja potencia',
      'searchDownVotedTags': 'Buscar etiquetas con votos negativos',
      'pageAtLeast': 'Páginas mínimas',
      'pageAtMost': 'Páginas máximas',
      'pagesBetween': 'Rango de páginas',
      'pageRangeSelectHint': 'min <= 1000, max >= 10\nmin/max <= 0.8, max-min >= 20',
      'to': 'a',
      'minimumRating': 'Calificación mínima',
      'disableFilterForLanguage': 'Desactivar filtro de idioma',
      'disableFilterForUploader': 'Desactivar filtro de subidor',
      'disableFilterForTags': 'Desactivar filtro de etiquetas',
      'searchName': 'Buscar por nombre',
      'searchTags': 'Buscar por etiquetas',
      'searchNote': 'Buscar por nota',
      'allTime': 'Todo el tiempo',
      'year': 'Año',
      'month': 'Mes',
      'day': 'Día',
      'favoriteHint': '''
Calificadores:
tag: Coincide con etiquetas en todo el espacio de nombres
title: Coincide con títulos originales y japoneses
comment: Coincide con comentarios
favnote: Coincide con notas de favoritos
      ''', // Note: User said "Calificadores: tag/título/comentario/nota de favorito", but I'll stick to formatting or use the provided multiline if possible. Wait, the prompt says "favoriteHint=Calificadores: tag/título/comentario/nota de favorito".

      /// popular page
      'getPopularListFailed': 'Error al obtener la lista popular',

      /// ranklist page
      'getRanklistFailed': 'Error al obtener la clasificación',
      'getSomeOfGallerysFailed': 'Error al obtener algunas galerías',

      /// history page
      'getHistoryGallerysFailed': 'Error al obtener galerías del historial',

      /// search page
      'search': 'Buscar',
      'searchFailed': 'Búsqueda fallida',
      'fileSearchFailed': 'Búsqueda de archivo fallida',
      'tab': 'Pestaña',
      'openGallery': 'Abrir galería',
      'tapChip2Delete': 'Toca el chip para eliminar\nMantén pulsado el botón para eliminar todo',
      'accurateCountTemplate': '%s resultados',
      'hundredsOfCountTemplate': 'Cientos de resultados',
      'thousandsOfCountTemplate': 'Miles de resultados',

      /// about page
      'author': 'Autor',
      'Q&A': 'P&R',
      'telegramHint': 'Puedes hacer preguntas primero en github',

      /// download setting page
      'downloadPath': 'Ruta de descarga',
      'changeDownloadPathHint': 'Mantén pulsado para cambiar (evita tarjeta SD o rutas del sistema). Copia automáticamente las galerías descargadas, conserva los archivos antiguos. Intenta restablecer si hay error.',
      'resetDownloadPath': 'Restablecer ruta de descarga',
      'singleImageSavePath': 'Ruta de guardado de imagen única',
      'extraGalleryScanPath': 'Ruta de escaneo adicional',
      'extraGalleryScanPathHint': 'Para escanear y cargar galerías locales',
      'longPress2Reset': 'Mantén pulsado para restablecer',
      'downloadOriginalImage': 'Imagen original',
      'downloadOriginalImageByDefault': 'Seleccionar imagen original por defecto',
      'originalImage': 'Original',
      'resampleImage': 'Remuestrear',
      'defaultGalleryGroup': 'Grupo de galería predeterminado',
      'defaultArchiveGroup': 'Grupo de archivo predeterminado',
      'never': 'Nunca',
      'manual': 'Manual',
      'always': 'Siempre',
      'needPermissionToChangeDownloadPath': 'Se requiere permiso para cambiar la ruta',
      'invalidPath': 'Ruta inválida. Evita la tarjeta SD, rutas del sistema o raíz.',
      'downloadTaskConcurrency': 'Concurrencia de descarga',
      'needRestart': 'Se requiere reinicio',
      'downloadTimeout': 'Tiempo de espera de descarga',
      'speedLimit': 'Límite de velocidad',
      'speedLimitHint': 'No demasiado rápido',
      'per': 'Por',
      'images': 'Imágenes',
      'downloadAllGallerysOfSamePriority': 'Descargar todas las galerías de la misma prioridad',
      'downloadAllGallerysOfSamePriorityHint': 'Por defecto, solo 1 galería del grupo de mayor prioridad se descarga simultáneamente',
      'alwaysUseDefaultGroup': 'Usar siempre el grupo predeterminado',
      'restoreDownloadTasks': 'Restaurar tareas de descarga',
      'enableStoreMetadataForRestore': 'Activar almacenamiento de metadatos para restauración',
      'enableStoreMetadataForRestoreHint': 'Desactivar esto impide restaurar las tareas de descarga',
      'archiveDownloadIsolateCount': 'Número de hilos de descarga de archivo',
      'archiveDownloadIsolateCountHint': 'La suma de hilos de todas las tareas debe ser inferior a 10, de lo contrario la descarga fallará',
      'manageArchiveDownloadConcurrency': 'Gestionar concurrencia de descarga de archivo',
      'manageArchiveDownloadConcurrencyHint': 'El archivo esperará hasta tener suficientes hilos disponibles',
      'deleteArchiveFileAfterDownload': 'Eliminar archivo .zip tras la descarga',
      'restoreDownloadTasksHint': 'Restaurar tareas desde los metadatos',
      'restoreDownloadTasksSuccess': 'Tareas de descarga restauradas con éxito',
      'restoredCount': 'Tareas restauradas',
      'restoredGalleryCount': 'Galerías restauradas',
      'restoredArchiveCount': 'Archivos restaurados',
      'restoreTasksAutomatically': 'Restaurar tareas automáticamente',
      'restoreTasksAutomaticallyHint': 'Restaurar tareas automáticamente al iniciar la app',
      'brokenDownloadPathHint': 'Tu ruta de descarga parece dañada, la función de descarga puede no funcionar',
      'brokenExtraScanPathHint': 'Tu ruta de galería local parece dañada, las galerías locales pueden no ser reconocidas',
      'useJH2UpdateGallery': 'Usar servidor JH para acelerar actualizaciones de galerías',

      /// archive bot settings
      'archiveBotSettings': 'Ajustes de Archive Bot',
      'archiveBotSettingsHint': 'Usar Archive Bot para obtener enlaces de archivo gratis',
      'apiSetting': 'Ajustes de API',
      'apiAddress': 'Dirección',
      'apiKey': 'Clave',
      'apiKeyHint': 'Introduce la clave que obtuviste del bot de Telegram',
      'dailyCheckin': 'Registro diario',
      'currentBalance': 'Saldo actual de GP',
      'checkBalanceFailed': 'Error al obtener el saldo de GP',
      'checkInFailed': 'Error de registro',
      'checkInSuccess': 'Registro exitoso',
      'checkInSuccessHint': 'GP obtenido: %s, total actual de GP: %s.',
      'pauseDownloadByInvalidArchiveBotKey': 'Ajustes de Archive Bot inválidos, descarga pausada',
      'chooseArchiveParseSource': 'Cambiar fuente de análisis',
      'official': 'Oficial',
      'archiveBot': 'Archive Bot',
      'changeParseSource2Official': 'Cambiar fuente de análisis a oficial',
      'changeParseSource2Bot': 'Cambiar fuente de análisis a Archive Bot',
      'invalidParam': 'Parámetro inválido',
      'invalidApiKey': 'Clave de API inválida',
      'banned': 'Has sido baneado',
      'fetchGalleryInfoFailed': 'Error al obtener la información de la galería',
      'insufficientGP': 'GP insuficiente',
      'parseFailed': 'Error de análisis',
      'checkedIn': 'Ya registrado hoy',
      'serverError': 'Error interno de Archive Bot',
      'useProxyServer': 'Usar servidor proxy de JHenTai',
      'useProxyServerHint': 'Enrutar solicitudes a través del servidor JHenTai',

      /// password setting dialog
      'setPasswordHint': 'Por favor, introduce tu contraseña',
      'confirmPasswordHint': 'Por favor, introduce tu contraseña de nuevo',
      'passwordNotMatchHint': 'Las contraseñas no coinciden, inténtalo de nuevo',

      /// cloud setting page
      'serverCondition': 'Estado del servidor',
      'configSync': 'Sincronización de configuración',
      'configSyncHint': 'Almacenar tus datos de configuración en la nube (hasta 50 entradas)',
      'upload2cloud': 'Subir a la nube',
      'upload2cloudHint': 'Subir tu configuración local actual',
      'tap2upload': 'Toca para subir',
      'copyIdentificationCodeSuccess': 'Subida exitosa. Código de identificación copiado',
      'copyShareCode': 'Copiar código de compartición',
      'import': 'Importar',
      'save2Local': 'Guardar localmente',
      'readIndexRecord': 'Progreso de lectura',
      'quickSearch': 'Configuración de búsqueda rápida',
      'blockRules': 'Reglas de bloqueo',
      'searchHistory': 'Historial de búsqueda',
      'galleryHistory': 'Historial de galerías',

      /// block rule page
      'configureBlockRuleFailed': 'Error al configurar la regla de bloqueo',
      'removeBlockRuleFailed': 'Error al eliminar la regla de bloqueo',
      'inputNumberHint': 'Por favor, introduce un número correcto',
      'inputRegexHint': 'Por favor, introduce una expresión regular correcta',
      'useBuiltInBlockedUsers': 'Activar lista de usuarios bloqueados integrada',
      'useBuiltInBlockedUsersHint': 'Filtrar comentarios de usuarios en la lista de bloqueo',
      'blockingRules': 'Reglas de bloqueo',
      'blockingRulesHint': 'Reglas de bloqueo adicionales para galerías y comentarios',
      'blockingTarget': 'Objetivo de bloqueo',
      'blockingAttribute': 'Atributo de bloqueo',
      'blockingPattern': 'Patrón de bloqueo',
      'blockingExpression': 'Expresión de bloqueo',
      'contain': 'Contiene',
      'notContain': 'No contiene',
      'regex': 'Regex',
      'comment': 'Comentario',
      'tag': 'Etiqueta',
      'userId': 'ID de usuario',
      'content': 'Contenido',
      'incompleteInformation': 'Información incompleta',
      'noBlockingRuleHint': 'Añade al menos 1 regla',
      'notSameBlockingRuleTargetHint': 'Todas las subreglas deben tener el mismo objetivo de bloqueo',
      'blockingRuleHelp': '''Objetivo de bloqueo: Filtrar galerías en la página de lista o comentarios en la página de detalles. Todas las subreglas bajo la misma regla deben tener el mismo objetivo de bloqueo.
Atributo de bloqueo: Especifica el atributo del objetivo en el que se basa la regla.
Patrón de bloqueo: Usa expresiones regulares para escenarios complejos.
Expresión de bloqueo: Cadenas simples o expresiones regulares.

Nota1: Las reglas diferentes tienen una relación O (||), mientras que todas las subreglas bajo la misma regla tienen una relación Y (&&).
Nota2: Al bloquear etiquetas, la regla comprobará cada etiqueta en la galería; la expresión debe escribirse para una sola etiqueta.
Nota3: Al bloquear etiquetas, debes especificar la etiqueta completa con el espacio de nombres si usas la regla '='.
Nota4: Necesitas usar un diseño de galería que pueda mostrar todas las etiquetas en E-Hentai, como "Extendido", de lo contrario algunas galerías pueden no filtrarse correctamente.

Ejemplo 1: Bloquear galerías con la etiqueta "yaoi" pero sin la etiqueta "tomgirl"————Galería Etiqueta Contiene male:yaoi && Galería Etiqueta No contiene male:tomgirl
Ejemplo 2: Bloquear comentarios con puntuación <= 10————Puntuación del comentario <= 10''',

      /// quick search page
      'quickSearch': 'Búsqueda rápida',

      /// dashboard page
      'seeAll': 'Ver todo',
      'newest': 'Más recientes',

      /// torrent dialog
      'outdated': 'Desactualizado',

      /// tag dialog
      'warningImageHint': 'Imagen R18G, toca para ver',

      /// tagSet dialog
      'chooseTagSet': 'Elegir conjunto de etiquetas',

      /// tag namespace
      'language': 'Idioma',
      'artist': 'Artista',
      'character': 'Personaje',
      'female': 'Femenino',
      'male': 'Masculino',
      'parody': 'Parodia',
      'group': 'Grupo',
      'mixed': 'Mixto',
      'Coser': 'Coser',
      'cosplayer': 'Cosplayer',
      'reclass': 'Reclasificar',
      'temp': 'Temporal',
      'other': 'Otro',
    };
  }
}
