import 'dart:core';

class fr_FR {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': 'Oui',
      'no': 'Non',
      'cancel': 'Annuler',
      'OK': 'OK',
      'reset': 'Réinitialiser',
      'success': 'Succès',
      'error': 'Erreur',
      'failed': 'Échec',
      'reload': 'Recharger',
      'noMoreData': 'Plus de données',
      'noData': 'Aucune donnée',
      'operationFailed': 'Opération échouée',
      'needLoginToOperate': 'Connexion requise',
      'hasCopiedToClipboard': 'Copié dans le presse-papiers',
      'networkError': 'Erreur réseau, appuyez pour recharger',
      'systemError': 'Erreur système',
      'invalid': 'Invalide',
      'internalError': 'Erreur interne',
      'you': 'Vous',
      'retryHint': 'Veuillez réessayer après actualisation',
      'stop': 'Arrêter',
      'attention': 'Attention',
      'jump': 'Aller à',
      'deleteAll': 'Tout supprimer',
      'connectionTimeoutHint': 'Délai de connexion réseau dépassé',
      'receiveDataTimeoutHint': 'Délai de réception des données dépassé',
      'archiveError': 'Erreur de téléchargement de l\'archive',
      'edit': 'Modifier',

      'home': 'Accueil',
      'gallery': 'Galerie',
      'setting': 'Paramètres',

      /// unlock page
      'localizedReason': 'Veuillez vous authentifier pour continuer',
      'tap2Auth': 'Appuyez pour s\'authentifier',
      'passwordErrorHint': 'Mot de passe incorrect, veuillez réessayer',

      /// schedule
      'dawnOfaNewDay': 'C\'est l\'aube d\'un nouveau jour !',
      'encounterMonster': 'Vous avez rencontré un monstre !',
      'encounterMonsterHint': 'Cliquez pour combattre dans HentaiVerse.',

      /// start page
      'TapAgainToExit': 'Appuyez à nouveau pour quitter',

      /// update dialog
      'availableUpdate': 'Mise à jour disponible !',
      'LatestVersion': 'Dernière version',
      'CurrentVersion': 'Version actuelle',
      'check': 'Vérifier',
      'dismiss': 'Ignorer',

      /// login page
      'login': 'Connexion',
      'notLoggedIn': 'Connexion',
      'logout': 'Déconnexion',
      'passwordLogin': 'Connexion par mot de passe',
      'cookieLogin': 'Connexion par cookie',
      'useWebview': 'Utiliser Webview',
      'skipCookieVerification': 'Ignorer la vérification',
      'youHaveLoggedInAs': 'Bonjour :   ',
      'cookieIsBlack': 'Cookie en liste noire',
      'cookieFormatError': 'Erreur de format du cookie',
      'invalidCookie': 'Échec de connexion ou cookie invalide',
      'loginFail': 'Échec de connexion',
      'userName': 'Nom d\'utilisateur',
      'EHUser': 'Utilisateur EH',
      'password': 'Mot de passe',
      'needCaptcha': 'Captcha requis, veuillez vous connecter via cookie ou web.',
      'userNameOrPasswordMismatch': 'Nom d\'utilisateur ou mot de passe incorrect',
      'copyCookies': 'Copier les cookies',
      'tap2Copy': 'Appuyez pour copier',
      'webLoginIsDisabled': 'La connexion web est désactivée sur bureau',
      'loginSuccess': 'Connexion réussie',
      'userNameFormHint': 'Essayez avec un cookie en cas de Sad Panda',
      'tap2Login': 'Se connecter',
      'parse': 'Analyser',
      'igneousHint': 'igneous (EX requis)',
      'refreshIgneousFailed': 'Échec de l\'actualisation Igneous',

      /// request
      'sadPanda': 'Sad Panda (aucune donnée). Référence : https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',

      /// gallery card
      'filtered': 'Filtré',

      /// gallery page
      'getGallerysFailed': 'Échec de récupération des galeries',
      'tabBarSetting': 'Paramètres de la barre d\'onglets',
      'refreshGalleryFailed': 'Échec d\'actualisation de la galerie',
      'jumpPageTo': 'Aller à la page',
      'range': 'Plage',
      'current': 'Actuel',
      'galleryUrlDetected': 'URL de galerie détectée dans le presse-papiers',
      'galleryUrlDetectedHint': 'Appuyez pour accéder à la page de détails',

      /// details page
      'read': 'Lire',
      'download': 'Télécharger',
      'favorite': 'Favori',
      'rating': 'Note',
      'torrent': 'Torrent',
      'archive': 'Archive',
      'statistic': 'Statistiques',
      'similar': 'Similaire',
      'downloading': 'Téléchargement',
      'resume': 'Reprendre',
      'pause': 'Pause',
      'finished': 'Terminé',
      'update': 'Mettre à jour',
      'submit': 'Soumettre',
      'chooseFavorite': 'Choisir un favori',
      'asYourDefault': 'Comme favori par défaut',
      'Note': 'Note',
      'addNoteHint': 'Choisissez un emplacement avant d\'ajouter une note',
      'uploader': 'Importateur',
      'allComments': 'Tous les commentaires',
      'noComments': 'Aucun commentaire',
      'lastEditedOn': 'Dernière modification le',
      'getGalleryDetailFailed': 'Échec de récupération des détails de la galerie',
      'cloudflare403': 'Vous avez été restreint par Cloudflare. Essayez de changer de réseau ou d\'utiliser une autre méthode de connexion.',
      'invisible2User': 'Cette galerie est invisible pour vous',
      'invisibleHints': 'Cette galerie a été supprimée ou est indisponible.',
      'copyRightHints': 'Cette galerie est indisponible suite à une réclamation de droits d\'auteur :',
      'refreshGalleryDetailsFailed': 'Échec d\'actualisation des détails',
      'failToGetThumbnails': 'Échec de récupération des miniatures',
      'favoriteGallerySuccess': 'Galerie ajoutée aux favoris',
      'favoriteGalleryFailed': 'Échec de l\'ajout aux favoris',
      'removeFavoriteSuccess': 'Favori supprimé avec succès',
      'removeFavoriteFailed': 'Échec de la suppression du favori',
      'getGalleryFavoriteInfoFailed': 'Échec de récupération des infos de favori',
      'favoriteNoteSlotFullHint': 'L\'emplacement de note de favori est plein, supprimez d\'abord quelques notes',
      'ratingSuccess': 'Note enregistrée',
      'ratingFailed': 'Échec de la notation',
      'voteTagFailed': 'Échec du vote pour le tag',
      'beginToDownload': 'Début du téléchargement',
      'resumeDownload': 'Reprendre le téléchargement',
      'pauseDownload': 'Pause du téléchargement',
      'addNewTagSetSuccess': 'Nouveau jeu de tags ajouté',
      'addNewWatchedTagSetSuccess': 'Nouveau jeu de tags surveillés ajouté',
      'addNewHiddenTagSetSuccess': 'Nouveau jeu de tags masqués ajouté',
      'addNewTagSetSuccessHint': 'Vous pouvez vérifier vos tags dans Paramètres->EH->Mes tags',
      'addNewTagSetFailed': 'Échec de l\'ajout du jeu de tags',
      'VisitorStatistics': 'Statistiques des visiteurs',
      'invisible2UserWithoutDonation': 'Les statistiques de cette galerie sont masquées pour les non-donateurs',
      'getGalleryStatisticsFailed': 'Échec de récupération des statistiques',
      'totalVisits': 'Visites totales',
      'visits': 'Visites',
      'imageAccesses': 'Accès aux images',
      'period': 'Période',
      'ranking': 'Classement',
      'score': 'Score',
      'NotOnTheList': 'Hors liste',
      'getGalleryArchiveFailed': 'Échec de récupération de l\'archive',
      'parseGalleryArchiveFailed': 'Échec de l\'analyse. Vérifiez que vos paramètres d\'archivage sur e-hentai sont [Sélection manuelle, démarrage manuel (par défaut)]',
      'original': 'Original',
      'resample': 'Rééchantillonner',
      'beginToDownloadArchive': 'Début du téléchargement de l\'archive',
      'beginToDownloadArchiveHint': 'Vous pouvez consulter la progression dans Télécharger -> Archive',
      'updateGalleryError': 'Erreur de mise à jour de la galerie',
      'thisGalleryHasANewVersion': 'Cette galerie a une nouvelle version',
      'hasUpdated': 'Mis à jour',
      'unpackingArchiveError': 'Erreur lors de la décompression de l\'archive',
      'failedToDealWith': 'Échec du traitement',
      'hasDownloaded': 'Téléchargé',
      '410Hints': 'Le nombre d\'octets de téléchargement pour cette archive a dépassé la limite. Vous devez déverrouiller à nouveau l\'archive pour continuer.',
      '429Hints': 'Trop de demandes de téléchargement ! Réduisez la concurrence de téléchargement d\'archives.',
      'getUnpackedImagesFailedMsg': 'JHenTai ne peut pas charger les images de cette archive. Vérifiez vos fichiers locaux.',
      'getGalleryTorrentsFailed': 'Échec de récupération des torrents',
      'chooseArchive': 'Choisir une archive',
      'tagSetExceedLimit': 'Impossible d\'ajouter plus de tags, limite atteinte',
      'useTranslation': 'Utiliser la traduction',
      'addTagSuccess': 'Tag ajouté avec succès',
      'addTagFailed': 'Échec de l\'ajout du tag',
      'parentGallery': 'Galerie parente',
      'blockUploaderLocally': 'Bloquer l\'utilisateur localement',
      'block': 'Bloquer',

      /// detail dialog
      'galleryUrl': 'URL de la galerie',
      'title': 'Titre',
      'japaneseTitle': 'Titre japonais',
      'category': 'Catégorie',
      'publishTime': 'Date de publication',
      'pageCount': 'Nombre de pages',
      'favoriteCount': 'Nombre de favoris',
      'ratingCount': 'Nombre de notes',

      /// comment page
      'newComment': 'Nouveau commentaire',
      'updateComment': 'Modifier le commentaire',
      'commentTooShort': 'Commentaire trop court',
      'sendCommentFailed': 'Échec d\'envoi du commentaire',
      'voteCommentFailed': 'Échec du vote pour le commentaire',
      'voteCommentFailedHint': 'Essayez d\'abord de glisser vers le bas pour actualiser la page de détails',
      'unknownUser': 'Utilisateur inconnu',
      'atLeast3Characters': 'Minimum 3 caractères requis',
      'noJHenTaiHints': 'Ne mentionnez pas JHenTai',
      'blockUser': 'Bloquer l\'utilisateur',

      /// EHImage
      'reloadImage': 'Recharger l\'image',

      /// read page
      'parsingPage': 'Analyse de la page',
      'parsingURL': 'Analyse de l\'URL',
      'parsePageFailed': 'Échec d\'analyse de la page, appuyez pour réessayer',
      'parseURLFailed': 'Échec d\'analyse de l\'URL, appuyez pour réessayer',
      'loading': 'Chargement',
      'paused': 'En pause',
      'exceedImageLimits': 'Limite d\'images dépassée',
      'ehServerError': 'Une erreur de serveur EH s\'est produite. Veuillez réessayer plus tard.',
      'unsupportedImagePageStyle': 'JHenTai ne prend pas en charge le visionneuse multi-pages (MPV). Veuillez passer au style par défaut sur e-hentai.org',
      'toNext': 'Suivant',
      'toPrev': 'Précédent',
      'back': 'Retour',
      'toggleMenu': 'Basculer le menu',
      'share': 'Partager',
      'save': 'Enregistrer l\'image',

      /// setting page
      'account': 'Compte',
      'EH': 'EH',
      'style': 'Style',
      'preference': 'Préférence',
      'network': 'Réseau',
      'performance': 'Performance',
      'mouseWheel': 'Molette de souris',
      'advanced': 'Avancé',
      'cloud': 'Cloud',
      'security': 'Sécurité',
      'about': 'À propos',
      'accountSetting': 'Paramètres du compte',
      'styleSetting': 'Paramètres de style',
      'advancedSetting': 'Paramètres avancés',
      'securitySetting': 'Paramètres de sécurité',
      'ehSetting': 'Paramètres du site EH',
      'readSetting': 'Paramètres de lecture',
      'preferenceSetting': 'Paramètres de préférence',
      'downloadSetting': 'Paramètres de téléchargement',
      'networkSetting': 'Paramètres réseau',
      'performanceSetting': 'Paramètres de performance',
      'mouseWheelSetting': 'Paramètres de molette de souris',

      /// eh setting page
      'site': 'Site',
      'redirect2Eh': 'Rediriger vers EH si disponible',
      'redirect2EhHint': 'Essayez de charger d\'abord la page de détails du site EH pour de meilleures performances réseau',
      'redirectAllGallery': 'Rediriger toutes les galeries vers EH',
      'imDonorHint': 'Si vous êtes donateur, activez ceci pour accéder aux galeries sur le site EX',
      'profileSetting': 'Paramètres de profil',
      'chooseProfileHint': 'Choisissez le profil utilisé dans JHenTai',
      'siteSetting': 'Paramètres du site',
      'siteSettingHint': 'Modifier les paramètres du site sur e-hentai',
      'showCookie': 'Cookie',
      'redirect2EH': 'Rediriger vers le site EH si disponible',
      'redirect2Hints': 'Essaiera d\'abord d\'analyser le site EH',
      'pleaseLogInToOperate': 'Veuillez vous connecter pour opérer',
      'imageLimits': 'Quota d\'images',
      'resetCost': 'Appui long pour réinitialiser, coût',
      'assets': 'Actifs',
      'isNotDonator': 'Non-donateur ne peut pas voir le quota',
      'fetchImageQuotaFailed': 'Échec de récupération du quota d\'images',

      /// tag setting page
      'myTags': 'Mes tags',
      'myTagsHint': 'Gérer les tags surveillés/masqués en ligne',
      'localTags': 'Tags locaux',
      'localTagsHint': 'Tags de filtre supplémentaires',
      'localTagsHint2': 'Les galeries avec ces tags seront masquées',
      'addLocalTags': 'Ajouter des tags',
      'hidden': 'Masqué',
      'nope': 'Non',
      'getTagSetFailed': 'Échec de récupération du jeu de tags',
      'updateTagSetFailed': 'Échec de mise à jour du jeu de tags',
      'updateTagFailed': 'Échec de mise à jour du tag',
      'deleteTagSuccess': 'Tag supprimé avec succès',
      'deleteTagFailed': 'Échec de la suppression du tag',
      'addLocalTagHint': 'Recherchez pour ajouter un nouveau tag',

      /// Profile Setting page
      'selectedProfile': 'Profil sélectionné',
      'resetIfSwitchSite': 'Sera réinitialisé lors du changement de site',

      /// add host mapping dialog
      'addHostMapping': 'Ajouter un mappage d\'hôte',

      /// Layout
      'layoutMode': 'Mode de mise en page',
      'mobileLayoutV2Name': 'Mobile',
      'mobileLayoutV2Desc': 'Colonne unique',
      'mobileLayoutName': 'Mobile (ancien)',
      'mobileLayoutDesc': 'Plus maintenu',
      'tabletLayoutV2Name': 'Tablette',
      'tabletLayoutV2Desc': 'Double colonne',
      'tabletLayoutName': 'Tablette (ancien)',
      'tabletLayoutDesc': 'Plus maintenu',
      'desktopLayoutName': 'Bureau',
      'desktopLayoutDesc': 'Double colonne avec barre d\'onglets gauche, prise en charge du clavier',

      /// style setting page
      'enableTagZHTranslation': 'Traduire les noms de tags en chinois',
      'version': 'Version',
      'downloadTagTranslationHint': 'Téléchargement des données... Téléchargé :',
      'zhTagSearchOrderOptimization': 'Règle de tri de la saisie automatique des tags chinois',
      'zhTagSearchOrderOptimizationHint': 'Tri intelligent par défaut, tri par fréquence si activé',
      'themeMode': 'Mode thème',
      'dark': 'Sombre',
      'light': 'Clair',
      'followSystem': 'Suivre le système',
      'themeColor': 'Couleur du thème',
      'listStyle': 'Style de liste de galeries (Global)',
      'flat': 'Plat',
      'flatWithoutTags': 'Plat (sans tags)',
      'listWithoutTags': 'Carte (sans tags)',
      'listWithTags': 'Carte',
      'waterfallFlowSmall': 'Cascade (Petite)',
      'waterfallFlowMedium': 'Cascade (Moyenne)',
      'waterfallFlowBig': 'Cascade (Grande)',
      'crossAxisCountInWaterFallFlow': 'Colonnes de la cascade',
      'pageListStyle': 'Style de liste (Page)',
      'crossAxisCountInGridDownloadPageForGroup': 'Colonnes de la grille de téléchargement (Groupe)',
      'crossAxisCountInGridDownloadPageForGallery': 'Colonnes de la grille de téléchargement (Galerie)',
      'crossAxisCountInDetailPage': 'Colonnes des miniatures (Détail)',
      'global': 'Global',
      'auto': 'Automatique',
      'moveCover2RightSide': 'Déplacer la couverture à droite',
      'coverStyle': 'Style de couverture',
      'cover': 'Couverture',
      'adaptive': 'Adaptatif',
      'simpleDashboardMode': 'Page d\'accueil simplifiée',
      'simpleDashboardModeHint': 'Masquer la liste de classement et populaires',
      'hideBottomBar': 'Masquer la barre inférieure',
      'hideScroll2TopButton': 'Masquer le bouton de défilement vers le haut',
      'whenScrollUp': 'En défilant vers le haut',
      'whenScrollDown': 'En défilant vers le bas',
      'preloadGalleryCover': 'Précharger les couvertures de galeries',
      'preloadGalleryCoverHint': 'Précharger les couvertures des galeries non encore affichées',
      'enableSwipeBackGesture': 'Activer le geste de retour par glissement',
      'enableLeftMenuDrawerGesture': 'Activer le geste du tiroir de menu gauche',
      'enableQuickSearchDrawerGesture': 'Activer le geste du tiroir de recherche rapide',
      'drawerGestureEdgeWidth': 'Largeur du bord du geste du tiroir',
      'alwaysShowScroll2TopButton': 'Toujours afficher le bouton de défilement vers le haut',
      'enableDefaultFavorite': 'Activer le favori par défaut',
      'enableDefaultFavoriteHint': 'Appui long pour resélectionner',
      'enableDefaultTagSet': 'Activer le jeu de tags par défaut',
      'enableDefaultTagSetHint': 'Appui long pour resélectionner',
      'disableDefaultTagSetHint': 'Sélectionner manuellement',
      'launchInFullScreen': 'Lancer en plein écran',
      'launchInFullScreenHint': 'Basculer manuellement avec F11',
      'disableDefaultFavoriteHint': 'Sélectionner manuellement',
      'searchBehaviour': 'Comportement de recherche',
      'inheritAll': 'Tout hériter',
      'inheritAllHint': 'Utiliser les dernières options de recherche pour la prochaine recherche',
      'inheritPartially': 'Hériter partiellement',
      'inheritPartiallyHint': 'Utiliser les dernières options (sauf langue et catégorie)',
      'none': 'Aucun',
      'noneHint': 'Utiliser les options de recherche par défaut',
      'showAllGalleryTitles': 'Afficher tous les titres de galeries',
      'showAllGalleryTitlesHint': 'Afficher les titres originaux et japonais si disponibles',
      'showGalleryTagVoteStatus': 'Afficher le statut de vote des tags',
      'showGalleryTagVoteStatusHint': 'Inclut confiance, scepticisme et incorrect',
      'showComments': 'Afficher les commentaires',
      'showAllComments': 'Afficher tous les commentaires',
      'showAllCommentsHint': 'Par défaut, seulement les 45 commentaires les mieux notés et les 5 plus récents sont affichés',
      'addTag': 'Ajouter un tag',
      'addTagHint': 'Entrez de nouveaux tags séparés par des virgules',

      /// theme color
      'themeColorSettingHint': 'Attribuer des couleurs différentes pour les thèmes clair et sombre',
      'preview': 'Aperçu',
      'preset': 'Prédéfini',
      'custom': 'Personnalisé',

      /// performance
      'maxGalleryNum4Animation': 'Nombre max. de galeries pour l\'animation de la liste',
      'maxGalleryNum4AnimationHint': 'Désactiver l\'animation pour les groupes avec plus de galeries que cette valeur (style liste)',

      /// mouse wheel
      'wheelScrollSpeed': 'Vitesse de défilement de la molette',
      'ineffectiveInGalleryPage': 'Actuellement inefficace sur la page de galeries.',

      /// advanced setting page
      'enableDomainFronting': 'Activer le fronting de domaine',
      'bypassSNIBlocking': 'Contourner le blocage SNI',
      'hostMapping': 'Mappage d\'hôte',
      'hostMappingHint': 'Utilisé pour le fronting de domaine',
      'proxyAddress': 'Adresse du proxy',
      'proxyAddressHint': 'Définissez correctement si vous utilisez un serveur proxy',
      'saveSuccess': 'Enregistrement réussi',
      'saveFailed': 'Échec de l\'enregistrement',
      'updateSuccess': 'Mise à jour réussie',
      'connectTimeout': 'Délai de connexion',
      'receiveTimeout': 'Délai de réception',
      'pageCacheMaxAge': 'Durée maximale du cache de page',
      'pageCacheMaxAgeHint': 'Vous pouvez actualiser pour mettre à jour le cache',
      'cacheImageExpireDuration': 'Durée d\'expiration du cache d\'images',
      'cacheImageExpireDurationHint': 'Supprimer automatiquement le cache d\'images au démarrage',
      'oneMinute': '1 minute',
      'tenMinute': '10 minutes',
      'oneHour': '1 heure',
      'oneDay': '1 jour',
      'threeDay': '3 jours',
      'enableLogging': 'Activer la journalisation',
      'enableVerboseLogging': 'Activer la journalisation détaillée',
      'openLog': 'Ouvrir les journaux',
      'clearLogs': 'Effacer les journaux',
      'clearImagesCache': 'Effacer le cache d\'images',
      'longPress2Clear': 'Appui long pour effacer',
      'checkUpdateAfterLaunchingApp': 'Vérifier les mises à jour au démarrage',
      'checkClipboard': 'Vérifier l\'URL de galerie dans le presse-papiers',
      'clearPageCache': 'Effacer le cache de pages',
      'clearSuccess': 'Effacement réussi',
      'superResolution': 'Super résolution d\'image',
      'stopSuperResolution': 'Arrêter la super résolution',
      'deleteSuperResolvedImage': 'Supprimer l\'image super résolue',
      'superResolveOriginalImageHint': 'Le traitement de l\'image originale prend plus de temps, d\'espace et de performances. Continuer ?',
      'verityAppLinks4Android12': 'Vérifier les liens d\'application (Android 12+)',
      'verityAppLinks4Android12Hint': 'Pour Android 12+, vous devez ajouter manuellement le lien aux liens vérifiés pour ouvrir JHenTai depuis des apps tiers',
      'noImageMode': 'Mode sans image',
      'exportData': 'Exporter les données',
      'exportDataHint': 'Exporter les paramètres, règles de blocage et historique',
      'selectExportItems': 'Sélectionner les éléments à exporter',
      'importData': 'Importer les données',
      'importDataHint': 'L\'application se fermera automatiquement après l\'importation pour appliquer la configuration',

      /// host mapping page
      'hostDataSource': 'Ne pas modifier par défaut.\nSource de données : https://dns.google/',

      /// proxy page
      'proxySetting': 'Paramètres du proxy',
      'proxyType': 'Type de proxy',
      'systemProxy': 'Système',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRECT',
      'address': 'Adresse',

      /// security setting page
      'enablePasswordAuth': 'Activer l\'authentification par mot de passe',
      'enableBiometricAuth': 'Activer l\'authentification biométrique',
      'enableAuthOnResume': 'Activer l\'authentification à la reprise',
      'enableAuthOnResumeHints': 'Délai de 3 secondes',
      'enableBlurBackgroundApp': 'Flouter la page lors du changement en arrière-plan',
      'hideImagesInAlbum': 'Masquer les images dans l\'album',
      'hideImagesInAlbumHints': 'Si vous avez modifié le chemin de téléchargement par défaut, créez .nomedia manuellement',

      /// read setting page
      'enableImmersiveMode': 'Activer le mode immersif',
      'keepScreenAwakeWhenReading': 'Garder l\'écran actif pendant la lecture',
      'enableCustomReadBrightness': 'Activer la luminosité personnalisée pendant la lecture',
      'spaceBetweenImages': 'Espace entre les images',
      'enableImmersiveHint': 'Masquer la barre système',
      'enableImmersiveHint4Windows': 'Masquer la barre de titre',
      'deviceOrientation': 'Orientation de l\'appareil',
      'landscape': 'Paysage',
      'portrait': 'Portrait',
      'readDirection': 'Direction de lecture',
      'notchOptimization': 'Optimisation de l\'encoche',
      'notchOptimizationHint': 'Ajouter un espacement avant la première image pour éviter l\'encoche',
      'imageRegionWidthRatio': 'Ratio de largeur de la région d\'image',
      'gestureRegionWidthRatio': 'Ratio de largeur de la région de geste',
      'useThirdPartyViewer': 'Utiliser un visionneuse personnalisé',
      'thirdPartyViewerPath': 'Chemin du visionneuse (exécutable)',
      'showThumbnails': 'Afficher les miniatures',
      'showScrollBar': 'Afficher la barre de défilement',
      'showStatusInfo': 'Afficher le statut en bas',
      'autoModeInterval': 'Intervalle de tournage de page auto',
      'autoModeStyle': 'Style de mode auto',
      'scroll': 'Défilement',
      'turnPage': 'Tourner la page',
      'top2bottomList': 'De haut en bas (Continu)',
      'left2rightSinglePage': 'De gauche à droite (Page unique)',
      'left2rightSinglePageFitWidth': 'De gauche à droite (Ajuster la largeur)',
      'right2leftSinglePage': 'De gauche à droite (Page unique)',
      'right2leftSinglePageFitWidth': 'De gauche à droite (Ajuster la largeur)',
      'left2rightDoubleColumn': 'De gauche à droite (Double colonne)',
      'right2leftDoubleColumn': 'De gauche à droite (Double colonne)',
      'left2rightList': 'De gauche à droite (Continu)',
      'right2leftList': 'De gauche à droite (Continu)',
      'enablePageTurnByVolumeKeys': 'Utiliser les touches de volume pour tourner la page',
      'enablePageTurnAnime': 'Activer l\'animation de tournage de page',
      'enableDoubleTapToScaleUp': 'Activer le double-tap pour zoomer',
      'enableTapDragToScaleUp': 'Activer le tap-glisser pour zoomer',
      'enableBottomMenu': 'Activer le menu inférieur',
      'reverseTurnPageDirection': 'Inverser la direction de tournage de page',
      'disableGestureWhenScrolling': 'Désactiver le geste lors du défilement',
      'disablePageTurningOnTap': 'Désactiver le tournage de page par tap',
      'turnPageMode': 'Mode de tournage de page',
      'turnPageModeHint': 'Vers l\'écran suivant ou l\'image suivante',
      'enableImageMaxKilobytes': 'Activer la compression d\'image',
      'imageMaxKilobytes': 'Taille maximale de l\'image',
      'imageMaxKilobytesHint': 'Les images plus grandes que cette taille seront compressées',
      'image': 'Image',
      'screen': 'Écran',
      'preloadDistanceInOnlineMode': 'Distance de préchargement (En ligne)',
      'preloadDistanceInLocalMode': 'Distance de préchargement (Local)',
      'ScreenHeight': 'Écran',
      'preloadPageCount': 'Pages de préchargement (En ligne)',
      'preloadPageCountInLocalMode': 'Pages de préchargement (Local)',
      'continuousScroll': 'Défilement continu',
      'continuousScrollHint': 'Connecter plusieurs images ensemble',
      'doubleColumn': 'Double colonne',
      'displayFirstPageAlone': 'Afficher la première page seule',
      'displayFirstPageAloneGlobally': 'Afficher la première page seule (Global)',
      'toggleFullScreen': 'Basculer en plein écran',
      'enableAutoScaleUp': 'Activer la mise à l\'échelle automatique des grandes images',
      'enableAutoScaleUpHints': 'Mettre la largeur de l\'image à la largeur de l\'écran',

      /// preference setting page
      'showR18GImageDirectly': 'Afficher directement les images R18G',
      'defaultTab': 'Onglet par défaut',
      'showUtcTime': 'Afficher l\'heure UTC pour la galerie',
      'showDawnInfo': 'Afficher l\'événement de nouvelle aube',
      'showEncounterMonster': 'Afficher l\'événement de rencontre avec un monstre HentaiVerse',

      /// log page
      'logList': 'Liste des journaux',

      /// super resolution setting page
      'downloadSuperResolutionModelHint': 'Télécharger le modèle depuis Github',
      'modelDirectoryPath': 'Chemin du répertoire du modèle',
      'upSamplingScale': 'Échelle de suréchantillonnage',
      'modelType': 'Choisir le modèle',
      'x4plusHint': 'Utilise plus d\'espace, généralement plus rapide',
      'x4plusAnimeHint': 'Utilise moins d\'espace, généralement plus lent',
      'enable4OnlineReading': 'Traiter automatiquement pendant la lecture en ligne',

      /// download page
      'local': 'Local',
      'delete': 'Supprimer',
      'deleteTask': 'Supprimer la tâche seulement',
      'deleteTaskAndImages': 'Supprimer la tâche et les images',
      'reDownload': 'Retélécharger',
      'unlocking': 'Déverrouillage',
      'unlocked': 'Déverrouillé',
      'parsingDownloadPageUrl': 'Analyse I',
      'parsedDownloadPageUrl': 'Analyse I',
      'parsingDownloadUrl': 'Analyse II',
      'parsedDownloadUrl': 'Analyse II',
      'waitingIsolate': 'En attente',
      'downloaded': 'Téléchargé',
      'downloadFailed': 'Téléchargement échoué',
      'unpacking': 'Décompression',
      'completed': 'Terminé',
      'needReUnlock': 'Redéverrouillage requis',
      'reUnlock': 'Redéverrouiller',
      'reUnlockHint': 'Attention ! Vous devrez racheter cette archive pour la redéverrouiller.',
      'downloadHelpInfo': 'Si vous ne pouvez pas télécharger ou si vous avez des erreurs de table manquante, veuillez désinstaller et réinstaller l\'application actuelle.',
      'localGalleryHelpInfo': 'Chargez des galeries non téléchargées par JHenTai. Ajoutez une configuration dans Paramètres de téléchargement -> Chemin de scan supplémentaire puis actualisez.',
      'localGalleryHelpInfo4iOSAndMacOS': 'Chargez des galeries non téléchargées par JHenTai. Placez vos galeries dans le chemin de téléchargement par défaut puis actualisez.',
      'deleteLocalGalleryHint': 'Supprimer vos fichiers locaux',
      'priority': 'Priorité',
      'highest': 'Maximale',
      'default': 'Par défaut',
      'newGalleryCount': 'Nouvelles galeries',
      'changePriority': 'Changer la priorité',
      'changeGroup': 'Changer le groupe',
      'chooseGroup': 'Choisir un groupe',
      'renameGroup': 'Renommer le groupe',
      'deleteGroup': 'Supprimer le groupe',
      'existingGroup': 'Groupe existant',
      'groupName': 'Nom du groupe',
      'drag2sort': 'Glisser pour trier',
      'switch2GridMode': 'Passer en mode grille',
      'switch2ListMode': 'Passer en mode liste',
      'multiSelect': 'Sélection multiple',
      'multiSelectHint': 'Appuyez pour sélectionner',
      'resumeAllTasks': 'Reprendre toutes les tâches',
      'pauseAllTasks': 'Mettre en pause toutes les tâches',
      'requireDownloadComplete': 'Téléchargement complet requis',
      'operationHasCompleted': 'L\'opération est terminée',
      'operationInProgress': 'L\'opération est en cours',
      'startProcess': 'Démarrer le processus',
      'multiReDownloadHint': 'Vous allez retélécharger toutes les galeries sélectionnées.',
      'multiChangeGroupHint': 'Vous allez changer le groupe de toutes les galeries sélectionnées.',
      'multiDeleteHint': 'Vous allez supprimer toutes les galeries sélectionnées.',
      'blankImageHint': 'Le téléchargement de l\'image a retourné un résultat vide, tentative de ré-analyse.',
      'peakHoursHint': 'Télécharger des fichiers originaux aux heures de pointe nécessite des GP, vous n\'en avez pas assez, téléchargement mis en pause.',
      'oldGalleryHint': 'Télécharger les fichiers originaux de cette galerie nécessite des GP, vous n\'en avez pas assez.',
      'exceedLimitHint': 'Vous avez atteint la limite d\'images et n\'avez pas assez de GP pour acheter un quota.',
      'deleteUpdatingDependentHint': 'Une autre galerie dépend de cette galerie. Il est recommandé de la supprimer après la fin de la mise à jour.',
      'migrateToDownload': 'Migrer vers 「Télécharger」',
      'refresh': 'Actualiser',

      /// search
      'simpleSearch': 'Simple',
      'regexSearch': 'Regex',

      /// search dialog
      'searchConfig': 'Configuration de recherche',
      'addTabBar': 'Ajouter une barre d\'onglets',
      'updateTabBar': 'Mettre à jour la barre d\'onglets',
      'addQuickSearch': 'Ajouter',
      'updateQuickSearch': 'Mettre à jour',
      'filter': 'Filtre',
      'tabBarName': 'Nom de la barre d\'onglets',
      'quickSearchName': 'Nom',
      'pleaseInputValidName': 'Veuillez saisir un nom valide',
      'sameNameExists': 'Ce nom existe déjà',
      'sameConfigExists': 'Cette configuration existe déjà',
      'searchType': 'Type de recherche',
      'popular': 'Populaire',
      'ranklist': 'Classement',
      'ranklistBoard': 'Tableau de classement',
      'watched': 'Surveillé',
      'history': 'Historique',
      'keyword': 'Mot-clé',
      'orderBy': 'Trier par',
      'favoritedTime': 'Heure d\'ajout aux favoris',
      'publishedTime': 'Date de publication',
      'backspace2DeleteTag': 'Retour arrière pour supprimer le tag',
      'searchGalleryName': 'Rechercher par nom',
      'searchGalleryTags': 'Rechercher par tags',
      'searchGalleryDescription': 'Rechercher par description',
      'onlySearchExpungedGalleries': 'Chercher uniquement les galeries supprimées',
      'onlyShowGalleriesWithTorrents': 'Afficher uniquement les galeries avec torrents',
      'searchLowPowerTags': 'Rechercher les tags à faible puissance',
      'searchDownVotedTags': 'Rechercher les tags avec votes négatifs',
      'pageAtLeast': 'Pages minimum',
      'pageAtMost': 'Pages maximum',
      'pagesBetween': 'Plage de pages',
      'pageRangeSelectHint': 'min <= 1000, max >= 10\nmin/max <= 0.8, max-min >= 20',
      'to': 'à',
      'minimumRating': 'Note minimale',
      'disableFilterForLanguage': 'Désactiver le filtre de langue',
      'disableFilterForUploader': 'Désactiver le filtre d\'importateur',
      'disableFilterForTags': 'Désactiver le filtre de tags',
      'searchName': 'Rechercher par nom',
      'searchTags': 'Rechercher par tags',
      'searchNote': 'Rechercher par note',
      'allTime': 'Tout le temps',
      'year': 'Année',
      'month': 'Mois',
      'day': 'Jour',
      'favoriteHint': '''Qualificateurs : tag/titre/commentaire/note de favori''',

      /// popular page
      'getPopularListFailed': 'Échec de récupération de la liste populaire',

      /// ranklist page
      'getRanklistFailed': 'Échec de récupération du classement',
      'getSomeOfGallerysFailed': 'Échec de récupération de certaines galeries',

      /// history page
      'getHistoryGallerysFailed': 'Échec de récupération de l\'historique',

      /// search page
      'search': 'Rechercher',
      'searchFailed': 'Échec de la recherche',
      'fileSearchFailed': 'Échec de la recherche de fichier',
      'tab': 'Onglet',
      'openGallery': 'Ouvrir la galerie',
      'tapChip2Delete': 'Appuyez sur la puce pour supprimer\nAppui long sur le bouton pour tout supprimer',
      'accurateCountTemplate': '%s résultats',
      'hundredsOfCountTemplate': 'Des centaines de résultats',
      'thousandsOfCountTemplate': 'Des milliers de résultats',

      /// about page
      'author': 'Auteur',
      'Q&A': 'Q&R',
      'telegramHint': 'Vous pouvez d\'abord poser des questions sur github',

      /// download setting page
      'downloadPath': 'Chemin de téléchargement',
      'changeDownloadPathHint': 'Appui long pour modifier (évitez la carte SD ou les chemins système). Copie automatiquement les galeries téléchargées, conserve les anciens fichiers. Essayez de réinitialiser en cas d\'erreur.',
      'resetDownloadPath': 'Réinitialiser le chemin de téléchargement',
      'singleImageSavePath': 'Chemin de sauvegarde d\'image unique',
      'extraGalleryScanPath': 'Chemin de scan supplémentaire',
      'extraGalleryScanPathHint': 'Pour scanner et charger des galeries locales',
      'longPress2Reset': 'Appui long pour réinitialiser',
      'downloadOriginalImage': 'Image originale',
      'downloadOriginalImageByDefault': 'Sélectionner l\'image originale par défaut',
      'originalImage': 'Original',
      'resampleImage': 'Rééchantillonner',
      'defaultGalleryGroup': 'Groupe de galerie par défaut',
      'defaultArchiveGroup': 'Groupe d\'archive par défaut',
      'never': 'Jamais',
      'manual': 'Manuel',
      'always': 'Toujours',
      'needPermissionToChangeDownloadPath': 'Permission requise pour modifier le chemin',
      'invalidPath': 'Chemin invalide. Évitez la carte SD, les chemins système ou racine.',
      'downloadTaskConcurrency': 'Concurrence de téléchargement',
      'needRestart': 'Redémarrage requis',
      'downloadTimeout': 'Délai de téléchargement',
      'speedLimit': 'Limite de vitesse',
      'speedLimitHint': 'Ne pas aller trop vite',
      'per': 'Par',
      'images': 'Images',
      'downloadAllGallerysOfSamePriority': 'Télécharger toutes les galeries de même priorité',
      'downloadAllGallerysOfSamePriorityHint': 'Par défaut, seulement 1 galerie du groupe de priorité la plus haute est téléchargée simultanément',
      'alwaysUseDefaultGroup': 'Toujours utiliser le groupe par défaut',
      'restoreDownloadTasks': 'Restaurer les tâches de téléchargement',
      'enableStoreMetadataForRestore': 'Activer le stockage des métadonnées pour restauration',
      'enableStoreMetadataForRestoreHint': 'Désactiver cela empêche la restauration des tâches de téléchargement',
      'archiveDownloadIsolateCount': 'Nombre de threads de téléchargement d\'archive',
      'archiveDownloadIsolateCountHint': 'La somme des threads pour toutes les tâches doit être inférieure à 10, sinon le téléchargement échouera',
      'manageArchiveDownloadConcurrency': 'Gérer la concurrence de téléchargement d\'archive',
      'manageArchiveDownloadConcurrencyHint': 'L\'archive attendra jusqu\'à avoir suffisamment de threads disponibles',
      'deleteArchiveFileAfterDownload': 'Supprimer le fichier .zip après téléchargement',
      'restoreDownloadTasksHint': 'Restaurer les tâches depuis les métadonnées',
      'restoreDownloadTasksSuccess': 'Restauration des tâches réussie',
      'restoredCount': 'Tâches restaurées',
      'restoredGalleryCount': 'Galeries restaurées',
      'restoredArchiveCount': 'Archives restaurées',
      'restoreTasksAutomatically': 'Restaurer les tâches automatiquement',
      'restoreTasksAutomaticallyHint': 'Restaurer automatiquement les tâches au démarrage',
      'brokenDownloadPathHint': 'Votre chemin de téléchargement semble corrompu, le téléchargement peut ne pas fonctionner',
      'brokenExtraScanPathHint': 'Votre chemin de galerie locale semble corrompu, les galeries locales peuvent ne pas être reconnues',
      'useJH2UpdateGallery': 'Utiliser le serveur JH pour accélérer les mises à jour de galeries',

      /// archive bot settings
      'archiveBotSettings': 'Paramètres Archive Bot',
      'archiveBotSettingsHint': 'Utiliser Archive Bot pour obtenir des liens d\'archive gratuitement',
      'apiSetting': 'Paramètres API',
      'apiAddress': 'Adresse',
      'apiKey': 'Clé',
      'apiKeyHint': 'Entrez la clé obtenue du bot Telegram',
      'dailyCheckin': 'Connexion quotidienne',
      'currentBalance': 'Solde GP actuel',
      'checkBalanceFailed': 'Échec de récupération du solde GP',
      'checkInFailed': 'Échec de la connexion',
      'checkInSuccess': 'Connexion réussie',
      'checkInSuccessHint': 'GP obtenu : %s, total GP actuel : %s.',
      'pauseDownloadByInvalidArchiveBotKey': 'Paramètres Archive Bot invalides, téléchargement mis en pause',
      'chooseArchiveParseSource': 'Changer la source d\'analyse',
      'official': 'Officiel',
      'archiveBot': 'Archive Bot',
      'changeParseSource2Official': 'Changer la source vers officiel',
      'changeParseSource2Bot': 'Changer la source vers Archive Bot',
      'invalidParam': 'Paramètre invalide',
      'invalidApiKey': 'Clé API invalide',
      'banned': 'Vous avez été banni',
      'fetchGalleryInfoFailed': 'Échec de récupération des informations de la galerie',
      'insufficientGP': 'GP insuffisant',
      'parseFailed': 'Échec de l\'analyse',
      'checkedIn': 'Déjà connecté aujourd\'hui',
      'serverError': 'Erreur interne du bot Archive',
      'useProxyServer': 'Utiliser le serveur proxy JHenTai',
      'useProxyServerHint': 'Router les requêtes via le serveur JHenTai',

      /// password setting dialog
      'setPasswordHint': 'Veuillez saisir votre mot de passe',
      'confirmPasswordHint': 'Veuillez saisir à nouveau votre mot de passe',
      'passwordNotMatchHint': 'Les mots de passe ne correspondent pas, veuillez réessayer',

      /// cloud setting page
      'serverCondition': 'État du serveur',
      'configSync': 'Synchronisation de la configuration',
      'configSyncHint': 'Stocker vos données de configuration dans le cloud (jusqu\'à 50 entrées)',
      'upload2cloud': 'Téléverser dans le cloud',
      'upload2cloudHint': 'Téléverser votre configuration locale actuelle',
      'tap2upload': 'Appuyez pour téléverser',
      'copyIdentificationCodeSuccess': 'Téléversement réussi. Code d\'identification copié',
      'copyShareCode': 'Copier le code de partage',
      'import': 'Importer',
      'save2Local': 'Enregistrer localement',
      'readIndexRecord': 'Progression de lecture',
      'quickSearch': 'Configuration de recherche rapide',
      'blockRules': 'Règles de blocage',
      'searchHistory': 'Historique de recherche',
      'galleryHistory': 'Historique des galeries',

      /// block rule page
      'configureBlockRuleFailed': 'Échec de configuration de la règle de blocage',
      'removeBlockRuleFailed': 'Échec de suppression de la règle de blocage',
      'inputNumberHint': 'Veuillez saisir un nombre correct',
      'inputRegexHint': 'Veuillez saisir une regex correcte',
      'useBuiltInBlockedUsers': 'Activer la liste de blocage intégrée',
      'useBuiltInBlockedUsersHint': 'Filtrer les commentaires des utilisateurs sur la liste de blocage',
      'blockingRules': 'Règles de blocage',
      'blockingRulesHint': 'Règles de blocage supplémentaires pour galeries et commentaires',
      'blockingTarget': 'Cible de blocage',
      'blockingAttribute': 'Attribut de blocage',
      'blockingPattern': 'Modèle de blocage',
      'blockingExpression': 'Expression de blocage',
      'contain': 'Contient',
      'notContain': 'Ne contient pas',
      'regex': 'Regex',
      'comment': 'Commentaire',
      'tag': 'Tag',
      'userId': 'ID utilisateur',
      'content': 'Contenu',
      'incompleteInformation': 'Informations incomplètes',
      'noBlockingRuleHint': 'Ajoutez au moins 1 règle',
      'notSameBlockingRuleTargetHint': 'Toutes les sous-règles doivent avoir la même cible de blocage',
      'blockingRuleHelp': '''Cible de blocage : Filtrer les galeries sur la page de liste ou les commentaires sur la page de détails. Toutes les sous-règles sous la même règle doivent avoir la même cible de blocage.
Attribut de blocage : Spécifiez l'attribut de la cible sur lequel la règle est basée.
Modèle de blocage : Utilisez des expressions régulières pour les scénarios complexes.
Expression de blocage : Chaînes simples ou expressions régulières.

Note1 : Les règles différentes ont une relation OU (||), tandis que les sous-règles sous la même règle ont une relation ET (&&).
Note2 : Lors du blocage de tags, la règle vérifie chaque tag de la galerie, l'expression doit être écrite pour un seul tag.
Note3 : Lors du blocage de tags, vous devez spécifier le tag complet avec l'espace de noms si vous utilisez la règle '='.
Note4 : Vous devez utiliser une mise en page de galerie qui peut afficher tous les tags sur E-Hentai, comme "Étendu", sinon certaines galeries peuvent ne pas être filtrées correctement.

Exemple 1 : Bloquer les galeries avec le tag "yaoi" mais sans le tag "tomgirl"————Tag de galerie Contient male:yaoi && Tag de galerie Ne contient pas male:tomgirl
Exemple 2 : Bloquer les commentaires avec un score inférieur ou égal à 10————Score du commentaire <= 10''',

      /// quick search page
      'quickSearch': 'Recherche rapide',

      /// dashboard page
      'seeAll': 'Tout voir',
      'newest': 'Derniers',

      /// torrent dialog
      'outdated': 'Obsolète',

      /// tag dialog
      'warningImageHint': 'Image R18G, appuyez pour voir',

      /// tagSet dialog
      'chooseTagSet': 'Choisir un jeu de tags',

      /// tag namespace
      'language': 'Langue',
      'artist': 'Artiste',
      'character': 'Personnage',
      'female': 'Féminin',
      'male': 'Masculin',
      'parody': 'Parodie',
      'group': 'Groupe',
      'mixed': 'Mixte',
      'Coser': 'Coseur',
      'cosplayer': 'Cosplayeur',
      'reclass': 'Reclasser',
      'temp': 'Temporaire',
      'other': 'Autre',
    };
  }
}
