import 'dart:core';

class ja_JP {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': 'はい',
      'no': 'いいえ',
      'cancel': 'キャンセル',
      'OK': 'OK',
      'reset': 'リセット',
      'success': '成功',
      'error': 'エラー',
      'failed': '失敗',
      'reload': '再読込',
      'noMoreData': 'これ以上データなし',
      'noData': 'データなし',
      'operationFailed': '操作失敗',
      'needLoginToOperate': '操作にはログインが必要です',
      'hasCopiedToClipboard': 'クリップボードにコピーしました',
      'networkError': 'ネットワークエラー、タップして再読込',
      'systemError': 'システムエラー',
      'invalid': '無効',
      'internalError': '内部エラー',
      'you': 'あなた',
      'retryHint': '更新後に再試行してください',
      'stop': '停止',
      'attention': '注意',
      'jump': 'ジャンプ',
      'deleteAll': 'すべて削除',
      'connectionTimeoutHint': 'ネットワーク接続タイムアウト',
      'receiveDataTimeoutHint': 'データ受信タイムアウト',
      'archiveError': 'アーカイブのダウンロードエラー',
      'edit': '編集',

      'home': 'ホーム',
      'gallery': 'ギャラリー',
      'setting': '設定',

      /// schedule
      'dawnOfaNewDay': '新しい一日の夜明けです！',
      'encounterMonster': 'モンスターに遭遇しました！',
      'encounterMonsterHint': 'クリックしてHentaiVerseで戦いましょう。',

      /// unlock page
      'localizedReason': '続行するために認証してください',
      'tap2Auth': 'タップして認証',
      'passwordErrorHint': 'パスワードが間違っています、もう一度試してください',

      /// start page
      'TapAgainToExit': 'もう一度タップして終了',

      /// update dialog
      'availableUpdate': 'アップデートあり！',
      'LatestVersion': '最新版',
      'CurrentVersion': '現在のバージョン',
      'check': '確認',
      'dismiss': '閉じる',

      /// login page
      'login': 'ログイン',
      'notLoggedIn': 'ログイン',
      'logout': 'ログアウト',
      'passwordLogin': 'パスワードログイン',
      'cookieLogin': 'Cookieログイン',
      'useWebview': 'Webviewを使用',
      'skipCookieVerification': '確認をスキップ',
      'youHaveLoggedInAs': 'こんにちは：   ',
      'cookieIsBlack': 'Cookieがブラック',
      'cookieFormatError': 'Cookie形式エラー',
      'invalidCookie': 'ログイン失敗または無効なCookie',
      'loginFail': 'ログイン失敗',
      'userName': 'ユーザー名',
      'EHUser': 'EHユーザー',
      'password': 'パスワード',
      'needCaptcha': 'キャプチャが必要です。Cookieまたはウェブから再ログインしてください。',
      'userNameOrPasswordMismatch': 'ユーザー名またはパスワードが一致しません',
      'copyCookies': 'Cookieをコピー',
      'tap2Copy': 'タップしてコピー',
      'webLoginIsDisabled': 'デスクトップではWebログインは無効です',
      'loginSuccess': 'ログイン成功',
      'userNameFormHint': 'Sad Pandaの場合はCookieを試してください',
      'tap2Login': 'ログイン',
      'parse': '解析',
      'igneousHint': 'igneous（EX必須）',
      'refreshIgneousFailed': 'Ignorousの更新失敗',

      /// request
      'sadPanda': 'Sad Panda（データなし）。参照: https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',

      /// gallery card
      'filtered': 'フィルター済み',

      /// gallery page
      'getGallerysFailed': 'ギャラリーの取得失敗',
      'refreshGalleryFailed': 'ギャラリーの更新失敗',
      'tabBarSetting': 'タブバー設定',
      'jumpPageTo': 'ページへ移動',
      'range': '範囲',
      'current': '現在',
      'galleryUrlDetected': 'クリップボードにギャラリーURLが見つかりました',
      'galleryUrlDetectedHint': 'タップして詳細ページへ',

      /// details page
      'read': '読む',
      'download': 'ダウンロード',
      'favorite': 'お気に入り',
      'rating': '評価',
      'torrent': 'トレント',
      'archive': 'アーカイブ',
      'statistic': '統計',
      'similar': '類似',
      'downloading': 'ダウンロード中',
      'resume': '再開',
      'pause': '一時停止',
      'finished': '完了',
      'update': '更新',
      'submit': '送信',
      'chooseFavorite': 'お気に入りを選択',
      'asYourDefault': 'デフォルトとして設定',
      'Note': 'メモ',
      'addNoteHint': 'メモを追加する前にスロットを選択してください',
      'uploader': 'アップロード者',
      'allComments': 'すべてのコメント',
      'noComments': 'コメントなし',
      'lastEditedOn': '最終編集日',
      'getGalleryDetailFailed': 'ギャラリー詳細の取得失敗',
      'cloudflare403': 'Cloudflareにネットワークリクエストが制限されています。ネットワークを切り替えるか別のログイン方法をお試しください。',
      'invisible2User': 'このギャラリーはあなたには非表示です',
      'invisibleHints': 'このギャラリーは削除されたか利用不可です。',
      'copyRightHints': 'このギャラリーは著作権の申し立てにより利用不可です：',
      'refreshGalleryDetailsFailed': 'ギャラリー詳細の更新失敗',
      'failToGetThumbnails': 'サムネイルの取得失敗',
      'favoriteGallerySuccess': 'ギャラリーをお気に入りに追加しました',
      'favoriteGalleryFailed': 'お気に入りの追加失敗',
      'removeFavoriteSuccess': 'お気に入りの削除成功',
      'removeFavoriteFailed': 'お気に入りの削除失敗',
      'getGalleryFavoriteInfoFailed': 'ギャラリーのお気に入り情報の取得失敗',
      'favoriteNoteSlotFullHint': 'お気に入りメモのスロットが満杯です。先にいくつかのメモを削除してください',
      'ratingSuccess': '評価成功',
      'ratingFailed': '評価失敗',
      'voteTagFailed': 'タグ投票失敗',
      'beginToDownload': 'ダウンロード開始',
      'resumeDownload': 'ダウンロード再開',
      'pauseDownload': 'ダウンロード一時停止',
      'addNewTagSetSuccess': '新しいタグセットの追加成功',
      'addNewWatchedTagSetSuccess': '新しい監視タグセットの追加成功',
      'addNewHiddenTagSetSuccess': '新しい非表示タグセットの追加成功',
      'addNewTagSetSuccessHint': '設定->EH->マイタグでタグを確認できます',
      'addNewTagSetFailed': '新しいタグセットの追加失敗',
      'VisitorStatistics': '訪問者統計',
      'invisible2UserWithoutDonation': 'このギャラリーの統計は寄付なしのユーザーには非表示です',
      'getGalleryStatisticsFailed': 'ギャラリー統計の取得失敗',
      'totalVisits': '合計訪問数',
      'visits': '訪問数',
      'imageAccesses': '画像アクセス数',
      'period': '期間',
      'ranking': 'ランキング',
      'score': 'スコア',
      'NotOnTheList': 'リスト外',
      'getGalleryArchiveFailed': 'ギャラリーアーカイブの取得失敗',
      'parseGalleryArchiveFailed': '解析失敗。e-hentaiの[アーカイバー設定]が[手動選択、手動開始（デフォルト）]になっているか確認してください',
      'original': 'オリジナル',
      'resample': 'リサンプル',
      'beginToDownloadArchive': 'アーカイブのダウンロード開始',
      'beginToDownloadArchiveHint': 'ダウンロード -> アーカイブで進捗を確認できます',
      'updateGalleryError': 'ギャラリーの更新エラー',
      'thisGalleryHasANewVersion': 'このギャラリーに新しいバージョンがあります',
      'hasUpdated': '更新済み',
      'unpackingArchiveError': 'アーカイブの解凍エラー',
      'failedToDealWith': '処理失敗',
      'hasDownloaded': 'ダウンロード済み',
      '410Hints': 'このアーカイブのダウンロードバイト数が上限を超えました。再開するにはアーカイブを再ロック解除する必要があります。',
      '429Hints': 'ダウンロードリクエストが多すぎます！アーカイブのダウンロード並行数を減らしてください。',
      'getUnpackedImagesFailedMsg': 'JHenTaiはこのアーカイブの画像を読み込めません。ローカルファイルを確認してください。',
      'getGalleryTorrentsFailed': 'トレントの取得失敗',
      'chooseArchive': 'アーカイブを選択',
      'tagSetExceedLimit': '上限に達したため、これ以上タグを追加できません',
      'useTranslation': '翻訳を使用',
      'addTagSuccess': 'タグの追加成功',
      'addTagFailed': 'タグの追加失敗',
      'parentGallery': '親ギャラリー',
      'blockUploaderLocally': 'ユーザーをローカルでブロック',
      'block': 'ブロック',

      /// detail dialog
      'galleryUrl': 'ギャラリーURL',
      'title': 'タイトル',
      'japaneseTitle': '日本語タイトル',
      'category': 'カテゴリ',
      'publishTime': '公開日時',
      'pageCount': 'ページ数',
      'favoriteCount': 'お気に入り数',
      'ratingCount': '評価数',

      /// comment page
      'newComment': '新しいコメント',
      'updateComment': 'コメントを更新',
      'commentTooShort': 'コメントが短すぎます',
      'sendCommentFailed': 'コメントの送信失敗',
      'voteCommentFailed': 'コメントの投票失敗',
      'voteCommentFailedHint': '先に詳細ページを下に引いて更新してみてください',
      'unknownUser': '不明なユーザー',
      'atLeast3Characters': '3文字以上必要です',
      'noJHenTaiHints': 'JHenTaiについては言及しないでください',
      'blockUser': 'ユーザーをブロック',

      /// EHImage
      'reloadImage': '画像を再読込',

      /// read page
      'parsingPage': 'ページを解析中',
      'parsingURL': 'URLを解析中',
      'parsePageFailed': 'ページの解析失敗、タップして再試行',
      'parseURLFailed': 'URLの解析失敗、タップして再試行',
      'loading': '読み込み中',
      'paused': '一時停止中',
      'exceedImageLimits': '画像制限を超過',
      'ehServerError': 'EHのサーバーエラーが発生しました。後でもう一度試してください',
      'unsupportedImagePageStyle': 'JHenTaiはマルチページビューア（MPV）をサポートしていません。e-hentai.orgでデフォルトスタイルに変更してください',
      'toNext': '次へ',
      'toPrev': '前へ',
      'back': '戻る',
      'toggleMenu': 'メニュー切替',
      'share': '共有',
      'save': '画像に保存',

      /// setting page
      'account': 'アカウント',
      'EH': 'EH',
      'style': 'スタイル',
      'preference': '設定',
      'network': 'ネットワーク',
      'performance': 'パフォーマンス',
      'mouseWheel': 'マウスホイール',
      'advanced': '詳細設定',
      'cloud': 'クラウド',
      'security': 'セキュリティ',
      'about': 'について',
      'accountSetting': 'アカウント設定',
      'styleSetting': 'スタイル設定',
      'advancedSetting': '詳細設定',
      'securitySetting': 'セキュリティ設定',
      'ehSetting': 'EHサイト設定',
      'readSetting': '読書設定',
      'preferenceSetting': '設定',
      'downloadSetting': 'ダウンロード設定',
      'networkSetting': 'ネットワーク設定',
      'performanceSetting': 'パフォーマンス設定',
      'mouseWheelSetting': 'マウスホイール設定',

      /// eh setting page
      'site': 'サイト',
      'redirect2Eh': '利用可能な場合はEHにリダイレクト',
      'redirect2EhHint': 'ネットワーク性能向上のためEHサイトのギャラリー詳細ページを先に読み込みます',
      'redirectAllGallery': 'すべてのギャラリーをEHにリダイレクト',
      'imDonorHint': '寄付者の場合、これをオンにするとEXサイトেরギャラリーへのアクセスに役立ちます',
      'profileSetting': 'プロファイル設定',
      'chooseProfileHint': 'JHenTaiで使用するプロファイルを選択してください',
      'siteSetting': 'サイト設定',
      'siteSettingHint': 'e-hentaiでサイト設定を編集',
      'showCookie': 'Cookie',
      'redirect2EH': '利用可能な場合はEHサイトにリダイレクト',
      'redirect2Hints': 'EHサイトを最初に解析しようとします',
      'pleaseLogInToOperate': '操作するにはログインしてください',
      'imageLimits': '画像クオータ',
      'resetCost': '長押しでリセット、コスト',
      'assets': '資産',
      'isNotDonator': '非寄付者はクオータを見ることができません',
      'fetchImageQuotaFailed': '画像クオータの取得失敗',

      /// tag setting page
      'myTags': 'マイタグ',
      'myTagsHint': '監視・非表示タグをオンラインで管理',
      'localTags': 'ローカルタグ',
      'localTagsHint': '追加フィルタータグ',
      'localTagsHint2': 'これらのタグを持つギャラリーは非表示になります',
      'addLocalTags': 'タグを追加',
      'hidden': '非表示',
      'nope': 'なし',
      'getTagSetFailed': 'タグセットの取得失敗',
      'updateTagSetFailed': 'タグセットの更新失敗',
      'updateTagFailed': 'タグの更新失敗',
      'deleteTagSuccess': 'タグの削除成功',
      'deleteTagFailed': 'タグの削除失敗',
      'addLocalTagHint': '検索して新しいタグを追加',

      /// Profile Setting page
      'selectedProfile': '選択中のプロファイル',
      'resetIfSwitchSite': 'サイト切替時にリセットされます',

      /// add host mapping dialog
      'addHostMapping': 'ホストマッピングを追加',

      /// Layout
      'layoutMode': 'レイアウトモード',
      'mobileLayoutV2Name': 'モバイル',
      'mobileLayoutV2Desc': 'シングルカラム',
      'mobileLayoutName': 'モバイル（旧）',
      'mobileLayoutDesc': 'メンテナンス停止',
      'tabletLayoutV2Name': 'タブレット',
      'tabletLayoutV2Desc': 'ダブルカラム',
      'tabletLayoutName': 'タブレット（旧）',
      'tabletLayoutDesc': 'メンテナンス停止',
      'desktopLayoutName': 'デスクトップ',
      'desktopLayoutDesc': '左タブバー付きダブルカラム、キーボードサポート',

      /// style setting page
      'enableTagZHTranslation': 'タグ名を中国語に翻訳',
      'version': 'バージョン',
      'downloadTagTranslationHint': 'データをダウンロード中...ダウンロード済み：',
      'zhTagSearchOrderOptimization': '中国語タグ自動補完の並び順ルール',
      'zhTagSearchOrderOptimizationHint': 'デフォルトはインテリジェントソート、有効化すると頻度順に並べます',
      'themeMode': 'テーマモード',
      'dark': 'ダーク',
      'light': 'ライト',
      'followSystem': 'システムに従う',
      'themeColor': 'テーマカラー',
      'listStyle': 'ギャラリーリストスタイル（グローバル）',
      'flat': 'フラット',
      'flatWithoutTags': 'フラット（タグなし）',
      'listWithoutTags': 'カード（タグなし）',
      'listWithTags': 'カード',
      'waterfallFlowSmall': '瀑布フロー（小）',
      'waterfallFlowMedium': '瀑布フロー（中）',
      'waterfallFlowBig': '瀑布フロー（大）',
      'crossAxisCountInWaterFallFlow': '瀑布フロー列数',
      'pageListStyle': 'ギャラリーリストスタイル（ページ）',
      'crossAxisCountInGridDownloadPageForGroup': 'ダウンロードページグリッド列数（グループ）',
      'crossAxisCountInGridDownloadPageForGallery': 'ダウンロードページグリッド列数（ギャラリー）',
      'crossAxisCountInDetailPage': '詳細ページサムネイル列数',
      'global': 'グローバル',
      'auto': '自動',
      'moveCover2RightSide': 'カバーを右側へ移動',
      'coverStyle': 'カバースタイル',
      'cover': 'カバー',
      'adaptive': 'アダプティブ',
      'simpleDashboardMode': 'シンプルホームページ',
      'simpleDashboardModeHint': 'ランクリストと人気を非表示',
      'hideBottomBar': 'ボトムバーを非表示',
      'hideScroll2TopButton': 'トップへスクロールボタンを非表示',
      'whenScrollUp': '上にスクロール時',
      'whenScrollDown': '下にスクロール時',
      'preloadGalleryCover': 'ギャラリーカバーをプリロード',
      'preloadGalleryCoverHint': 'まだページに表示されていないギャラリーのカバーをプリロードします',
      'enableSwipeBackGesture': 'スワイプバックジェスチャーを有効化',
      'enableLeftMenuDrawerGesture': '左メニュードロワージェスチャーを有効化',
      'enableQuickSearchDrawerGesture': 'クイック検索ドロワージェスチャーを有効化',
      'drawerGestureEdgeWidth': 'ドロワージェスチャーエッジ幅',
      'alwaysShowScroll2TopButton': 'トップへスクロールボタンを常に表示',
      'enableDefaultFavorite': 'デフォルトお気に入りを有効化',
      'enableDefaultFavoriteHint': '長押しで再選択',
      'enableDefaultTagSet': 'デフォルトタグセットを有効化',
      'enableDefaultTagSetHint': '長押しで再選択',
      'disableDefaultTagSetHint': '手動で選択',
      'launchInFullScreen': 'フルスクリーンで起動',
      'launchInFullScreenHint': 'F11で手動切替',
      'disableDefaultFavoriteHint': '手動で選択',
      'searchBehaviour': '検索の動作',
      'inheritAll': 'すべて引き継ぐ',
      'inheritAllHint': '次の検索に最後の検索オプションを使用',
      'inheritPartially': '一部引き継ぐ',
      'inheritPartiallyHint': '次の検索に最後の検索オプションを使用（言語とカテゴリを除く）',
      'none': 'なし',
      'noneHint': '次の検索にデフォルトの検索オプションを使用',
      'showAllGalleryTitles': 'すべてのギャラリータイトルを表示',
      'showAllGalleryTitlesHint': '利用可能な場合、オリジナルと日本語タイトルを両方表示',
      'showGalleryTagVoteStatus': 'ギャラリータグの投票状況を表示',
      'showGalleryTagVoteStatusHint': '信頼度、懐疑論、不正確を含む',
      'showComments': 'コメントを表示',
      'showAllComments': 'すべてのコメントを表示',
      'showAllCommentsHint': 'デフォルトでは上位45件と最新5件のコメントのみ表示されます',
      'addTag': 'タグを追加',
      'addTagHint': '新しいタグをカンマ区切りで入力',

      /// theme color setting page
      'themeColorSettingHint': 'ライトとダークテーマに異なる色を割り当てる',
      'preview': 'プレビュー',
      'preset': 'プリセット',
      'custom': 'カスタム',

      /// performance setting page
      'maxGalleryNum4Animation': 'ダウンロードページのリストアニメーションの最大ギャラリー数',
      'maxGalleryNum4AnimationHint': 'この値より多いギャラリーを持つグループのアニメーションを無効化（リストスタイル用）',

      /// mouse wheel setting page
      'wheelScrollSpeed': 'ホイールスクロール速度',
      'ineffectiveInGalleryPage': '現在ギャラリーページでは無効です。',

      /// advanced setting page
      'enableDomainFronting': 'ドメインフロンティングを有効化',
      'bypassSNIBlocking': 'バイパスSNIブロッキング',
      'hostMapping': 'ホストマッピング',
      'hostMappingHint': 'ドメインフロンティングに使用',
      'proxyAddress': 'プロキシアドレス',
      'proxyAddressHint': 'プロキシサーバーを使用する場合は正しく設定してください',
      'saveSuccess': '保存成功',
      'saveFailed': '保存失敗',
      'updateSuccess': '更新成功',
      'connectTimeout': '接続タイムアウト',
      'receiveTimeout': 'データ受信タイムアウト',
      'pageCacheMaxAge': 'ページキャッシュの有効期限',
      'pageCacheMaxAgeHint': 'ページを更新してキャッシュを更新できます',
      'cacheImageExpireDuration': '画像キャッシュの有効期限',
      'cacheImageExpireDurationHint': 'アプリ起動後に自動的に画像キャッシュを削除',
      'oneMinute': '1分',
      'tenMinute': '10分',
      'oneHour': '1時間',
      'oneDay': '1日',
      'threeDay': '3日',
      'enableLogging': 'ログを有効化',
      'enableVerboseLogging': '詳細ログを有効化',
      'openLog': 'ログを開く',
      'clearLogs': 'ログをクリア',
      'clearImagesCache': '画像キャッシュをクリア',
      'longPress2Clear': '長押しでクリア',
      'checkUpdateAfterLaunchingApp': '起動後にアップデートを確認',
      'checkClipboard': 'クリップボードのギャラリーURLを確認',
      'clearPageCache': 'ページキャッシュをクリア',
      'clearSuccess': 'クリア成功',
      'superResolution': '画像超解像',
      'stopSuperResolution': '超解像を停止',
      'deleteSuperResolvedImage': '超解像画像を削除',
      'superResolveOriginalImageHint': '元の画像の処理にはより多くの時間・スペース・パフォーマンスが必要です。続けますか？',
      'verityAppLinks4Android12': 'アプリリンクを確認（Android 12+）',
      'verityAppLinks4Android12Hint': 'Android 12+では、サードパーティアプリからJHenTaiを開くには確認済みリンクに手動で追加が必要です',
      'noImageMode': '画像なしモード',
      'exportData': 'データをエクスポート',
      'exportDataHint': '設定・ブロックルール・履歴をエクスポート',
      'selectExportItems': 'エクスポートするアイテムを選択',
      'importData': 'データをインポート',
      'importDataHint': 'インポート後、最新の設定を適用するためにアプリが自動的に終了します',

      /// host mapping page
      'hostDataSource': 'デフォルトで変更不要。\nデータソース: https://dns.google/',

      /// proxy page
      'proxySetting': 'プロキシ設定',
      'proxyType': 'プロキシタイプ',
      'systemProxy': 'システム',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRECT',
      'address': 'アドレス',

      /// security setting page
      'enablePasswordAuth': 'パスワード認証を有効化',
      'enableBiometricAuth': '生体認証を有効化',
      'enableAuthOnResume': '再開時に認証を有効化',
      'enableAuthOnResumeHints': '3秒の遅延',
      'enableBlurBackgroundApp': 'バックグラウンド切替時にページをぼかす',
      'hideImagesInAlbum': 'アルバムで画像を非表示',
      'hideImagesInAlbumHints': 'デフォルトのダウンロードパスを変更した場合、.nomediaを手動で作成する必要があります',

      /// read setting page
      'enableImmersiveMode': '没入モードを有効化',
      'keepScreenAwakeWhenReading': '読書中は画面を常時点灯',
      'enableCustomReadBrightness': '読書中カスタム輝度を有効化',
      'spaceBetweenImages': '画像間のスペース',
      'enableImmersiveHint': 'システムバーを非表示',
      'enableImmersiveHint4Windows': 'タイトルバーを非表示',
      'deviceOrientation': 'デバイスの向き',
      'landscape': '横向き',
      'portrait': '縦向き',
      'readDirection': '読む方向',
      'notchOptimization': 'ノッチ最適化',
      'notchOptimizationHint': 'ノッチとステータスバーを避けるため最初の画像の前にパディングを追加',
      'imageRegionWidthRatio': '画像領域の幅の比率',
      'gestureRegionWidthRatio': 'ジェスチャー領域の幅の比率',
      'useThirdPartyViewer': 'カスタムビューアーを使用',
      'thirdPartyViewerPath': 'カスタムビューアーのパス（実行ファイル）',
      'showThumbnails': 'サムネイルを表示',
      'showScrollBar': 'スクロールバーを表示',
      'showStatusInfo': '下部にステータスを表示',
      'autoModeInterval': 'ページ送り間隔',
      'autoModeStyle': '自動モードスタイル',
      'scroll': 'スクロール',
      'turnPage': 'ページ送り',
      'top2bottomList': '上から下（連続）',
      'left2rightSinglePage': '左から右（シングルページ）',
      'left2rightSinglePageFitWidth': '左から右（幅に合わせる）',
      'right2leftSinglePage': '右から左（シングルページ）',
      'right2leftSinglePageFitWidth': '右から左（幅に合わせる）',
      'left2rightDoubleColumn': '左から右（ダブルカラム）',
      'right2leftDoubleColumn': '右から左（ダブルカラム）',
      'left2rightList': '左から右（連続）',
      'right2leftList': '右から左（連続）',
      'enablePageTurnByVolumeKeys': 'ボリュームキーでページ送り',
      'enablePageTurnAnime': 'ページ送りアニメーションを有効化',
      'enableDoubleTapToScaleUp': 'ダブルタップで拡大を有効化',
      'enableTapDragToScaleUp': 'タップドラッグで拡大を有効化',
      'enableBottomMenu': 'ボトムメニューを有効化',
      'reverseTurnPageDirection': 'ページ送り方向を逆転',
      'disableGestureWhenScrolling': 'スクロール中のジェスチャーを無効化',
      'disablePageTurningOnTap': 'タップでのページ送りを無効化',
      'turnPageMode': 'ページ送りモード',
      'turnPageModeHint': '次の画面または次の画像へ',
      'enableImageMaxKilobytes': '画像圧縮を有効化',
      'imageMaxKilobytes': '画像の最大サイズ',
      'imageMaxKilobytesHint': 'このサイズより大きい画像は圧縮されます',
      'image': '画像',
      'screen': '画面',
      'preloadDistanceInOnlineMode': 'プリロード距離（オンライン）',
      'preloadDistanceInLocalMode': 'プリロード距離（ローカル）',
      'ScreenHeight': '画面',
      'preloadPageCount': 'プリロードページ数（オンライン）',
      'preloadPageCountInLocalMode': 'プリロードページ数（ローカル）',
      'continuousScroll': '連続スクロール',
      'continuousScrollHint': '複数の画像をつなぎ合わせる',
      'doubleColumn': 'ダブルカラム',
      'displayFirstPageAlone': '最初のページを単独表示',
      'displayFirstPageAloneGlobally': '最初のページを単独表示（グローバル）',
      'toggleFullScreen': 'フルスクリーン切替',
      'enableAutoScaleUp': '長い画像の自動拡大を有効化',
      'enableAutoScaleUpHints': '画像の幅を画面幅に合わせます',

      /// preference setting page
      'showR18GImageDirectly': 'R18G画像を直接表示',
      'defaultTab': 'デフォルトタブ',
      'showUtcTime': 'ギャラリーのUTC時刻を表示',
      'showDawnInfo': '夜明けイベントを表示',
      'showEncounterMonster': 'HentaiVerseモンスター遭遇イベントを表示',

      /// log page
      'logList': 'ログリスト',

      /// super resolution setting page
      'downloadSuperResolutionModelHint': 'Githubからモデルをダウンロード',
      'modelDirectoryPath': 'モデルディレクトリパス',
      'upSamplingScale': 'アップサンプリングスケール',
      'modelType': 'モデルを選択',
      'x4plusHint': 'より多くのスペースを使用しますが、多くの場合より高速です',
      'x4plusAnimeHint': 'より少ないスペースを使用しますが、多くの場合より低速です',
      'enable4OnlineReading': 'オンライン読書中に自動処理',

      /// download page
      'local': 'ローカル',
      'delete': '削除',
      'deleteTask': 'タスクのみ削除',
      'deleteTaskAndImages': 'タスクと画像を削除',
      'reDownload': '再ダウンロード',
      'unlocking': 'アンロック中',
      'unlocked': 'アンロック済み',
      'parsingDownloadPageUrl': '解析Ⅰ',
      'parsedDownloadPageUrl': '解析Ⅰ',
      'parsingDownloadUrl': '解析Ⅱ',
      'parsedDownloadUrl': '解析Ⅱ',
      'waitingIsolate': '待機中',
      'downloaded': 'ダウンロード済み',
      'downloadFailed': 'ダウンロード失敗',
      'unpacking': '解凍中',
      'completed': '完了',
      'needReUnlock': '再アンロックが必要',
      'reUnlock': '再アンロック',
      'reUnlockHint': '注意！再アンロックにはこのアーカイブを再購入する必要があります。',
      'downloadHelpInfo': 'ダウンロードできない場合やログにテーブルが存在しないなどのエラーがある場合は、現在のアプリをアンインストールして再インストールしてください。',
      'localGalleryHelpInfo': 'JHenTaiでダウンロードしていないギャラリーを読み込みます。ダウンロード設定->追加ギャラリースキャンパスに設定を追加してから更新してください。',
      'localGalleryHelpInfo4iOSAndMacOS': 'JHenTaiでダウンロードしていないギャラリーを読み込みます。ギャラリーをデフォルトのダウンロードパスに置いてから更新してください',
      'deleteLocalGalleryHint': 'ローカルファイルを削除します',
      'priority': '優先度',
      'highest': '最高',
      'default': 'デフォルト',
      'newGalleryCount': '新しいギャラリー数',
      'changePriority': '優先度を変更',
      'changeGroup': 'グループを変更',
      'chooseGroup': 'グループを選択',
      'renameGroup': 'グループ名を変更',
      'deleteGroup': 'グループを削除',
      'existingGroup': '既存のグループ',
      'groupName': 'グループ名',
      'drag2sort': 'ドラッグして並び替え',
      'switch2GridMode': 'グリッドモードに切替',
      'switch2ListMode': 'リストモードに切替',
      'multiSelect': '複数選択',
      'multiSelectHint': 'タップして選択',
      'resumeAllTasks': 'すべてのタスクを再開',
      'pauseAllTasks': 'すべてのタスクを一時停止',
      'requireDownloadComplete': 'ダウンロード完了が必要',
      'operationHasCompleted': '操作が完了しました',
      'operationInProgress': '操作が進行中です',
      'startProcess': 'プロセスを開始',
      'multiReDownloadHint': '選択したすべてのギャラリーを再ダウンロードします。',
      'multiChangeGroupHint': '選択したすべてのギャラリーのグループを変更します。',
      'multiDeleteHint': '選択したすべてのギャラリーを削除します。',
      'blankImageHint': '画像のダウンロードが空の結果を返しました。再解析を試みます。',
      'peakHoursHint': 'ピーク時間帯にオリジナルファイルをダウンロードするにはGPが必要ですが、不足しているためダウンロードが一時停止されました。',
      'oldGalleryHint': 'このギャラリーのオリジナルファイルをダウンロードするにはGPが必要ですが、不足しています。',
      'exceedLimitHint': '画像制限に達し、ダウンロードクオータを購入するのに十分なGPがありません。',
      'deleteUpdatingDependentHint': '別のギャラリーの更新が現在のギャラリーに依存しています。更新完了後に削除することをお勧めします。',
      'migrateToDownload': '「ダウンロード」に移行',
      'refresh': '更新',

      /// download search page
      'simpleSearch': 'シンプル',
      'regexSearch': '正規表現',

      /// search dialog
      'searchConfig': '検索設定',
      'addTabBar': 'タブバーを追加',
      'updateTabBar': 'タブバーを更新',
      'addQuickSearch': '追加',
      'updateQuickSearch': '更新',
      'filter': 'フィルター',
      'tabBarName': 'タブバー名',
      'quickSearchName': '名前',
      'pleaseInputValidName': '有効な名前を入力してください',
      'sameNameExists': '同じ名前が存在します',
      'sameConfigExists': '同じ設定が存在します',
      'searchType': '検索タイプ',
      'popular': '人気',
      'ranklist': 'ランクリスト',
      'ranklistBoard': 'ランクリスト',
      'watched': '監視中',
      'history': '履歴',
      'keyword': 'キーワード',
      'orderBy': '並び順',
      'favoritedTime': 'お気に入り追加日時',
      'publishedTime': '公開日時',
      'backspace2DeleteTag': 'バックスペースでタグを削除',
      'searchGalleryName': 'ギャラリー名で検索',
      'searchGalleryTags': 'ギャラリータグで検索',
      'searchGalleryDescription': 'ギャラリー説明で検索',
      'onlySearchExpungedGalleries': '削除されたギャラリーのみ検索',
      'onlyShowGalleriesWithTorrents': 'トレントのあるギャラリーのみ表示',
      'searchLowPowerTags': '低評価タグを検索',
      'searchDownVotedTags': '反対投票タグを検索',
      'pageAtLeast': '最低ページ数',
      'pageAtMost': '最大ページ数',
      'pagesBetween': 'ページ範囲',
      'pageRangeSelectHint': 'min <= 1000、max >= 10\nmin/max <= 0.8、max-min >= 20',
      'to': 'から',
      'minimumRating': '最低評価',
      'disableFilterForLanguage': '言語フィルターを無効化',
      'disableFilterForUploader': 'アップロード者フィルターを無効化',
      'disableFilterForTags': 'タグフィルターを無効化',
      'searchName': '名前で検索',
      'searchTags': 'タグで検索',
      'searchNote': 'メモで検索',
      'allTime': 'すべて',
      'year': '年',
      'month': '月',
      'day': '日',
      'favoriteHint': '''
修飾子:
tag： タグで検索
title： タイトルで検索
comment： コメントで検索
favnote： メモで検索
      ''',

      /// popular page
      'getPopularListFailed': '人気リストの取得失敗',

      /// ranklist page
      'getRanklistFailed': 'ランクリストの取得失敗',
      'getSomeOfGallerysFailed': '一部のギャラリーの取得失敗',

      /// history page
      'getHistoryGallerysFailed': '一部の履歴ギャラリーの取得失敗',

      /// search page
      'search': '検索',
      'searchFailed': '検索失敗',
      'fileSearchFailed': 'ファイル検索失敗',
      'tab': 'タブ',
      'openGallery': 'ギャラリーを開く',
      'tapChip2Delete': 'チップをタップして削除\nボタンを長押しですべて削除',
      'accurateCountTemplate': '%s件の結果',
      'hundredsOfCountTemplate': '数百件の結果',
      'thousandsOfCountTemplate': '数千件の結果',

      /// about page
      'author': '作者',
      'Q&A': 'Q&A',
      'telegramHint': 'githubで質問することもできます',

      /// download setting page
      'downloadPath': 'ダウンロードパス',
      'changeDownloadPathHint': '長押しで変更（SDカードやシステムパスは使用しないでください）。ダウンロード済みのギャラリーを自動的にコピーし、古いファイルを保持します。エラーが発生した場合はリセットを試してください。',
      'resetDownloadPath': 'ダウンロードパスをリセット',
      'extraGalleryScanPath': '追加ギャラリースキャンパス',
      'extraGalleryScanPathHint': 'ローカルギャラリーのスキャンと読み込み',
      'singleImageSavePath': '単一画像の保存パス',
      'downloadOriginalImage': 'オリジナル画像',
      'downloadOriginalImageByDefault': 'デフォルトでオリジナル画像を選択',
      'originalImage': 'オリジナル',
      'resampleImage': 'リサンプル',
      'defaultGalleryGroup': 'デフォルトギャラリーグループ',
      'defaultArchiveGroup': 'デフォルトアーカイブグループ',
      'never': 'しない',
      'manual': '手動',
      'always': '常に',
      'longPress2Reset': '長押しでリセット',
      'needPermissionToChangeDownloadPath': 'ダウンロードパスの変更に権限が必要です',
      'invalidPath': '無効なパス。SDカード、システムパス、またはルートパスの使用は避けてください。',
      'downloadTaskConcurrency': 'ダウンロード並行数',
      'needRestart': '再起動が必要',
      'speedLimit': '速度制限',
      'speedLimitHint': '速すぎないようにしてください',
      'per': '毎',
      'images': '枚',
      'downloadTimeout': 'ダウンロードタイムアウト',
      'downloadAllGallerysOfSamePriority': '同じ優先度のすべてのギャラリーをダウンロード',
      'downloadAllGallerysOfSamePriorityHint': 'デフォルトでは最高優先度の1グループで同時に1つのギャラリーのみダウンロード',
      'alwaysUseDefaultGroup': '常にデフォルトグループを使用',
      'enableStoreMetadataForRestore': '復元用メタデータの保存を有効化',
      'enableStoreMetadataForRestoreHint': 'これを無効にするとダウンロードタスクを復元できません',
      'archiveDownloadIsolateCount': 'アーカイブダウンロードスレッド数',
      'archiveDownloadIsolateCountHint': 'すべてのタスクのスレッド合計が10未満である必要があります。そうでないとダウンロードに失敗します',
      'manageArchiveDownloadConcurrency': 'アーカイブダウンロード並行性を管理',
      'manageArchiveDownloadConcurrencyHint': 'アーカイブはダウンロードするのに十分なスレッドができるまで待機します',
      'deleteArchiveFileAfterDownload': 'ダウンロード後にアーカイブ.zipファイルを削除',
      'restoreDownloadTasks': 'ダウンロードタスクを復元',
      'restoreDownloadTasksHint': 'メタデータからダウンロードタスクを復元',
      'restoreDownloadTasksSuccess': 'ダウンロードタスクの復元成功',
      'restoredCount': '復元されたタスク数',
      'restoredGalleryCount': '復元されたギャラリー数',
      'restoredArchiveCount': '復元されたアーカイブ数',
      'restoreTasksAutomatically': '自動的にタスクを復元',
      'restoreTasksAutomaticallyHint': 'アプリ起動時に自動的にタスクを復元',
      'brokenDownloadPathHint': 'ダウンロードパスが壊れているようです。ダウンロード機能が無効になる可能性があります',
      'brokenExtraScanPathHint': 'デフォルトのローカルギャラリーパスが壊れているようです。ローカルギャラリーが認識されない可能性があります',
      'useJH2UpdateGallery': 'JHサーバーを使用してギャラリーの更新を高速化',

      /// archive bot settings
      'archiveBotSettings': 'Archive Bot設定',
      'archiveBotSettingsHint': 'Archive Botを使用してアーカイブリンクを無料で取得',
      'apiSetting': 'API設定',
      'apiAddress': 'アドレス',
      'apiKey': 'キー',
      'apiKeyHint': 'Telegram botから取得したキーを入力してください',
      'dailyCheckin': 'デイリーチェックイン',
      'currentBalance': '現在のGP残高',
      'checkBalanceFailed': 'GP残高の取得失敗',
      'checkInFailed': 'チェックイン失敗',
      'checkInSuccess': 'チェックイン成功',
      'checkInSuccessHint': '取得GP: %s、現在の合計GP: %s。',
      'pauseDownloadByInvalidArchiveBotKey': 'Archive Botの設定が無効です。ダウンロードが一時停止されました',
      'chooseArchiveParseSource': '解析ソースを変更',
      'official': '公式',
      'archiveBot': 'Archive Bot',
      'changeParseSource2Official': '解析ソースを公式に変更',
      'changeParseSource2Bot': '解析ソースをArchive Botに変更',
      'invalidParam': '無効なパラメータ',
      'invalidApiKey': '無効なAPIキー',
      'banned': 'あなたはBANされました',
      'fetchGalleryInfoFailed': 'ギャラリー情報の取得失敗',
      'insufficientGP': 'GPが不足しています',
      'parseFailed': '解析失敗',
      'checkedIn': '本日はすでにチェックイン済みです',
      'serverError': 'Archive Botの内部エラー',
      'useProxyServer': 'JHenTaiプロキシサーバーを使用',
      'useProxyServerHint': 'JHenTaiサーバーを通じてリクエストをルーティング',

      /// password setting dialog
      'setPasswordHint': 'パスワードを入力してください',
      'confirmPasswordHint': 'もう一度パスワードを入力してください',
      'passwordNotMatchHint': 'パスワードが一致しません。もう一度試してください',

      /// cloud setting page
      'serverCondition': 'サーバー状態',
      'configSync': '設定同期',
      'configSyncHint': '設定データをクラウドに保存（最大50件）',
      'upload2cloud': 'クラウドにアップロード',
      'upload2cloudHint': '現在のローカル設定をアップロード',
      'tap2upload': 'タップしてアップロード',
      'copyIdentificationCodeSuccess': 'アップロード成功。識別コードがコピーされました',
      'copyShareCode': '共有コードをコピー',
      'import': 'インポート',
      'save2Local': 'ローカルに保存',
      'readIndexRecord': '読書進捗',
      'quickSearch': 'クイック検索設定',
      'blockRules': 'ブロックルール',
      'searchHistory': '検索履歴',
      'galleryHistory': 'ギャラリー履歴',

      /// block rule page
      'configureBlockRuleFailed': 'ブロックルールの設定失敗',
      'removeBlockRuleFailed': 'ブロックルールの削除失敗',
      'inputNumberHint': '正しい数値を入力してください',
      'inputRegexHint': '正しい正規表現を入力してください',
      'useBuiltInBlockedUsers': '組み込みユーザーブロックリストを有効化',
      'useBuiltInBlockedUsersHint': 'ブロックリストのユーザーのギャラリーコメントをフィルタリング',
      'blockingRules': 'ブロックルール',
      'blockingRulesHint': 'ギャラリーとコメントの追加ブロックルール',
      'blockingTarget': 'ブロック対象',
      'blockingAttribute': 'ブロック属性',
      'blockingPattern': 'ブロックパターン',
      'blockingExpression': 'ブロック式',
      'contain': '含む',
      'notContain': '含まない',
      'regex': '正規表現',
      'comment': 'コメント',
      'tag': 'タグ',
      'userId': 'ユーザーID',
      'content': '内容',
      'incompleteInformation': '情報が不完全です',
      'noBlockingRuleHint': '少なくとも1つのルールを追加してください',
      'notSameBlockingRuleTargetHint': 'すべてのサブルールは同じブロック対象を持つ必要があります',
      'blockingRuleHelp': '''
ブロック対象: リストページのギャラリーをフィルタリング、または詳細ページのコメントをフィルタリング。同じルール下のすべてのサブルールは同じブロック対象を持つ必要があります。
ブロック属性: ブロックするルールを書くための対象の属性を指定します。
ブロックパターン: 複雑なシナリオには正規表現を使用します。
ブロック式: 単純な文字列または正規表現。

注1: 異なるルールはOR（||）の関係にあり、同じルール下のすべてのサブルールはAND（&&）の関係にあります。
注2: タグをブロックする場合、ルールはギャラリーの各タグをチェックします。式は単一のタグに対して書く必要があります。
注3: タグをブロックする場合、'='ルールを使用する際はネームスペース付きのフルタグを指定する必要があります。
注4: e-hentaiで「Extended」などすべてのタグを表示できるギャラリーレイアウトを使用する必要があります。そうでないと一部のギャラリーが正しくフィルタリングされない場合があります。

例1: 「yaoi」タグがあり「tomgirl」タグがないギャラリーをブロック————ギャラリータグ 含む male:yaoi && ギャラリータグ 含まない male:tomgirl
例2: スコアが10以下のコメントをブロック————コメントスコア <= 10
      ''',

      /// quick search page
      'quickSearch': 'クイック検索',

      /// dashboard page
      'seeAll': 'すべて',
      'newest': '最新',

      /// torrent dialog
      'outdated': '古い',

      /// tag dialog
      'warningImageHint': 'R18G画像、タップして表示',

      /// tagSet dialog
      'chooseTagSet': 'タグセットを選択',

      /// tag namespace
      'language': '言語',
      'artist': 'アーティスト',
      'character': 'キャラクター',
      'female': '女性',
      'male': '男性',
      'parody': 'パロディ',
      'group': 'グループ',
      'mixed': '混合',
      'Coser': 'コサー',
      'cosplayer': 'コスプレイヤー',
      'reclass': '再分類',
      'temp': '一時',
      'other': 'その他',
    };
  }
}
