import 'dart:core';

class ko_KR {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': '예',
      'no': '아니요',
      'cancel': "취소",
      'OK': "확인",
      'reset': "초기화",
      'success': "성공",
      'error': "오류",
      'failed': "실패",
      'reload': '재실행',
      'noMoreData': '더 이상 데이터가 없음',
      'noData': '데이터 없음',
      'operationFailed': '작업 실패',
      'needLoginToOperate': '로그인이 필요한 작업',
      'hasCopiedToClipboard': "클립보드에 복사됨",
      'networkError': "네트워크 오류, 재시도 클릭",
      'systemError': "시스템 오류",
      'invalid': "유효하지 않음",
      'internalError': "내부 오류",
      'you': '사용자',
      'retryHint': '새로고침 후 다시 시도하세요.',
      'stop': '멈춤',
      'attention': '경고',
      'jump': '건너뛰기',
      'deleteAll': '전체 삭제',
      'connectionTimeoutHint': '네트워크 연결 타임아웃',
      'receiveDataTimeoutHint': '데이터 수신 타임아웃',
      'archiveError': '아카이브 다운로드 오류',
      'edit': '편집',

      'home': "홈",
      'gallery': "갤러리",
      'setting': '설정',

      /// schedule
      'dawnOfaNewDay': '새로운 하루가 밝았습니다!',
      'encounterMonster': '몬스터를 만났습니다!',
      'encounterMonsterHint': '클릭하여 HentaiVerse에서 싸우세요.',

      /// unlock page
      'localizedReason': '입장하려면 인증을 진행하세요.',
      'tap2Auth': '인증하려면 터치하세요.',
      'passwordErrorHint': '비밀번호 오류, 다시 시도하세요.',

      /// start page
      'TapAgainToExit': '종료하려면 다시 한번 누르세요.',

      /// update dialog
      'availableUpdate': '사용 가능한 업데이트가 있습니다!',
      'LatestVersion': '최신 버전',
      'CurrentVersion': '현재 버전',
      'check': '확인: ',
      'dismiss': '무시',

      /// login page
      'login': '로그인',
      'notLoggedIn': '로그인',
      'logout': '로그아웃',
      'passwordLogin': '비밀번호 로그인',
      'cookieLogin': '쿠키 로그인',
      'useWebview': 'Webview 사용',
      'skipCookieVerification': '확인 건너뛰기',
      'youHaveLoggedInAs': '환영합니다:   ',
      'cookieIsBlack': '쿠키가 비었습니다',
      'cookieFormatError': '쿠키 형식이 잘못됐습니다.',
      'invalidCookie': '로그인 실패 혹은 쿠키가 유효하지 않습니다.',
      'loginFail': '로그인 실패',
      'userName': '사용자명',
      'EHUser': 'EH 사용자',
      'password': '비밀번호',
      'needCaptcha': 'captcha가 필요합니다, 쿠키 혹은 웹으로 로그인을 하세요.',
      'userNameOrPasswordMismatch': '사용자명 혹은 비밀번호가 맞지 않습니다.',
      'copyCookies': '쿠키 복사',
      'tap2Copy': '터치해 복사하기',
      'webLoginIsDisabled': '데스크톱에서 웹 로그인을 할 수 없습니다.',
      'loginSuccess': '로그인 성공',
      'userNameFormHint': '슬픈 판다가 나온다면 쿠키로 시도하세요.',
      'tap2Login': '로그인',
      'parse': '파싱',
      'igneousHint': 'igneous(EX 필요)',
      'refreshIgneousFailed': 'Igneous 새로고침 실패',

      /// request
      'sadPanda': 'Sad Panda(no data). Refer: https://github.com/jiangtian616/JHenTai/wiki/%EC%9E%90%EC%A3%BC-%ED%95%98%EB%8A%94-%EC%A7%88%EB%AC%B8',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/%EC%9E%90%EC%A3%BC-%ED%95%98%EB%8A%94-%EC%A7%88%EB%AC%B8',

      /// gallery card
      'filtered': '필터됨',

      /// gallery page
      'getGallerysFailed': "갤러리 가져오기 실패",
      'refreshGalleryFailed': '갤러리 새로고침 실패',
      'tabBarSetting': '탭 바 설정',
      'jumpPageTo': '페이지 이동: ',
      'range': '범위',
      'current': '현재',
      'galleryUrlDetected': '클립보드에서 갤러리 URL을 찾았습니다.',
      'galleryUrlDetectedHint': '터치해 상세 페이지 들어가기',

      /// details page
      'read': '보기',
      'download': '다운로드',
      'favorite': '즐겨찾기',
      'rating': '점수',
      'torrent': '토렌트',
      'archive': '아카이브',
      'statistic': '통계',
      'similar': '비슷한 내용',
      'downloading': "다운로드 중",
      'resume': "이어서 하기",
      'pause': '일시 정지',
      'finished': '완료',
      'update': '업데이트',
      'submit': '등록',
      'chooseFavorite': '즐겨찾기 선택',
      'asYourDefault': '기본으로 설정',
      'Note': '메모',
      'addNoteHint': '메모를 추가하기 전에 슬롯을 선택하세요',
      'uploader': '업로더',
      'allComments': '모든 댓글',
      'noComments': '댓글 없음',
      'lastEditedOn': '최근 수정일: ',
      'getGalleryDetailFailed': '갤러리 세부 정보 가져오기 실패',
      'cloudflare403': 'Cloudflare에 의해 네트워크 요청이 차단되었습니다. 네트워크를 전환하거나 다른 로그인 방법을 사용해 보세요.',
      'invisible2User': '이 갤러리는 사용자에게 보이지 않습니다.',
      'invisibleHints': '이 갤러리는 삭제되었거나 사용할 수 없습니다.',
      'copyRightHints': '이 갤러리는 다음 저작권자로 인해 사용할 수 없음: ',
      'refreshGalleryDetailsFailed': '갤러리 세부 정보 새로고침 실패',
      'failToGetThumbnails': "섬네일 가져오기 실패",
      'favoriteGallerySuccess': "즐겨찾기 저장 성공",
      'favoriteGalleryFailed': "즐겨찾기 저장 실패",
      'removeFavoriteSuccess': "즐겨찾기 제거 성공",
      'removeFavoriteFailed': "즐겨찾기 제거 실패",
      'getGalleryFavoriteInfoFailed': '갤러리 즐겨찾기 정보 가져오기 실패',
      'favoriteNoteSlotFullHint': '즐겨찾기 메모 슬롯이 가득 찼습니다. 먼저 일부 메모를 삭제하세요.',
      'ratingSuccess': '평가 성공',
      'ratingFailed': '평가 실패',
      'voteTagFailed': '태그 투표 실패',
      'beginToDownload': '다운로드 시작',
      'resumeDownload': '계속 다운로드',
      'pauseDownload': '다운로드 일시 정지',
      'addNewTagSetSuccess': '태그 추가 성공',
      'addNewWatchedTagSetSuccess': '강조 태그 추가 성공',
      'addNewHiddenTagSetSuccess': '숨김 태그 추가 성공',
      'addNewTagSetSuccessHint': '\'설정 → EH → 나의 태그\'에서 사용자의 태그를 확인할 수 있습니다.',
      'addNewTagSetFailed': '태그 추가 실패',
      'VisitorStatistics': '방문자 통계',
      'invisible2UserWithoutDonation': '이 갤러리 통계는 기부하지 않은 사용자는 볼 수 없습니다.',
      'getGalleryStatisticsFailed': '갤러리 통계 가져오기 실패',
      'totalVisits': '총방문자 수',
      'visits': '방문자 수',
      'imageAccesses': '이미지 방문',
      'period': '기간',
      'ranking': '순위',
      'score': '점수',
      'NotOnTheList': '순위권 밖',
      'getGalleryArchiveFailed': '갤러리 아카이브 가져오기 실패',
      'parseGalleryArchiveFailed': '설정 불러오기 실패, e-hentai에서 [Archiver Settings]가 [Manual Select, Manual Start (Default)]인지 확인하세요.',
      'original': '원본',
      'resample': '압축',
      'beginToDownloadArchive': '아카이브 다운로드 시작',
      'beginToDownloadArchiveHint': '다운로드 → 아카이브에서 진행 상황을 확인할 수 있습니다.',
      'updateGalleryError': '갤러리 업데이트 오류',
      'thisGalleryHasANewVersion': '이 갤러리는 새 버전이 있습니다.',
      'hasUpdated': '업데이트됨',
      'unpackingArchiveError': '아카이브 압축 해제 오류',
      'failedToDealWith': '처리 실패',
      'hasDownloaded': '다운로드 완료',
      '410Hints': '이 아카이브에서 다운로드한 용량이 너무 많아서 다시 시작하려면 아카이브의 잠금을 다시 해제해야 합니다.',
      '429Hints': '다운로드 요청이 너무 많습니다! 잠시 후 다시 시도하세요.',
      'getUnpackedImagesFailedMsg': 'JHenTai에서 이 아카이브 이미지를 가져올 수 없습니다. 로컬 파일을 확인하세요.',
      'getGalleryTorrentsFailed': '토렌트 불러오기 실패',
      'chooseArchive': '아카이브 선택',
      'tagSetExceedLimit': '저장된 태그 수가 최대치에 도달해서 더 추가할 수 없습니다.',
      'useTranslation': '번역 사용',
      'addTagSuccess': '태그 추가 성공',
      'addTagFailed': '태그 추가 실패',
      'parentGallery': '상위 갤러리',
      'blockUploaderLocally': '사용자 로컬 차단',
      'block': '차단',

      /// detail dialog
      'galleryUrl': '갤러리 주소',
      'title': '제목',
      'japaneseTitle': '일본어 제목',
      'category': '카테고리',
      'publishTime': '게재 시간',
      'pageCount': '페이지 수',
      'favoriteCount': '즐겨찾기 수',
      'ratingCount': '평가자 수',

      /// comment page
      'newComment': '댓글 추가',
      'updateComment': '댓글 수정',
      'commentTooShort': '내용이 너무 짧습니다.',
      'sendCommentFailed': '댓글 달기 실패',
      'voteCommentFailed': '댓글 평가 실패',
      'voteCommentFailedHint': '맨 처음 상세 페이지에서 아래로 내려 새로고침을 시도하세요',
      'unknownUser': '알 수 없는 사용자',
      'atLeast3Characters': '3글자 이상',
      'noJHenTaiHints': 'JHenTai로 열 수 없습니다. 먼저 앱을 설치하세요.',
      'blockUser': '사용자 차단',

      /// EHImage
      'reloadImage': "이미지 다시 불러오기",

      /// read page
      'parsingPage': "페이지 분석",
      'parsingURL': "주소 분석",
      'parsePageFailed': "페이지 분석 실패, 재시도 클릭",
      'parseURLFailed': "주소 분석 실패, 길게 눌러 재시도",
      'loading': "로딩",
      'paused': '일시 정지',
      'exceedImageLimits': "이미지 한도 초과",
      'ehServerError': 'EH 서버 오류가 발생했습니다.',
      'unsupportedImagePageStyle': "JHenTai는 Multi-Page Viewer(MPV)를 지원하지 않습니다. e-hentai.org에서 기본값 스타일로 해주세요.",
      'toNext': '다음',
      'toPrev': '이전',
      'back': '뒤로',
      'toggleMenu': '토글 메뉴',
      'share': '공유',
      'save': '사진으로 저장',

      /// setting page
      'account': '계정',
      'EH': 'EH',
      'style': '스타일',
      'preference': '일반',
      'network': '네트워크',
      'performance': '성능',
      'mouseWheel': '마우스 휠',
      'advanced': '고급',
      'cloud': '클라우드',
      'security': '보안',
      'about': '앱 정보',
      'accountSetting': '계정 설정',
      'styleSetting': '스타일 설정',
      'advancedSetting': '고급 설정',
      'securitySetting': '보안 설정',
      'ehSetting': 'EH 사이트 설정',
      'readSetting': '뷰어 설정',
      'preferenceSetting': '일반 설정',
      'downloadSetting': '다운로드 설정',
      'networkSetting': '네트워크 설정',
      'performanceSetting': '성능 설정',
      'mouseWheelSetting': '마우스 휠 설정',

      /// eh setting page
      'site': '사이트',
      'redirect2Eh': '사용 가능하면 EH로 재요청',
      'redirect2EhHint': '더 나은 네트워크 성능을 위해 먼저 EH 사이트에서 갤러리 상세 페이지를 로드하세요.',
      'redirectAllGallery': '모든 갤러리를 EH로 리다이렉트',
      'imDonorHint': '후원자라면 이 기능을 켜서 EX 사이트의 갤러리에 접근하는 데 도움을 받으세요.',
      'profileSetting': '프로필 설정',
      'chooseProfileHint': 'JHenTai에서 사용할 프로필을 선택하세요.',
      'siteSetting': '사이트 내부 설정',
      'siteSettingHint': 'e-hentai에서 사이트 설정 편집',
      'showCookie': '쿠키 정보',
      'redirect2EH': '사용 가능하면 EH 사이트로 재요청',
      'redirect2Hints': 'EH 사이트 분석을 먼저 합니다.',
      'pleaseLogInToOperate': '실행하려면 로그인하세요',
      'imageLimits': '이미지 할당량',
      'resetCost': '길게 눌러 초기화, 비용',
      'assets': '자산',
      'isNotDonator': '후원자가 아닙니다',
      'fetchImageQuotaFailed': '이미지 할당량 가져오기 실패',

      /// tag setting page
      'myTags': '나의 태그',
      'myTagsHint': '강조하거나 숨기고 싶은 태그를 관리',
      'localTags': '로컬 태그',
      'localTagsHint': '추가 필터 태그',
      'localTagsHint2': '이 태그가 있는 갤러리는 숨겨집니다.',
      'addLocalTags': '태그 추가',
      'hidden': '숨김',
      'nope': '없음',
      'getTagSetFailed': '태그 목록 불러오기 실패',
      'updateTagSetFailed': '태그 목록 수정 실패',
      'updateTagFailed': '태그 목록 수정 실패',
      'deleteTagSuccess': '태그 목록 삭제 성공',
      'deleteTagFailed': '태그 목록 삭제 실패',
      'addLocalTagHint': '새 태그를 추가하려면 검색하세요.',

      /// Profile Setting page
      'selectedProfile': '선택된 프로필',
      'resetIfSwitchSite': '사이트 전환 시 초기화됩니다',

      /// add host mapping dialog
      'addHostMapping': '호스트 매핑 추가',

      /// Layout
      'layoutMode': '레이아웃 모드',
      'mobileLayoutV2Name': '모바일',
      'mobileLayoutV2Desc': '단일 리스트',
      'mobileLayoutName': '모바일(구형)',
      'mobileLayoutDesc': '지원 중지',
      'tabletLayoutV2Name': '태블릿',
      'tabletLayoutV2Desc': '이중 리스트',
      'tabletLayoutName': '태블릿(구형)',
      'tabletLayoutDesc': '지원 중지',
      'desktopLayoutName': '데스크톱',
      'desktopLayoutDesc': '왼쪽 탭 바가 있는 이중 리스트(키보드 지원)',

      /// style setting page
      'enableTagZHTranslation': '태그를 중국어로 변환',
      'version': '버전',
      'downloadTagTranslationHint': '데이터 다운로드 중...: ',
      'zhTagSearchOrderOptimization': '중국어 태그 자동완성 정렬 규칙',
      'zhTagSearchOrderOptimizationHint': '기본 지능형 정렬, 활성화 시 빈도 기준 정렬',
      'themeMode': '테마 모드',
      'dark': '어두운 모드',
      'light': '밝은 모드',
      'followSystem': '시스템에 따라',
      'themeColor': '테마 색상',
      'listStyle': '갤러리 리스트 스타일 (기본값)',
      'flat': '플랫',
      'flatWithoutTags': '플랫(태그 없음)',
      'listWithoutTags': '카드(태그 없음)',
      'listWithTags': '카드',
      'waterfallFlowSmall': '폭포형 (소)',
      'waterfallFlowMedium': '폭포형 (중)',
      'waterfallFlowBig': '폭포형 (대)',
      'crossAxisCountInWaterFallFlow': '폭포의 세로줄 개수',
      'pageListStyle': '갤러리 리스트 스타일 (개별)',
      'crossAxisCountInGridDownloadPageForGroup': '다운로드 페이지 그리드 정렬 세로줄 개수(폴더)',
      'crossAxisCountInGridDownloadPageForGallery': '다운로드 페이지 그리드 정렬 세로줄 개수(폴더 내부)',
      'crossAxisCountInDetailPage': '상세 페이지 썸네일 열 수',
      'global': '기본값',
      'auto': '자동',
      'moveCover2RightSide': '섬네일을 오른쪽으로 배치',
      'coverStyle': '커버 스타일',
      'cover': '커버',
      'adaptive': '적응형',
      'simpleDashboardMode': '간단한 홈 화면',
      'simpleDashboardModeHint': '랭킹과 인기 항목 숨기기',
      'hideBottomBar': '하단 메뉴 숨기기',
      'hideScroll2TopButton': '맨 위로 스크롤 버튼 숨기기',
      'whenScrollUp': '위로 스크롤 시',
      'whenScrollDown': '아래로 스크롤 시',
      'preloadGalleryCover': '갤러리 커버 미리 로드',
      'preloadGalleryCoverHint': '아직 표시되지 않은 갤러리의 커버를 미리 로드합니다',
      'enableSwipeBackGesture': '스와이프 제스처로 뒤로 가기 활성화',
      'enableLeftMenuDrawerGesture': '좌측 서랍 메뉴 제스처로 열기 활성화',
      'enableQuickSearchDrawerGesture': '우측 빠른 검색 메뉴 제스처로 열기 활성화',
      'drawerGestureEdgeWidth': '드로어 제스처 가장자리 너비',
      'alwaysShowScroll2TopButton': '맨 위로 가기 버튼 항상 보이기',
      'enableDefaultFavorite': '기본 즐겨찾기 활성화',
      'enableDefaultFavoriteHint': '길게 눌러 다시 선택',
      'enableDefaultTagSet': '기본 태그 세트 활성화',
      'enableDefaultTagSetHint': '길게 눌러 다시 선택',
      'disableDefaultTagSetHint': '수동으로 선택',
      'launchInFullScreen': '전체 화면으로 시작',
      'launchInFullScreenHint': 'F11로 수동 전환',
      'disableDefaultFavoriteHint': '수동으로 선택',
      'searchBehaviour': '검색 동작',
      'inheritAll': '전체 상속',
      'inheritAllHint': '다음 검색에 마지막 검색 옵션 사용',
      'inheritPartially': '부분 상속',
      'inheritPartiallyHint': '다음 검색에 마지막 검색 옵션 사용(언어 및 카테고리 제외)',
      'none': '없음',
      'noneHint': '다음 검색에 기본 검색 옵션 사용',
      'showAllGalleryTitles': '모든 갤러리 제목 표시',
      'showAllGalleryTitlesHint': '사용 가능한 경우 원본 및 일본어 제목 모두 표시',
      'showGalleryTagVoteStatus': '갤러리 태그 투표 상태 표시',
      'showGalleryTagVoteStatusHint': '신뢰도, 회의론, 부정확 포함',
      'showComments': '댓글 표시',
      'showAllComments': '모든 댓글 표시',
      'showAllCommentsHint': '기본적으로 점수 상위 45개와 최신 5개 댓글만 표시됩니다',
      'addTag': '태그 추가',
      'addTagHint': '새 태그를 입력하세요. 쉼표로 구분',

      /// theme color setting page
      'preset': '프리셋',
      'custom': '커스텀',

      /// performance setting page
      'maxGalleryNum4Animation': '다운로드 페이지 목록 애니메이션 최대 갤러리 수',
      'maxGalleryNum4AnimationHint': '이 값보다 많은 갤러리를 가진 그룹의 애니메이션 비활성화(목록 스타일)',

      /// mouse wheel setting page
      'themeColorSettingHint': '라이트 모드와 다크 모드 각각에 다른 색을 지정합니다',
      'preview': '미리 보기',
      'wheelScrollSpeed': '휠 스크롤 속도',
      'ineffectiveInGalleryPage': '현재 갤러리 페이지에서 유효하지 않습니다.',

      /// advanced setting page
      'enableDomainFronting': '도메인 우회 활성화',
      'bypassSNIBlocking': 'SNI 우회 차단',
      'hostMapping': '호스트 매핑',
      'hostMappingHint': '도메인 프론팅에 사용됨',
      'proxyAddress': '프록시 주소',
      'proxyAddressHint': '프록시 서버를 사용한다면 정확하게 설정해야 합니다.',
      'saveSuccess': '저장 성공',
      'saveFailed': '저장 실패',
      'updateSuccess': '수정 성공',
      'connectTimeout': '연결 시간 초과',
      'receiveTimeout': '수신 시간 초과',
      'pageCacheMaxAge': '페이지 캐시의 수명 최대 시간',
      'pageCacheMaxAgeHint': '새로고침 페이지 별로 캐시를 업데이트할 수 있습니다.',
      'cacheImageExpireDuration': '이미지 캐시 만료 시간',
      'cacheImageExpireDurationHint': '앱 실행 후 이미지 캐시를 자동으로 삭제',
      'oneMinute': '1분',
      'tenMinute': '10분',
      'oneHour': '1시간',
      'oneDay': '1일',
      'threeDay': '3일',
      'enableLogging': '로깅 사용',
      'enableVerboseLogging': '상세 로깅 사용',
      'openLog': '로그 열기',
      'clearLogs': '로그 삭제',
      'clearImagesCache': '이미지 캐시 삭제',
      'longPress2Clear': '길게 눌러 삭제하기',
      'checkUpdateAfterLaunchingApp': '앱 실행 후 업데이트 확인',
      'checkClipboard': '클립보드에서 갤러리 주소 검사',
      'clearPageCache': '페이지 캐시 삭제',
      'clearSuccess': '삭제 완료',
      'superResolution': '초고해상도 이미지 생성',
      'stopSuperResolution': '초고해상도 이미지 생성 취소',
      'deleteSuperResolvedImage': '초고해상도 이미지 삭제',
      'superResolveOriginalImageHint': '원본 이미지 처리는 더 많은 시간과 공간, 성능을 사용합니다. 계속하시겠습니까?',
      'verityAppLinks4Android12': '앱 링크 확인(Android 12+)',
      'verityAppLinks4Android12Hint': 'Android 12+의 경우, JHenTai를 타사 앱에서 열기 위해 확인된 링크에 수동으로 링크를 추가해야 합니다',
      'noImageMode': '이미지 없음 모드',
      'exportData': '데이터 내보내기',
      'exportDataHint': '설정, 차단 규칙 및 기록 내보내기',
      'selectExportItems': '내보낼 항목 선택',
      'importData': '데이터 가져오기',
      'importDataHint': '최신 구성을 적용하기 위해 가져오기 후 앱이 자동으로 종료됩니다',

      /// host mapping page
      'hostDataSource': '기본적으로 변경할 필요는 없습니다.\n데이터 소스: https://dns.google/',

      /// proxy page
      'proxySetting': '프록시 설정',
      'proxyType': '프록시 프로토콜 타입',
      'systemProxy': '시스템',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRECT',
      'address': '주소',

      /// security setting page
      'enablePasswordAuth': '비밀번호 인증 사용',
      'enableBiometricAuth': '생체 인증 사용',
      'enableAuthOnResume': '앱 다시 열 때 인증 사용',
      'enableAuthOnResumeHints': '3초 후 인증 요구',
      'enableBlurBackgroundApp': '백그라운드로 전환할 때 페이지 블러 사용',
      'hideImagesInAlbum': '앨범에서 이미지 숨기기',
      'hideImagesInAlbumHints': '기본 다운로드 경로를 변경한 경우, .nomedia를 수동으로 생성해야 합니다',

      /// read setting page
      'enableImmersiveMode': '몰입형 모드 사용',
      'keepScreenAwakeWhenReading': '읽는 중에 화면 꺼짐 방지하기',
      'enableCustomReadBrightness': '읽기 중 사용자 지정 밝기 활성화',
      'spaceBetweenImages': '이미지 간격',
      'enableImmersiveHint': '시스템 바를 숨김',
      'enableImmersiveHint4Windows': '제목 표시줄 숨기기',
      'deviceOrientation': '기기 방향',
      'landscape': '가로',
      'portrait': '세로',
      'readDirection': '읽는 방향',
      'notchOptimization': '노치 최적화',
      'notchOptimizationHint': '노치와 상태 표시줄을 피하기 위해 첫 번째 이미지 전에 패딩 추가',
      'imageRegionWidthRatio': '이미지 영역 너비 비율',
      'gestureRegionWidthRatio': '제스처 영역 너비 비율',
      'useThirdPartyViewer': '커스텀 뷰어 사용',
      'thirdPartyViewerPath': '커스텀 뷰어 경로(실행 파일)',
      'showThumbnails': '섬네일 보기',
      'showStatusInfo': '하단에 상태 보기',
      'showScrollBar': '스크롤 바 표시',
      'autoModeInterval': '자동 넘기기 간격',
      'autoModeStyle': '자동 넘기기 스타일',
      'scroll': '스크롤',
      'turnPage': '넘기기',
      'top2bottomList': '위에서 아래로 (연속)',
      'left2rightSinglePage': '왼쪽에서 오른쪽 (단일 페이지)',
      'left2rightSinglePageFitWidth': '왼쪽에서 오른쪽 (너비 맞춤)',
      'right2leftSinglePage': '오른쪽에서 왼쪽 (단일 페이지)',
      'right2leftSinglePageFitWidth': '오른쪽에서 왼쪽 (너비 맞춤)',
      'left2rightDoubleColumn': '왼쪽에서 오른쪽 (이중 열)',
      'right2leftDoubleColumn': '오른쪽에서 왼쪽 (이중 열)',
      'left2rightList': '왼쪽에서 오른쪽 (연속)',
      'right2leftList': '오른쪽에서 왼쪽 (연속)',
      'enablePageTurnByVolumeKeys': '볼륨 키로 페이지 넘기기',
      'enablePageTurnAnime': '페이지 넘기기 애니메이션 사용',
      'enableDoubleTapToScaleUp': '두 번 터치해 확대 사용',
      'enableTapDragToScaleUp': '탭 드래그로 확대 활성화',
      'enableBottomMenu': '하단 메뉴 활성화',
      'reverseTurnPageDirection': '페이지 넘기기 방향 반전',
      'disableGestureWhenScrolling': '스크롤 중 제스처 비활성화',
      'disablePageTurningOnTap': '탭으로 페이지 넘기기 비활성화',
      'turnPageMode': '페이지 넘기기 모드',
      'turnPageModeHint': '화면 기준 혹은 이미지 기준',
      'enableImageMaxKilobytes': '이미지 압축 활성화',
      'imageMaxKilobytes': '이미지 최대 크기',
      'imageMaxKilobytesHint': '이 크기보다 큰 이미지는 압축됩니다',
      'image': '이미지 기준',
      'screen': '화면 기준',
      'preloadDistanceInOnlineMode': '미리 로드 거리(온라인)',
      'preloadDistanceInLocalMode': '미리 로드 거리(로컬)',
      'ScreenHeight': '화면',
      'preloadPageCount': '미리 로드 페이지 수(온라인)',
      'preloadPageCountInLocalMode': '미리 로드 페이지 수(로컬)',
      'continuousScroll': '길게 이어진 스크롤',
      'continuousScrollHint': '여러 이미지가 가로로 연결됨',
      'doubleColumn': '두 쪽으로 보기',
      'displayFirstPageAlone': '첫 페이지 단독 표시',
      'displayFirstPageAloneGlobally': '첫 페이지 단독 표시(전역)',
      'toggleFullScreen': '전체 화면 전환',
      'enableAutoScaleUp': '긴 이미지 자동 확대 사용',
      'enableAutoScaleUpHints': '이미지 너비를 화면 너비와 동일하게 함',

      /// preference setting page
      'showR18GImageDirectly': 'R18G 이미지 표시',
      'defaultTab': '기본 탭',
      'showUtcTime': '갤러리에 UTC 시간 표시',
      'showDawnInfo': '새벽 이벤트 표시',
      'showEncounterMonster': 'HentaiVerse 몬스터 조우 이벤트 표시',

      /// log page
      'logList': '로그 리스트',

      /// super resolution setting page
      'downloadSuperResolutionModelHint': 'Github에서 모델 다운로드 하기',
      'modelDirectoryPath': '모델 폴더 경로',
      'upSamplingScale': '샘플링 스케일 올리기',
      'modelType': '모델 선택하기',
      'x4plusHint': '용량이 크지만 소요 시간은 짧아집니다',
      'x4plusAnimeHint': '용량이 작지만 소요 시간은 늘어납니다.',
      'enable4OnlineReading': '온라인 읽기 중 자동 처리',

      /// download page
      'local': '로컬',
      'reDownload': '다시 다운로드',
      'delete': '삭제',
      'deleteTask': '리스트에서만 삭제',
      'deleteTaskAndImages': '리스트와 파일 모두 삭제',
      'unlocking': '압축 해제 중',
      'unlocked': '잠금 해제됨',
      'parsingDownloadPageUrl': '다운로드 Ⅰ',
      'parsedDownloadPageUrl': '다운로드 Ⅰ',
      'parsingDownloadUrl': '다운로드 Ⅱ',
      'parsedDownloadUrl': '다운로드 Ⅱ',
      'waitingIsolate': '대기 중',
      'downloaded': '다운로드 완료',
      'downloadFailed': '다운로드 실패',
      'unpacking': '압축 푸는 중',
      'completed': '완료',
      'needReUnlock': '다시 잠금 해제해야 합니다',
      'reUnlock': '다시 잠금 해제',
      'reUnlockHint': '주의! 다시 잠금 해제하려면 이 파일을 다시 구입해야 합니다.',
      'downloadHelpInfo': '다운로드 할 수 없고 로그에 DB 테이블이 없다면 앱을 삭제하고 다시 설치하세요.',
      'localGalleryHelpInfo': 'JHenTai에서 다운로드하지 않은 갤러리를 불러옵니다. 다운로드 설정 → 추가 갤러리 스캔 경로를 추가하고 새로고침하세요.',
      'localGalleryHelpInfo4iOSAndMacOS': 'JHenTai로 다운로드하지 않은 갤러리를 로드합니다. 갤러리를 기본 다운로드 경로에 넣고 새로고침하세요.',
      'deleteLocalGalleryHint': '사용자의 로컬 파일을 삭제합니다.',
      'priority': '우선순위',
      'highest': '높음',
      'default': '기본값',
      'newGalleryCount': '새로운 갤러리 수',
      'changePriority': '우선순위 변경',
      'changeGroup': '그룹 변경',
      'chooseGroup': '선택한 그룹',
      'renameGroup': '그룹 이름 변경',
      'deleteGroup': '그룹 삭제',
      'existingGroup': '기존 그룹',
      'groupName': '그룹 이름',
      'drag2sort': '드래그로 정렬',
      'switch2GridMode': '그리드 모드로 전환',
      'switch2ListMode': '리스트 모드로 전환',
      'multiSelect': '다중 선택',
      'multiSelectHint': '탭하여 선택',
      'resumeAllTasks': '모든 작업 이어서 시작',
      'pauseAllTasks': '모든 작업 일시 정지',
      'requireDownloadComplete': '다운로드가 완료되어야 합니다',
      'operationHasCompleted': '작업이 완료되었습니다',
      'operationInProgress': '작업이 진행 중입니다',
      'startProcess': '작업을 시작합니다',
      'multiReDownloadHint': '선택한 모든 갤러리를 다시 다운로드합니다.',
      'multiChangeGroupHint': '선택한 모든 갤러리의 그룹을 변경합니다.',
      'multiDeleteHint': '선택한 모든 갤러리를 삭제합니다.',
      'blankImageHint': '이미지 다운로드가 빈 결과를 반환했습니다. 다시 파싱을 시도합니다.',
      'peakHoursHint': '피크 시간대에 원본 파일을 다운로드하려면 GP가 필요하지만 충분하지 않아 다운로드가 일시 중지되었습니다.',
      'oldGalleryHint': '이 갤러리의 원본 파일을 다운로드하려면 GP가 필요하지만 충분하지 않습니다.',
      'exceedLimitHint': '이미지 한도에 도달했으며 다운로드 할당량을 구입하기 위한 충분한 GP가 없습니다.',
      'deleteUpdatingDependentHint': '다른 갤러리가 이 갤러리에 의존하고 있습니다.',
      'migrateToDownload': '「다운로드」로 이동',
      'refresh': '새로고침',

      /// download search page
      'simpleSearch': '단순',
      'regexSearch': '정규식',

      /// search dialog
      'searchConfig': '검색 설정',
      'addTabBar': '탭 추가',
      'updateTabBar': '탭 수정',
      'addQuickSearch': '추가',
      'updateQuickSearch': '수정',
      'filter': '필터',
      'tabBarName': '탭 이름',
      'quickSearchName': '이름',
      'pleaseInputValidName': '올바른 이름을 입력해 주세요.',
      'sameNameExists': '동일한 이름이 존재합니다.',
      'sameConfigExists': '동일한 설정이 존재합니다',
      'searchType': '검색 타입',
      'popular': '인기 있음',
      'ranklist': '순위',
      'ranklistBoard': '순위 리스트',
      'watched': '시청 기록',
      'history': '방문 기록',
      'keyword': '키워드',
      'orderBy': '정렬 기준',
      'favoritedTime': '즐겨찾기 시간',
      'publishedTime': '게시 시간',
      'backspace2DeleteTag': '백스페이스로 태그 삭제',
      'searchGalleryName': '갤러리 이름 검색',
      'searchGalleryTags': '갤러리 태그 검색',
      'searchGalleryDescription': '갤러리 설명 검색',
      'onlySearchExpungedGalleries': "삭제된 갤러리만 보기",
      'onlyShowGalleriesWithTorrents': '토렌트가 있는 갤러리만 보기',
      'searchLowPowerTags': '신뢰도 낮은 태그 검색',
      'searchDownVotedTags': '점수 낮은 태그 검색',
      'pageAtLeast': '최소 페이지',
      'pageAtMost': '최대 페이지',
      'pagesBetween': '페이지 사이',
      'pageRangeSelectHint': '최소 ≤ 1000, 최대 ≥ 10\n최소/최대 ≤ 0.8, 최대-최소 ≥ 20',
      'to': '~',
      'minimumRating': '최소 점수',
      'disableFilterForLanguage': '언어 필터 사용 안 함',
      'disableFilterForUploader': '업로더 필터 사용 안 함',
      'disableFilterForTags': '태그 필터 사용 안 함',
      'searchName': '이름 검색',
      'searchTags': '태그 검색',
      'searchNote': '주석 검색',
      'allTime': '전체',
      'year': '연도별',
      'month': '월별',
      'day': '일별',
      'favoriteHint': '한정자: 태그/제목/댓글/즐겨찾기 메모',

      /// popular page
      'getPopularListFailed': '인기 있는 리스트 불러오기 실패',

      /// ranklist page
      'getRanklistFailed': '순위 리스트 가져오기 실패',
      'getSomeOfGallerysFailed': '일부 갤러리 가져오기 실패',

      /// history page
      'getHistoryGallerysFailed': '일부 갤러리 기록 가져오기 실패',

      /// search page
      'search': '검색',
      'searchFailed': '검색 실패',
      'fileSearchFailed': '파일 검색 실패',
      'tab': '탭',
      'openGallery': '갤러리 열기',
      'tapChip2Delete': '칩을 탭하여 삭제\n버튼을 길게 눌러 전체 삭제',
      'accurateCountTemplate': '%s 개의 결과',
      'hundredsOfCountTemplate': '수백 개의 결과',
      'thousandsOfCountTemplate': '수천 개의 결과',

      /// about page
      'author': '제작자',
      'Q&A': 'Q&A',
      'telegramHint': '먼저 github에서 질문할 수 있습니다',

      /// download setting page
      'downloadPath': '다운로드 경로',
      'changeDownloadPathHint': '길게 눌러 변경(SD 카드 또는 시스템 경로는 사용하지 마세요). 다운로드한 갤러리를 자동으로 복사하고 오래된 파일은 보관합니다. 오류가 발생하면 초기화해 보세요.',
      'resetDownloadPath': '다운로드 경로 초기화',
      'extraGalleryScanPath': '추가 갤러리 스캔 경로',
      'extraGalleryScanPathHint': '로컬 갤러리를 스캔하고 불러오기 위함',
      'singleImageSavePath': '단일 이미지 저장 경로',
      'downloadOriginalImage': '원본 이미지',
      'downloadOriginalImageByDefault': '기본값으로 원본 이미지 선택',
      'originalImage': '원본',
      'resampleImage': '압축',
      'defaultGalleryGroup': '기본 갤러리 그룹',
      'defaultArchiveGroup': '기본 아카이브 그룹',
      'never': '영원히 안 함',
      'manual': '수동',
      'always': '항상 함',
      'longPress2Reset': '길게 눌러 초기화',
      'needPermissionToChangeDownloadPath': '다운로드 경로를 변경할 수 있는 권한이 필요합니다.',
      'invalidPath': '잘못된 경로입니다. SD 카드, 시스템 경로 또는 루트 경로는 사용하지 마세요.',
      'downloadTaskConcurrency': '동시 다운로드 수',
      'needRestart': '재시작 필요',
      'speedLimit': '속도 제한',
      'speedLimitHint': '너무 빠르게 설정하지 마세요',
      'per': '/ 시간: ',
      'images': '장 ',
      'downloadTimeout': '다운로드 시간 초과',
      'downloadAllGallerysOfSamePriority': '동일 우선순위의 모든 갤러리 다운로드',
      'downloadAllGallerysOfSamePriorityHint': '기본적으로 가장 높은 우선순위를 가진 1개의 그룹에서 동시에 1개의 갤러리만 다운로드',
      'alwaysUseDefaultGroup': '항상 기본 그룹 사용',
      'enableStoreMetadataForRestore': '복원을 위한 저장소 메타데이터 사용',
      'enableStoreMetadataForRestoreHint': '사용하지 않으면 다운로드 작업을 복원할 수 없습니다.',
      'archiveDownloadIsolateCount': '아카이브 다운로드 스레드 수',
      'archiveDownloadIsolateCountHint': '모든 작업의 스레드 합계는 10 미만이어야 합니다. 그렇지 않으면 다운로드가 실패합니다.',
      'manageArchiveDownloadConcurrency': '아카이브 다운로드 동시성 관리',
      'manageArchiveDownloadConcurrencyHint': '아카이브는 다운로드할 스레드가 충분해질 때까지 대기합니다.',
      'deleteArchiveFileAfterDownload': '다운로드 완료 후 아카이브 .zip 파일 삭제',
      'restoreDownloadTasks': '다운로드 작업 복원',
      'restoreDownloadTasksHint': '메타데이터로 다운로드 작업 복원',
      'restoreDownloadTasksSuccess': '다운로드 작업 복원 성공',
      'restoredCount': '복원된 작업 수',
      'restoredGalleryCount': '복원된 갤러리 수',
      'restoredArchiveCount': '복원된 아카이브 수',
      'restoreTasksAutomatically': '자동으로 작업 복원',
      'restoreTasksAutomaticallyHint': '앱 실행 시 자동으로 작업 복원',
      'brokenDownloadPathHint': '다운로드 경로가 손상된 것 같습니다. 다운로드 기능이 낮아질 수 있습니다.',
      'brokenExtraScanPathHint': '기본 로컬 갤러리 경로가 손상된 것 같습니다. 로컬 갤러리가 인식되지 않을 수 있습니다.',
      'useJH2UpdateGallery': 'JH 서버를 사용하여 갤러리 업데이트 가속화',

      /// archive bot settings
      'archiveBotSettings': '아카이브 봇 설정',
      'archiveBotSettingsHint': '아카이브 봇을 사용하여 아카이브 링크를 무료로 가져오세요',
      'apiSetting': 'API 설정',
      'apiAddress': '주소',
      'apiKey': '키',
      'apiKeyHint': '텔레그램 봇에서 받은 키를 입력하세요',
      'dailyCheckin': '일일 체크인',
      'currentBalance': '현재 GP 잔액',
      'checkBalanceFailed': 'GP 잔액 가져오기 실패',
      'checkInFailed': '체크인 실패',
      'checkInSuccess': '체크인 성공',
      'checkInSuccessHint': '획득 GP: %s, 현재 총 GP: %s.',
      'pauseDownloadByInvalidArchiveBotKey': '아카이브 봇 설정이 유효하지 않습니다. 다운로드가 일시 중지되었습니다.',
      'chooseArchiveParseSource': '파싱 소스 변경',
      'official': '공식',
      'archiveBot': '아카이브 봇',
      'changeParseSource2Official': '파싱 소스를 공식으로 변경',
      'changeParseSource2Bot': '파싱 소스를 아카이브 봇으로 변경',
      'invalidParam': '잘못된 파라미터',
      'invalidApiKey': '잘못된 API 키',
      'banned': '차단되었습니다',
      'fetchGalleryInfoFailed': '갤러리 정보 가져오기 실패',
      'insufficientGP': 'GP 부족',
      'parseFailed': '파싱 실패',
      'checkedIn': '오늘 이미 체크인했습니다',
      'serverError': '아카이브 봇 내부 오류',
      'useProxyServer': 'JHenTai 프록시 서버 사용',
      'useProxyServerHint': 'JHenTai 서버를 통해 요청 라우팅',

      /// password setting dialog
      'setPasswordHint': '비밀번호를 넣어주세요.',
      'confirmPasswordHint': '비밀번호를 다시 넣어주세요.',
      'passwordNotMatchHint': '두 비밀번호가 서로 맞지 않습니다. 다시 넣어주세요.',

      /// cloud setting page
      'serverCondition': '서버 상태',
      'configSync': '설정 동기화',
      'configSyncHint': '설정 데이터를 클라우드에 저장(최대 50개)',
      'upload2cloud': '클라우드에 업로드',
      'upload2cloudHint': '현재 로컬 설정을 업로드',
      'tap2upload': '탭하여 업로드',
      'copyIdentificationCodeSuccess': '업로드 성공. 식별 코드가 복사되었습니다.',
      'copyShareCode': '공유 코드 복사',
      'import': '가져오기',
      'save2Local': '로컬에 저장',
      'readIndexRecord': '읽기 진행 상황',
      'quickSearch': 'Quick Search Config',
      'blockRules': '차단 규칙',
      'searchHistory': '검색 기록',
      'galleryHistory': '갤러리 기록',

      /// block rule page
      'configureBlockRuleFailed': '차단 규칙 설정 실패',
      'removeBlockRuleFailed': '차단 규칙 삭제 실패',
      'inputNumberHint': '올바른 숫자를 입력하세요',
      'inputRegexHint': '올바른 정규식을 입력하세요',
      'useBuiltInBlockedUsers': '기본 제공 사용자 차단 목록 활성화',
      'useBuiltInBlockedUsersHint': '차단 목록에 있는 사용자의 갤러리 댓글 필터링',
      'blockingRules': '차단 규칙',
      'blockingRulesHint': '갤러리 및 댓글에 대한 추가 차단 규칙',
      'blockingTarget': '차단 대상',
      'blockingAttribute': '차단 속성',
      'blockingPattern': '차단 패턴',
      'blockingExpression': '차단 표현식',
      'contain': '포함',
      'notContain': '포함하지 않음',
      'regex': '정규식',
      'comment': '댓글',
      'tag': '태그',
      'userId': '사용자 ID',
      'content': '내용',
      'incompleteInformation': '불완전한 정보',
      'noBlockingRuleHint': '최소 1개의 규칙을 추가하세요',
      'notSameBlockingRuleTargetHint': '모든 하위 규칙의 차단 대상이 동일해야 합니다',
      'blockingRuleHelp': '''
Blocking Target: Filter galleries on the list page or filter comments on the details page. All sub-rules under the same rule must have the same blocking target.
Blocking Attribute: Specify the attribute of the target based on which the rule is written to block.
Blocking Pattern: Use regular expressions for complex scenarios.
Blocking Expression: Simple strings or regular expressions.

Note1: Different rules have an OR (||) relationship, while all sub-rules under the same rule have an AND (&&) relationship.
Note2: When blocking tag, the rule will check each tag in the gallery, the expression should be written for a single tag.
Note3: When blocking tag, you need specify full tag with namespace if you use '=' rule.
Note4: You need to use a gallery layout that can display all tags in E-Hentai, such as "Extended," otherwise some galleries may not be filtered correctly.

Example 1: Block galleries that have the "yaoi" tag and do not have the "tomgirl" tag————Gallery Tag Contain male:yaoi && Gallery Tag NotContain male:tomgirl
Example 2: Block comments with a score not exceeding 10————Comment Score <= 10
    ''',

      /// quick search page
      'quickSearch': '빠른 검색',

      /// dashboard page
      'seeAll': '전부',
      'newest': '최신순',

      /// torrent dialog
      'outdated': '만료됨',

      /// tag dialog
      'warningImageHint': 'R18G 이미지, 눌러서 보기',

      /// tagSet dialog
      'chooseTagSet': '태그 세트 선택',

      /// tag namespace
      'language': '언어',
      'artist': '작가',
      'character': '캐릭터',
      'female': '여자',
      'male': '남자',
      'parody': '패러디',
      'group': '그룹',
      'mixed': '혼합',
      'Coser': '코스어',
      'cosplayer': '코스플레이어',
      'reclass': '재분류',
      'temp': '임시',
      'other': '기타',
    };
  }
}
