import 'dart:core';

class pt_BR {
  static Map<String, String> keys() {
    return {
      /// common
      'yes': 'Sim',
      'no': 'Não',
      'cancel': "Cancelar",
      'OK': "OK",
      'reset': "Redefinir",
      'success': "Successo",
      'error': "Erro",
      'failed': "Falhou",
      'reload': 'Recarregar',
      'noMoreData': 'Sem mais',
      'noData': 'Sem dados',
      'operationFailed': 'Falha na opreção',
      'needLoginToOperate': 'Precisa de login para operar',
      'hasCopiedToClipboard': "Copiado para aréa de transferência",
      'networkError': "Erro na conexão com a rede",
      'systemError': "Erro no sistema",
      'invalid': "Inválido",
      'internalError': "Erro interno",
      'you': 'Você',
      'retryHint': 'Por favor, tente novamente após atualizar',
      'stop': 'Parar',
      'attention': 'Atenção',
      'jump': 'Ir para',
      'deleteAll': 'Excluir tudo',
      'connectionTimeoutHint': 'Tempo limite de conexão de rede',
      'receiveDataTimeoutHint': 'Tempo limite de recebimento de dados',
      'archiveError': 'Erro ao baixar arquivo',
      'edit': 'Editar',

      'home': "Início",
      'gallery': "Galeria",
      'setting': 'Configuração',

      /// schedule
      'dawnOfaNewDay': 'É o amanhecer de um novo dia!',
      'encounterMonster': 'Você encontrou um monstro!',
      'encounterMonsterHint': 'Clique para lutar no HentaiVerse.',

      /// unlock page
      'localizedReason': 'Por favor, autentique-se para continuar',
      'tap2Auth': 'Toque para autentique-se',
      'authHint': 'Auth to continue',
      'passwordErrorHint': 'Senha incorreta, tente novamente',

      /// start page
      'TapAgainToExit': 'Toque novamente para sair',

      /// update dialog
      'availableUpdate': 'Atualização disponível!',
      'LatestVersion': 'Versão mais recente',
      'CurrentVersion': 'Versão atual',
      'check': 'Checar',
      'dismiss': 'Dispensar',

      /// login page
      'login': 'Login',
      'notLoggedIn': 'Login',
      'logout': 'Sair',
      'passwordLogin': 'Senha de login',
      'cookieLogin': 'Cookie de login',
      'useWebview': 'Usar Webview',
      'skipCookieVerification': 'Pular verificação',
      'youHaveLoggedInAs': 'Olá:   ',
      'cookieIsBlack': 'Cookie está preto/vazio',
      'cookieFormatError': 'Error no formato do cookie',
      'invalidCookie': 'falha no login ou cookie inválido',
      'loginFail': 'Falha no login',
      'userName': 'Nome de usuário',
      'EHUser': 'Usuário EH',
      'password': 'Senha',
      'needCaptcha': 'Precisa do captcha, por favor fassa login via cookie ou pela web de novo.',
      'userNameOrPasswordMismatch': 'Nome de usuáriio e/ou senha incorreto(s)',
      'copyCookies': 'Copiar cookies',
      'tap2Copy': 'Toque para copiar',
      'webLoginIsDisabled': 'Login pela Web está disabilitado no desktop',
      'loginSuccess': 'Login feito com sucesso',
      'userNameFormHint': 'Tente com cookie em caso de Sad Panda',
      'tap2Login': 'Entrar',
      'parse': 'Analisar',
      'igneousHint': 'igneous (necessário para EX)',
      'refreshIgneousFailed': 'Falha ao atualizar Igneous',

      /// request
      'sadPanda': 'Sad Panda (sem dados). Consulte: https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
      'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',

      /// gallery card
      'filtered': 'Filtrado',

      /// gallery page
      'getGallerysFailed': "Falha ao obter galerias",
      'refreshGalleryFailed': 'Falha ao Atualizar galerias',
      'tabBarSetting': 'Opções da barra de abas',
      'jumpPageTo': 'Pular para à página',
      'range': 'Alcance',
      'current': 'Atual',
      'galleryUrlDetected': 'URL de galeria encontrada na área de transferência',
      'galleryUrlDetectedHint': 'Toque para entrar na página de detalhes',

      /// details page
      'read': 'Ler',
      'download': 'Baixar',
      'favorite': 'Favorito',
      'rating': 'Avaliação',
      'torrent': 'Torrent',
      'archive': 'Arquivo',
      'statistic': 'Estatística',
      'similar': 'Similar',
      'downloading': "Baixando",
      'resume': "Retomar",
      'pause': 'Pausar',
      'finished': 'Finalizado',
      'update': 'Atualizar',
      'submit': 'Enviar',
      'chooseFavorite': 'Escolhher favorito',
      'asYourDefault': 'Como padrão',
      'Note': 'Nota',
      'addNoteHint': 'Escolha um slot antes de adicionar uma nota',
      'uploader': 'Enviador',
      'allComments': 'Todos os comentários',
      'noComments': 'Sem comentários',
      'lastEditedOn': 'Última edição em',
      'getGalleryDetailFailed': 'Falha ao obter detalhes da galeria',
      'cloudflare403': 'Você foi restringido pelo Cloudflare de fazer solicitações de rede. Tente trocar de rede ou usar outro método de login.',
      'invisible2User': 'Esta Galeria é invisível para você',
      'invisibleHints': 'Esta galeria está indisponível ou foi removida.',
      'copyRightHints': 'Esta galeria está indisponível devido a uma reivindicação de direitos autorais por ',
      'refreshGalleryDetailsFailed': 'Falha ao atualizar detalhes da galeria',
      'failToGetThumbnails': "Falha ao obter miniaturas",
      'favoriteGallerySuccess': "Galeria adicionada aos favoritos",
      'favoriteGalleryFailed': "Falha na galeria Favorita",
      'removeFavoriteSuccess': "Favorito removido com sucesso",
      'removeFavoriteFailed': "Falha ao remover favorito",
      'getGalleryFavoriteInfoFailed': 'Falha ao obter informações de favoritos da galeria',
      'favoriteNoteSlotFullHint': 'O slot de notas de favoritos está cheio, exclua algumas notas primeiro',
      'ratingSuccess': 'Avaliação bem-sucedida',
      'ratingFailed': 'Falha na avaliação',
      'voteTagFailed': 'Falha na tag de votação',
      'beginToDownload': 'Começar a baixar',
      'resumeDownload': 'Retomar',
      'pauseDownload': 'Pausar',
      'addNewTagSetSuccess': 'Novo conjunto de tags adicionado com sucesso',
      'addNewWatchedTagSetSuccess': 'Novo conjunto de tags adicionado com sucesso',
      'addNewHiddenTagSetSuccess': 'Novo conjunto de tags ocultas adicionado com sucesso',
      'addNewTagSetSuccessHint': 'Você pode verificar suas tags em Configurações->EH->My Tags',
      'addNewTagSetFailed': 'Falha ao adicionar novo conjunto de tags',
      'VisitorStatistics': 'Estatísticas do visitante',
      'invisible2UserWithoutDonation': 'As estatísticas desta galeria são invisíveis para os usuários sem doação',
      'getGalleryStatisticsFailed': 'Falha ao obter estatísticas da galeria',
      'totalVisits': 'Total de visitas',
      'visits': 'Visitas',
      'imageAccesses': 'Acessos à imagem',
      'period': 'Período',
      'ranking': 'Classificação',
      'score': 'Pontuação',
      'NotOnTheList': 'Não está na lista',
      'getGalleryArchiveFailed': 'Falha ao obter arquivo da galeria',
      'parseGalleryArchiveFailed': 'Falha na análise, certifique-se de que seu [Archiver Settings] em e-hentai é [Manual Select, Manual Start (Default)]',
      'original': 'Original',
      'resample': 'Redimensionamento',
      'beginToDownloadArchive': 'Começar a baixar o arquivo',
      'beginToDownloadArchiveHint': 'Você pode verificar o progresso em Baixar -> Arquivo',
      'updateGalleryError': 'Erro ao atualizar galeria',
      'thisGalleryHasANewVersion': 'Nova versão desta galeria disponível',
      'hasUpdated': 'Atualizado',
      'unpackingArchiveError': 'Erro ao descompactar arquivo',
      'failedToDealWith': 'Falha ao lidar com',
      'hasDownloaded': 'Baixado',
      '410Hints': 'Você registrou muitos bytes baixados neste arquivo e precisa desbloquear novamente este arquivo para continuar.',
      '429Hints': 'Muitas solicitações de download! Tente novamente mais tarde.',
      'getUnpackedImagesFailedMsg': 'JHenTai não pode carregar imagens deste arquivo, por favor verifique seu arquivo local.',
      'getGalleryTorrentsFailed': 'Falha ao obter torrents',
      'chooseArchive': 'Escolher Arquivo',
      'tagSetExceedLimit': 'Não é possível adicionar mais tags porque você atingiu o limite',
      'useTranslation': 'Usar tradução',
      'addTagSuccess': 'Tag adicionada com sucesso',
      'addTagFailed': 'Falha ao adicionar tag',
      'parentGallery': 'Galeria pai',
      'blockUploaderLocally': 'Bloquear usuário localmente',
      'block': 'Bloquear',

      /// detail dialog
      'galleryUrl': 'URL da galeria',
      'title': 'Título',
      'japaneseTitle': 'Título em japonês',
      'category': 'Categoria',
      'publishTime': 'Hora de publicação',
      'pageCount': 'Número de páginas',
      'favoriteCount': 'Contagem de favoritos',
      'ratingCount': 'Contagem de avaliações',

      /// comment page
      'newComment': 'Novo comentário',
      'updateComment': 'Atualizar comentário',
      'commentTooShort': 'O comentário é muito curto',
      'sendCommentFailed': 'Falha ao enviar comentário',
      'voteCommentFailed': 'Falha ao votar cometário',
      'voteCommentFailedHint': 'Tente puxar para baixo para atualizar a página de detalhes primeiro',
      'unknownUser': 'Usuário desconhecido',
      'atLeast3Characters': 'Pelo menos 3 caracteres',
      'noJHenTaiHints': 'Não é possível abrir com JHenTai. Instale o aplicativo primeiro.',
      'blockUser': 'Bloquear usuário',

      /// EHImage
      'reloadImage': "Recarregar imagem",

      /// read page
      'parsingPage': "Página de análise",
      'parsingURL': "URL de análise",
      'parsePageFailed': "Falha na análise da página",
      'parseURLFailed': "Falha na analise da URL",
      'loading': "Caregando",
      'paused': 'Pausar',
      'exceedImageLimits': "Limite de imagens excedido",
      'ehServerError': 'Ocorreu um erro devido ao servidor EH.',
      'unsupportedImagePageStyle': "JHenTai não suporta Multi-Page Viewer (MPV), por favor mude para o estilo padrão em e-hentai.org",
      'toNext': 'Para o próximo',
      'toPrev': 'Para anterior',
      'back': 'Voltar',
      'toggleMenu': 'Alternar menu',
      'share': 'Compartilhar',
      'save': 'Salvar em imagens',

      /// setting page
      'account': 'Conta',
      'EH': 'EH',
      'style': 'Estilo',
      'preference': 'Preferência',
      'network': 'Rede',
      'performance': 'Desempenho',
      'mouseWheel': 'Roda do mouse',
      'advanced': 'Avançado',
      'cloud': 'Nuvem',
      'security': 'Segurança',
      'about': 'Sobre',
      'accountSetting': 'Configurações da conta',
      'styleSetting': 'Configurações de estilo',
      'advancedSetting': 'Configurações avançadas',
      'securitySetting': 'Configurções de segurança',
      'ehSetting': 'Configuração do site EH',
      'readSetting': 'Configurações de leitura',
      'preferenceSetting': 'Configurações de preferência',
      'downloadSetting': 'Configurações de download',
      'networkSetting': 'Configurações de Rede',
      'performanceSetting': 'Configurações de desempenho',
      'mouseWheelSetting': 'Configurações da roda do mouse',

      /// eh setting page
      'site': 'Site',
      'redirect2Eh': 'Redirecionar para EH, se disponível',
      'redirect2EhHint': 'Tente carregar a página de detalhes da galeria do site EH primeiro para melhor desempenho de rede',
      'redirectAllGallery': 'Redirecionar todas as galerias para EH',
      'imDonorHint': 'Se você é um doador, pode ativar isso para acessar galerias no site EX',
      'profileSetting': 'Configurações de perfil',
      'chooseProfileHint': 'Escolha o perfil usado no JHenTai',
      'siteSetting': 'Configuração do site',
      'siteSettingHint': 'Editar configurações do site no e-hentai',
      'showCookie': 'Cookie',
      'redirect2EH': 'Redirecionar para o site EH, se disponível',
      'redirect2Hints': 'Tentar analisar o site EH primeiro',
      'pleaseLogInToOperate': 'Faça login para operar',
      'imageLimits': 'Cota de imagens',
      'resetCost': 'Pressione longamente para redefinir, custo',
      'assets': 'Ativos',
      'isNotDonator': 'Não é doador',
      'fetchImageQuotaFailed': 'Falha ao obter cota de imagens',

      /// tag setting page
      'myTags': 'Minhas Tags',
      'myTagsHint': 'gerenciar tags assistidas e ocultas',
      'localTags': 'Tags locais',
      'localTagsHint': 'Tags de filtro extras',
      'localTagsHint2': 'Galerias com essas tags serão ocultadas',
      'addLocalTags': 'Adicionar tags',
      'hidden': 'Escondido',
      'nope': 'Nope(Não)',
      'getTagSetFailed': 'Falha ao obter conjunto de tags',
      'updateTagSetFailed': 'Falha na atualização do conjunto de tags',
      'updateTagFailed': 'Falha na atualização do conjunto de tags',
      'deleteTagSuccess': 'Falha na atualização do conjunto de tags',
      'deleteTagFailed': 'Falha ao excluir conjunto de tags',
      'addLocalTagHint': 'Pesquise para adicionar nova tag',

      /// Profile Setting page
      'selectedProfile': 'Perfil selecionado',
      'resetIfSwitchSite': 'Será redefinido ao trocar de site',

      /// add host mapping dialog
      'addHostMapping': 'Adicionar mapeamento de host',

      /// Layout
      'layoutMode': 'Modo de layout',
      'mobileLayoutV2Name': 'Celular',
      'mobileLayoutV2Desc': 'Uma coluna',
      'mobileLayoutName': 'Celular(antigo)',
      'mobileLayoutDesc': 'Manutenção interrompida',
      'tabletLayoutV2Name': 'Tablet',
      'tabletLayoutV2Desc': 'Duas colunas',
      'tabletLayoutName': 'Tablet(antigo)',
      'tabletLayoutDesc': 'Manutenção interrompida',
      'desktopLayoutName': 'Desktop',
      'desktopLayoutDesc': 'Duas colunas com barra de abas na esquerda, suporte a teclado',

      /// style setting page
      'enableTagZHTranslation': 'Traduzir nome da tag para Chinês',
      'version': 'Versão',
      'downloadTagTranslationHint': 'Baixando dados..., baixado: ',
      'zhTagSearchOrderOptimization': 'Regra de ordenação de autocompletar de tag chinês',
      'zhTagSearchOrderOptimizationHint': 'Ordenação inteligente por padrão, ordenar por frequência se ativado',
      'themeMode': 'Tema',
      'dark': 'Escuro',
      'light': 'Claro',
      'followSystem': 'Seguir o sistema',
      'themeColor': 'Cor do tema',
      'listStyle': 'Estilo da lista da galeria',
      'flat': 'Reto',
      'flatWithoutTags': 'Reto(Sem tags)',
      'listWithoutTags': 'Cartão(Sem tags)',
      'listWithTags': 'Cartão',
      'waterfallFlowSmall': 'Cascata (Pequena)',
      'waterfallFlowMedium': 'Cascata (Média)',
      'waterfallFlowBig': 'Cascata (Grande)',
      'crossAxisCountInWaterFallFlow': 'Waterfall Flow Column count',
      'pageListStyle': 'Estilo de lista de galeria (Página)',
      'crossAxisCountInGridDownloadPageForGroup': 'Colunas da grade de download (Grupo)',
      'crossAxisCountInGridDownloadPageForGallery': 'Colunas da grade de download (Galeria)',
      'crossAxisCountInDetailPage': 'Colunas de miniaturas da página de detalhes',
      'global': 'Global',
      'auto': 'Automático',
      'moveCover2RightSide': 'Mover a tampa para o lado direito',
      'coverStyle': 'Estilo da tampa',
      'cover': 'Tampa',
      'adaptive': 'Adaptativo',
      'simpleDashboardMode': 'Página inicial simples',
      'simpleDashboardModeHint': 'Ocultar lista de classificação e populares',
      'hideBottomBar': 'Ocultar barra inferior',
      'hideScroll2TopButton': 'Ocultar botão de rolagem para o topo',
      'whenScrollUp': 'Ao rolar para cima',
      'whenScrollDown': 'Ao rolar para baixo',
      'preloadGalleryCover': 'Pré-carregar capa da galeria',
      'preloadGalleryCoverHint': 'Pré-carregar capas de galerias que ainda não estão exibidas na página',
      'enableSwipeBackGesture': 'Ativar gesto de deslizar para voltar',
      'enableLeftMenuDrawerGesture': 'Ativar gesto do menu lateral esquerdo',
      'enableQuickSearchDrawerGesture': 'Ativar pesquisa rápida com gesto de gaveta',
      'drawerGestureEdgeWidth': 'Largura da borda do gesto do menu',
      'alwaysShowScroll2TopButton': 'Sempre mostrar o botão de rolagem para cima',
      'enableDefaultFavorite': 'Ativar favorito padrão',
      'enableDefaultFavoriteHint': 'Pressione longamente para selecionar novamente',
      'enableDefaultTagSet': 'Ativar conjunto de tags padrão',
      'enableDefaultTagSetHint': 'Pressione longamente para selecionar novamente',
      'disableDefaultTagSetHint': 'Selecionar manualmente',
      'launchInFullScreen': 'Iniciar em tela cheia',
      'launchInFullScreenHint': 'Alternar manualmente com F11',
      'disableDefaultFavoriteHint': 'Selecionar manualmente',
      'searchBehaviour': 'Comportamento de pesquisa',
      'inheritAll': 'Herdar tudo',
      'inheritAllHint': 'Usar as últimas opções de pesquisa para a próxima pesquisa',
      'inheritPartially': 'Herdar parcialmente',
      'inheritPartiallyHint': 'Usar as últimas opções de pesquisa para a próxima pesquisa (exceto idioma e categoria)',
      'none': 'Nenhum',
      'noneHint': 'Usar opções de pesquisa padrão para a próxima pesquisa',
      'showAllGalleryTitles': 'Mostrar todos os títulos da galeria',
      'showAllGalleryTitlesHint': 'Mostrar títulos originais e japoneses se disponíveis',
      'showGalleryTagVoteStatus': 'Mostrar status de votação de tags da galeria',
      'showGalleryTagVoteStatusHint': 'Incluir confiança, ceticismo e incorreto',
      'showComments': 'Mostrar comentários',
      'showAllComments': 'Mostrar todos os comentários',
      'showAllCommentsHint': 'Por padrão, apenas os 45 comentários com maior pontuação e os 5 mais recentes serão exibidos',
      'addTag': 'Adicionar tag',
      'addTagHint': 'Insira novas tags, separadas por vírgula',

      /// theme color setting page
      'themeColorSettingHint': 'Atribuir cor diferente para tema claro e escuro',
      'preview': 'Pré-visualização',
      'preset': 'Predefinição',
      'custom': 'Personalizado',

      /// performance setting page
      'maxGalleryNum4Animation': 'Número máx. de galerias para animação de lista na página de download',
      'maxGalleryNum4AnimationHint': 'Desativar animação para grupos com mais galerias que este valor (para estilo de lista)',

      /// mouse wheel setting page
      'wheelScrollSpeed': 'Velocidade de rolagem',
      'ineffectiveInGalleryPage': 'Ineficaz na página da galeria agora.',

      /// advanced setting page
      'enableDomainFronting': 'Ativar frente de Domínio',
      'bypassSNIBlocking': 'Ignorar bloqueio de SNI',
      'hostMapping': 'Mapeamento de host',
      'hostMappingHint': 'Usado para frente de domínio',
      'proxyAddress': 'Endereço de proxy',
      'proxyAddressHint': 'Se você usa servidor proxy, certifique-se de configurá-lo corretamente',
      'saveSuccess': 'Salvo com sucesso',
      'saveFailed': 'Falha ao salvar',
      'updateSuccess': 'Atualizado com sucesso',
      'connectTimeout': 'Tempo limite de conexão',
      'receiveTimeout': 'Tempo limite de recebimento de dados',
      'pageCacheMaxAge': 'Idade máxima do cache de página',
      'pageCacheMaxAgeHint': 'Você pode atualizar o cache atualizando a página',
      'cacheImageExpireDuration': 'Tempo de expiração do cache de imagem',
      'cacheImageExpireDurationHint': 'Remover cache de imagem automaticamente após iniciar o aplicativo',
      'oneMinute': '1 Minuto',
      'tenMinute': '10 Minutos',
      'oneHour': '1 Hora',
      'oneDay': '1 Dia',
      'threeDay': '3 Dias',
      'enableLogging': 'Ativar registro(log)',
      'enableVerboseLogging': 'Ativar registro(log) detalhado',
      'openLog': 'Abrir registro(log)',
      'clearLogs': 'Limpar registros(logs)',
      'clearImagesCache': 'Limpar cache de imagens',
      'longPress2Clear': 'Pressione e segure para limpar',
      'checkUpdateAfterLaunchingApp': 'Buscar atualizações após abrir o app',
      'checkClipboard': 'Verificar se há URL de Galeria na área de transferência',
      'clearPageCache': 'Limpar cache de página',
      'clearSuccess': 'Limpado com Sucesso',
      'superResolution': 'Super resolução de imagem',
      'stopSuperResolution': 'Parar super resolução',
      'deleteSuperResolvedImage': 'Excluir imagem com super resolução',
      'superResolveOriginalImageHint': 'Processar imagem original leva mais tempo, espaço e desempenho. Tem certeza que deseja continuar?',
      'verityAppLinks4Android12': 'Verificar links de aplicativo (Android 12+)',
      'verityAppLinks4Android12Hint': 'Para Android 12+, você precisa adicionar manualmente o link aos links verificados para abrir JHenTai em aplicativos de terceiros',
      'noImageMode': 'Modo sem imagem',
      'exportData': 'Exportar dados',
      'exportDataHint': 'Exportar configurações, regras de bloqueio e histórico',
      'selectExportItems': 'Selecionar itens para exportar',
      'importData': 'Importar dados',
      'importDataHint': 'O aplicativo será encerrado automaticamente após a importação para aplicar a configuração mais recente',

      /// host mapping page
      'hostDataSource': 'Não há necessidade de alterar por padrão.\nFonte de dados: https://dns.google/',

      /// proxy page
      'proxySetting': 'Configuração de proxy',
      'proxyType': 'Tipo de proxy',
      'systemProxy': 'Sistema',
      'httpProxy': 'HTTP',
      'socks5Proxy': 'SOCKS5',
      'socks4Proxy': 'SOCKS4',
      'directProxy': 'DIRETO',
      'address': 'Endereço',

      /// security setting page
      'enablePasswordAuth': 'Ativar autenticação por senha',
      'enableBiometricAuth': 'Ativar autenticação biométrica',
      'enableAuthOnResume': 'Ativar autenticação ao retomar',
      'enableAuthOnResumeHints': '3 segundos de atraso',
      'enableBlurBackgroundApp': 'Ative a página de desfoque ao alternar para o plano de fundo',
      'hideImagesInAlbum': 'Ocultar imagens no álbum',
      'hideImagesInAlbumHints': 'Se você alterou o caminho de download padrão, precisa criar o .nomedia manualmente',

      /// read setting page
      'enableImmersiveMode': 'Habilitar modo imersivo',
      'keepScreenAwakeWhenReading': 'Manter tela ativa durante leitura',
      'enableCustomReadBrightness': 'Ativar brilho personalizado durante leitura',
      'spaceBetweenImages': 'Espaço entre imagens',
      'enableImmersiveHint': 'Esconder barra do sistema',
      'enableImmersiveHint4Windows': 'Ocultar barra de título',
      'deviceOrientation': 'Orientação do dispositivo',
      'landscape': 'Paisagem',
      'portrait': 'Retrato',
      'readDirection': 'Direção da leitura',
      'notchOptimization': 'Otimização de notch',
      'notchOptimizationHint': 'Adicionar espaçamento antes da primeira imagem para evitar o notch e a barra de status',
      'imageRegionWidthRatio': 'Proporção de largura da região de imagem',
      'gestureRegionWidthRatio': 'Proporção de largura da região de gestos',
      'useThirdPartyViewer': 'Usar visualizador personaliado',
      'thirdPartyViewerPath': 'Localização do visualizador personalizado(Arquivo executável)',
      'showThumbnails': 'Mostrar miniaturas',
      'showScrollBar': 'Mostrar barra de rolagem',
      'showStatusInfo': 'Mostrar status na parte inferior',
      'autoModeInterval': 'Intervalo de virada de página',
      'autoModeStyle': 'Estilo do modo automático',
      'scroll': 'Rolagem',
      'turnPage': 'Virar página',
      'top2bottomList': 'De cima para baixo (Contínuo)',
      'left2rightSinglePage': 'Da esquerda para direita (Página única)',
      'left2rightSinglePageFitWidth': 'Da esquerda para direita (Ajustar largura)',
      'right2leftSinglePage': 'Da direita para esquerda (Página única)',
      'right2leftSinglePageFitWidth': 'Da direita para esquerda (Ajustar largura)',
      'left2rightDoubleColumn': 'Da esquerda para direita (Dupla coluna)',
      'right2leftDoubleColumn': 'Da direita para esquerda (Dupla coluna)',
      'left2rightList': 'Da esquerda para direita (Contínuo)',
      'right2leftList': 'Da direita para esquerda (Contínuo)',
      'enablePageTurnByVolumeKeys': 'Usar teclas de volume para virar página',
      'enablePageTurnAnime': 'Ativar animação de virada',
      'enableDoubleTapToScaleUp': 'Ativar toque duplo para aumentar a escala',
      'enableTapDragToScaleUp': 'Ativar toque e arrastar para ampliar',
      'disableGestureWhenScrolling': 'Desativar gesto ao rolar',
      'disablePageTurningOnTap': 'Desativar virar página ao tocar',
      'enableBottomMenu': 'Ativar menu inferior',
      'reverseTurnPageDirection': 'Inverter direção de virar página',
      'turnPageMode': 'Modo de virar página',
      'turnPageModeHint': 'Para a próxima tela ou próxima imagem',
      'enableImageMaxKilobytes': 'Ativar compressão de imagem',
      'imageMaxKilobytes': 'Tamanho máximo de imagem',
      'imageMaxKilobytesHint': 'Imagens maiores que este tamanho serão comprimidas',
      'image': 'Imagem',
      'screen': 'Tela',
      'preloadDistanceInOnlineMode': 'Distância de pré-carregamento (Online)',
      'preloadDistanceInLocalMode': 'Distância de pré-carregamento (Local)',
      'ScreenHeight': 'Tela',
      'preloadPageCount': 'Contagem de páginas de pré-carregamento (Online)',
      'preloadPageCountInLocalMode': 'Contagem de páginas de pré-carregamento (Local)',
      'continuousScroll': 'Rolagem contínua',
      'continuousScrollHint': 'Junte várias imagens',
      'doubleColumn': 'Duas Colunas',
      'displayFirstPageAlone': 'Exibir primeira página sozinha',
      'displayFirstPageAloneGlobally': 'Exibir primeira página sozinha (Global)',
      'toggleFullScreen': 'Alternar tela cheia',
      'enableAutoScaleUp': 'Ativar dimensionamento automático de imagens grandes',
      'enableAutoScaleUpHints': 'Tornar a largura da imagem igual à largura da tela',

      /// preference setting page
      'showR18GImageDirectly': 'Mostrar imagem R18G diretamente',
      'defaultTab': 'Aba padrão',
      'showUtcTime': 'Mostrar horário UTC para galeria',
      'showDawnInfo': 'Mostrar evento de novo amanhecer',
      'showEncounterMonster': 'Mostrar evento de encontro com monstro HentaiVerse',

      /// log page
      'logList': 'Lista de resgistro(log)',

      /// super resolution setting page
      'downloadSuperResolutionModelHint': 'Baixar modelo do Github',
      'modelDirectoryPath': 'Caminho do diretório do modelo',
      'upSamplingScale': 'Escala de amostragem superior',
      'modelType': 'Escolher modelo',
      'x4plusHint': 'Ocupa mais espaço, mas geralmente mais rápido',
      'x4plusAnimeHint': 'Ocupa menos espaço, mas geralmente mais lento',
      'enable4OnlineReading': 'Processar automaticamente durante leitura online',

      /// download page
      'local': 'Local',
      'reDownload': 'Baixar novamente',
      'delete': 'Apagar',
      'deleteTask': 'Apagar apenas tarefa',
      'deleteTaskAndImages': 'Apagar tarefa e imagens',
      'unlocking': 'desbloqueio',
      'unlocked': 'Desbloqueado',
      'parsingDownloadPageUrl': 'Analisando Ⅰ',
      'parsedDownloadPageUrl': 'Analisando Ⅰ',
      'parsingDownloadUrl': 'Analisando Ⅱ',
      'parsedDownloadUrl': 'Analisando Ⅱ',
      'waitingIsolate': 'Aguardando',
      'downloaded': 'Baixado',
      'downloadFailed': 'Download falhou',
      'unpacking': 'Desenpacotando',
      'completed': 'Completo',
      'needReUnlock': 'Precisa de novo desbloqueio',
      'reUnlock': 'Desbloquear novamente',
      'reUnlockHint': 'Atenção! precisa comprar este arquivo novamente para desbloque-lo novamente.',
      'downloadHelpInfo':
          'Se você não conseguir fazer o download e encontrar erros como a tabela não existe nos logs, desinstale o aplicativo atual e reinstale.',
      'localGalleryHelpInfo': 'Carregar galerias não baixadas pelo JHenTai. Adicione configuração em Download Setting -> Extra Gallery Scan Path e atualize.',
      'localGalleryHelpInfo4iOSAndMacOS': 'Carregar galerias não baixadas pelo JHenTai. Coloque suas galerias no caminho de download padrão e atualize.',
      'deleteLocalGalleryHint': 'Excluir seus arquivos locais',
      'priority': 'Prioridade',
      'highest': 'Alta',
      'default': 'Padrão',
      'newGalleryCount': 'Nova contagem de galerias',
      'changePriority': 'Mudar prioridade',
      'changeGroup': 'Mudar grupo',
      'chooseGroup': 'Escolhar grupo',
      'renameGroup': 'Renomear grupo',
      'deleteGroup': 'Apagar grupo',
      'existingGroup': 'Grupo existente',
      'groupName': 'Nome do grupo',
      'drag2sort': 'Arrastar para ordenar',
      'switch2GridMode': 'Mudar para modo grade',
      'switch2ListMode': 'Mudar para modo lista',
      'multiSelect': 'Seleção múltipla',
      'multiSelectHint': 'Toque para selecionar',
      'resumeAllTasks': 'Retomar todas as tarefas',
      'pauseAllTasks': 'Pausar todas as tarefas',
      'requireDownloadComplete': 'Exigir download completo',
      'operationHasCompleted': 'A operação foi concluída',
      'operationInProgress': 'A operação está em andamento',
      'startProcess': 'Iniciar processo',
      'multiReDownloadHint': 'Você irá baixar novamente todas as galerias selecionadas.',
      'multiChangeGroupHint': 'Você irá alterar o grupo de todas as galerias selecionadas.',
      'multiDeleteHint': 'Você irá excluir todas as galerias selecionadas.',
      'blankImageHint': 'O download da imagem retornou um resultado vazio, tentando reanalisar.',
      'peakHoursHint': 'Baixar arquivos originais durante horários de pico requer GP, e você não tem suficiente, o download foi pausado.',
      'oldGalleryHint': 'Baixar arquivos originais desta galeria requer GP, e você não tem suficiente.',
      'exceedLimitHint': 'Você atingiu o limite de imagens e não tem GP suficiente para comprar uma cota de download.',
      'deleteUpdatingDependentHint': 'Outra galeria depende desta galeria.',
      'migrateToDownload': 'Migrar para 「Download」',
      'refresh': 'Atualizar',

      /// download search page
      'simpleSearch': 'Simples',
      'regexSearch': 'Regex',

      /// search dialog
      'searchConfig': 'Opções de pesquisa',
      'addTabBar': 'Adicionar barra de guias',
      'updateTabBar': 'Atualizar barra de guias',
      'addQuickSearch': 'Adicionar',
      'updateQuickSearch': 'Atualizar',
      'filter': 'Filtro',
      'tabBarName': 'Nome da TabBar',
      'quickSearchName': 'Nome',
      'pleaseInputValidName': 'Por favor insira um nome válido',
      'sameNameExists': 'O mesmo nome já existe',
      'sameConfigExists': 'Configuração idêntica já existe',
      'searchType': 'Tipo de pesquisa',
      'popular': 'Popular',
      'ranklist': 'Lista de classificação',
      'ranklistBoard': 'lista de classificação (placa)',
      'watched': 'Assistido',
      'history': 'História',
      'keyword': 'Palavra-chave',
      'orderBy': 'Ordenar por',
      'favoritedTime': 'Hora de adição aos favoritos',
      'publishedTime': 'Hora de publicação',
      'backspace2DeleteTag': 'Backspace para excluir tag',
      'searchGalleryName': 'Pesquisar nome da galeria',
      'searchGalleryTags': 'Pesquisar tags da galeria',
      'searchGalleryDescription': 'Pesquisar descrição da galeria',
      'onlySearchExpungedGalleries': 'Pesquisar galerias eliminadas',
      'onlyShowGalleriesWithTorrents': 'Mostrar apenas galerias com torrents',
      'searchLowPowerTags': 'Pesquisar tags de baixo consumo',
      'searchDownVotedTags': 'Pesquisar tags pouco votadas',
      'pageAtLeast': 'Página no mínimo',
      'pageAtMost': 'Página no máximo',
      'pagesBetween': 'Páginas entre',
      'pageRangeSelectHint': 'min <= 1000, max >= 10\nmin/max <= 0.8, max-min >= 20',
      'to': 'para',
      'minimumRating': 'Classificação mínima',
      'disableFilterForLanguage': 'Desativar filtro para idioma',
      'disableFilterForUploader': 'Desativar filtro para uploader',
      'disableFilterForTags': 'Desativar filtro para Tags',
      'searchName': 'Nome de pesquisa',
      'searchTags': 'Tags de pesquisa',
      'searchNote': 'Nota de pesquisa',
      'allTime': 'Tudo',
      'year': 'Ano',
      'month': 'Mês',
      'day': 'Dia',
      'favoriteHint': 'Qualificadores: tag/título/comentário/nota de favorito',

      /// popular page
      'getPopularListFailed': 'Falha ao obter lista de popularidade',

      /// ranklist page
      'getRanklistFailed': 'Falha ao obter lista de classificação',
      'getSomeOfGallerysFailed': 'Falha ao obter algumas das galerias',

      /// history page
      'getHistoryGallerysFailed': 'Falha ao obter alguns dos histórico galerias',

      /// search page
      'search': 'Pesquisar',
      'searchFailed': 'Falha ao pesquisar',
      'fileSearchFailed': 'Falha ao pesquisr arquivo',
      'tab': 'Aba',
      'openGallery': 'Abrir galeria',
      'tapChip2Delete': 'Toque no chip para excluir\nPressione longamente o botão para excluir tudo',
      'accurateCountTemplate': '%s resultados',
      'hundredsOfCountTemplate': 'Centenas de resultados',
      'thousandsOfCountTemplate': 'Milhares de resultados',

      /// about page
      'author': 'Autor',
      'Q&A': 'P&R',
      'telegramHint': 'Você pode fazer suas perguntas no github primeiro',

      /// download setting page
      'downloadPath': 'Caminho de download',
      'changeDownloadPathHint':
          'Pressione e segure para mudar. Alterar o caminho de download copiará as galerias baixadas automaticamente e manterá os arquivos antigos. Se você achar que não consegue carregar a imagem, tente redefinir o caminho.',
      'resetDownloadPath': 'Redefinir caminho de download',
      'singleImageSavePath': 'Caminho para salvar imagem única',
      'extraGalleryScanPath': 'Caminho extra de varredura de galeria',
      'extraGalleryScanPathHint': 'Para escanear e carregar galerias locais',
      'downloadOriginalImage': 'Imagem original',
      'downloadOriginalImageByDefault': 'Escolher imagem original por padrão',
      'originalImage': 'Original',
      'resampleImage': 'Redimensionada',
      'defaultGalleryGroup': 'Grupo de galeria padrão',
      'defaultArchiveGroup': 'Grupo de arquivo padrão',
      'never': 'Nunca',
      'manual': 'Manual',
      'always': 'Sempre',
      'longPress2Reset': 'Pressione e segure para redefinir',
      'needPermissionToChangeDownloadPath': 'Precisa de permissão para alterar o caminho de download',
      'invalidPath': 'Caminho inválido. Evite usar o caminho do sistema, caminho raiz ou caminho do cartão SD.',
      'downloadTaskConcurrency': 'Download simultâneo',
      'needRestart': 'Precisa reiniciar',
      'speedLimit': 'Limite de velocidade',
      'speedLimitHint': 'Não baixar muito rápido',
      'per': 'por',
      'images': 'imagens',
      'downloadTimeout': 'Tempo limite de download',
      'downloadAllGallerysOfSamePriority': 'Baixar todas as galerias de mesma prioridade',
      'downloadAllGallerysOfSamePriorityHint': 'Baixar apenas 1 galeria simultaneamente no grupo de maior prioridade por padrão',
      'alwaysUseDefaultGroup': 'Sempre usar o grupo padrão',
      'enableStoreMetadataForRestore': 'Ativar metadados da loja para restauração',
      'enableStoreMetadataForRestoreHint': 'Se desabilitar isso, você não poderá restaurar as tarefas de download',
      'archiveDownloadIsolateCount': 'Número de threads de download de arquivo',
      'archiveDownloadIsolateCountHint': 'A soma de threads para todas as tarefas precisa ser menor que 10, caso contrário o download falhará',
      'manageArchiveDownloadConcurrency': 'Gerenciar concorrência de download de arquivo',
      'manageArchiveDownloadConcurrencyHint': 'O arquivo aguardará até que haja threads suficientes para baixar',
      'deleteArchiveFileAfterDownload': 'Excluir arquivo .zip após download',
      'restoreDownloadTasks': 'Restaurar tarefas de download',
      'restoreDownloadTasksHint': 'Restaurar tarefas de download por metadados',
      'restoreDownloadTasksSuccess': 'Tarefas de download restauradas com sucesso',
      'restoredCount': 'Contagem de tarefas restaurada',
      'restoredGalleryCount': 'Contagem de galerias restaurada',
      'restoredArchiveCount': 'Contagem de arquivos restaurada',
      'restoreTasksAutomatically': 'Restaurar tarefas automaticamente',
      'restoreTasksAutomaticallyHint': 'Restaurar tarefas automaticamente ao iniciar o aplicativo',
      'brokenDownloadPathHint': 'Parece que seu caminho de download está quebrado, a função de download pode ser ineficaz',
      'brokenExtraScanPathHint': 'Parece que seu caminho de galeria local padrão está danificado, a galeria local pode não ser reconhecida',
      'useJH2UpdateGallery': 'Usar servidor JH para acelerar atualizações de galeria',

      /// archive bot settings
      'archiveBotSettings': 'Configurações do bot de arquivo',
      'archiveBotSettingsHint': 'Usar bot de arquivo para obter links de arquivo gratuitamente',
      'apiSetting': 'Configuração de API',
      'apiAddress': 'Endereço',
      'apiKey': 'Chave',
      'apiKeyHint': 'Insira a chave que você obteve do bot do Telegram',
      'dailyCheckin': 'Check-in diário',
      'currentBalance': 'Saldo atual de GP',
      'checkBalanceFailed': 'Falha ao obter saldo de GP',
      'checkInFailed': 'Falha no check-in',
      'checkInSuccess': 'Check-in bem-sucedido',
      'checkInSuccessHint': 'GP obtido: %s, total de GP atual: %s.',
      'pauseDownloadByInvalidArchiveBotKey': 'Configurações do bot de arquivo são inválidas, download pausado',
      'chooseArchiveParseSource': 'Alterar fonte de análise',
      'official': 'Oficial',
      'archiveBot': 'Bot de arquivo',
      'changeParseSource2Official': 'Alterar fonte de análise para oficial',
      'changeParseSource2Bot': 'Alterar fonte de análise para bot de arquivo',
      'invalidParam': 'Parâmetro inválido',
      'invalidApiKey': 'Chave de API inválida',
      'banned': 'Você foi banido',
      'fetchGalleryInfoFailed': 'Falha ao obter informações da galeria',
      'insufficientGP': 'GP insuficiente',
      'parseFailed': 'Falha na análise',
      'checkedIn': 'Check-in já realizado hoje',
      'serverError': 'Erro interno do bot de arquivo',
      'useProxyServer': 'Usar servidor proxy JHenTai',
      'useProxyServerHint': 'Rotear solicitações pelo servidor JHenTai',

      /// password setting dialog
      'setPasswordHint': 'Por favor, insira sua senha',
      'confirmPasswordHint': 'Por favor, insira sua senha novamente',
      'passwordNotMatchHint': 'As senhas não coincidem, tente novamente',

      /// cloud setting page
      'serverCondition': 'Condição do servidor',
      'configSync': 'Sincronização de configuração',
      'configSyncHint': 'Armazenar seus dados de configuração na nuvem (até 50 entradas)',
      'upload2cloud': 'Enviar para a nuvem',
      'upload2cloudHint': 'Enviar sua configuração local atual',
      'tap2upload': 'Toque para enviar',
      'copyIdentificationCodeSuccess': 'Enviado com sucesso. Código de identificação copiado',
      'copyShareCode': 'Copiar código de compartilhamento',
      'import': 'Importar',
      'save2Local': 'Salvar localmente',
      'readIndexRecord': 'Progresso de leitura',
      'quickSearch': 'Quick Search Config',
      'blockRules': 'Regras de bloqueio',
      'searchHistory': 'Histórico de pesquisa',
      'galleryHistory': 'Histórico de galerias',

      /// block rule page
      'configureBlockRuleFailed': 'Falha ao configurar regra de bloqueio',
      'removeBlockRuleFailed': 'Falha ao remover regra de bloqueio',
      'inputNumberHint': 'Por favor, insira um número correto',
      'inputRegexHint': 'Por favor, insira uma regex correta',
      'useBuiltInBlockedUsers': 'Ativar lista de usuários bloqueados integrada',
      'useBuiltInBlockedUsersHint': 'Filtrar comentários de galerias de usuários na lista de bloqueio',
      'blockingRules': 'Regras de bloqueio',
      'blockingRulesHint': 'Regras de bloqueio adicionais para galerias e comentários',
      'blockingTarget': 'Alvo de bloqueio',
      'blockingAttribute': 'Atributo de bloqueio',
      'blockingPattern': 'Padrão de bloqueio',
      'blockingExpression': 'Expressão de bloqueio',
      'contain': 'Contém',
      'notContain': 'Não contém',
      'regex': 'Regex',
      'comment': 'Comentário',
      'tag': 'Tag',
      'userId': 'ID do usuário',
      'content': 'Conteúdo',
      'incompleteInformation': 'Informação incompleta',
      'noBlockingRuleHint': 'Adicione pelo menos 1 regra',
      'notSameBlockingRuleTargetHint': 'Todas as sub-regras devem ter o mesmo alvo de bloqueio',
      'blockingRuleHelp': '''
Alvo de Bloqueio: Filtrar galerias na página de lista ou filtrar comentários na página de detalhes. Todas as sub-regras sob a mesma regra devem ter o mesmo alvo de bloqueio.
Atributo de Bloqueio: Especificar o atributo do alvo com base no qual a regra é escrita para bloquear.
Padrão de Bloqueio: Use expressões regulares para cenários complexos.
Expressão de Bloqueio: Strings simples ou expressões regulares.

Nota 1: Regras diferentes têm uma relação OU (||), enquanto todas as sub-regras sob a mesma regra têm uma relação E (&&).
Nota 2: Ao bloquear uma tag, a regra verificará cada tag na galeria, a expressão deve ser escrita para uma única tag.
Nota 3: Ao bloquear uma tag, você precisa especificar a tag completa com o namespace se usar a regra '='.
Nota 4: Você precisa usar um layout de galeria que possa exibir todas as tags no E-Hentai, como "Extended", caso contrário, algumas galerias podem não ser filtradas corretamente.

Exemplo 1: Bloquear galerias que têm a tag "yaoi" e não têm a tag "tomgirl"————Gallery Tag Contain male:yaoi && Gallery Tag NotContain male:tomgirl
Exemplo 2: Bloquear comentários com uma pontuação não superior a 10————Comment Score <= 10
    ''',

      /// quick search page
      'quickSearch': 'Pesquisa rápida',

      /// dashboard page
      'seeAll': 'Tudo',
      'newest': 'Mias novo',

      /// torrent dialog
      'outdated': 'Desatualizado',

      /// tag dialog
      'warningImageHint': 'Imagem R18G, toque para ver',

      /// tagSet dialog
      'chooseTagSet': 'Escolher conjunto de tags',

      /// tag namespace
      'language': 'Idioma',
      'artist': 'Artista',
      'character': 'Personagem',
      'female': 'Feminino',
      'male': 'Masculino',
      'parody': 'Paródia',
      'group': 'Grupo',
      'mixed': 'Misturado',
      'Coser': 'Cosplayer',
      'cosplayer': 'Cosplayer',
      'reclass': 'Reclassificar',
      'temp': 'Temporário',
      'other': 'Outro',
    };
  }
}
